### ISSUE TITLE
Crashing with some paths

### ISSUE THREAD

**Issue by Asek3** [embeddedt/ModernFix#1]
[crash-2023-01-03_19.28.43-client.txt](https://github.com/embeddedt/ModernFix/files/10338592/crash-2023-01-03_19.28.43-client.txt)

**Comment by embeddedt** [comment]
Thanks! It's an honor to hear from a prominent developer. By the way, how did you find this mod?

**Comment by Asek3** [comment]
Just checking your profile every day after after seeing ArchaicFix
