### ISSUE TITLE
Chunk saving fix didn't work properly

### ISSUE THREAD

**Issue by Kasualix** [embeddedt/ModernFix#10]
![image](https://user-images.githubusercontent.com/110756250/212522977-ec11feac-9582-4b91-b37f-18de3be60ef6.png)
dimension: [atum](https://github.com/TeamMetallurgy/Atum2)
[related code](https://github.com/embeddedt/ModernFix/blob/main/src/main/java/org/embeddedt/modernfix/mixin/bugfix/edge_chunk_not_saved/ChunkManagerMixin.java)
For the tree, it works well. But the terrain looks bad.
I have used the original mod [Chunk Saving Fix](https://github.com/SuperCoder7979/chunksavingfix-forge) a long time ago which do have this problem too, but this mod seemed to be at end of life, so I didn't report the problem to SuperCoder7979.
Fortunately, this strange terrain appears rarely, but it would be nice if you can fix it.

**Comment by embeddedt** [comment]
Does this happen in other dimensions or only in Atum?

**Comment by Kasualix** [comment]
not only in Atum, but I can also see that in Overworld.
