### ISSUE TITLE
[Crash] can star loading mod crash with mixin

### ISSUE THREAD

**Issue by coco875** [embeddedt/ModernFix#101]
[latest.log](https://github.com/embeddedt/ModernFix/files/11479732/latest.log)

**Comment by embeddedt** [comment]
This is a mod conflict, please try to narrow down which mod causes the crash. I would guess it is some other optimization mod.

**Comment by coco875** [comment]
Ok it's just curseforge who downgrade version of mod (it's with FPS Reducer 2.0.3)
