### ISSUE TITLE
[1.16.5] Error loading mods

### ISSUE THREAD

**Issue by Le7emps** [embeddedt/ModernFix#102]
Failure message: Mowzie's Mobs (mowziesmobs) encountered an error during the complete event phase
		java.lang.ArrayIndexOutOfBoundsException: Index 1 out of bounds for length 0

[crash-2023-05-17_18.27.34-fml.txt](https://github.com/embeddedt/ModernFix/files/11497077/crash-2023-05-17_18.27.34-fml.txt)
[latest.log](https://github.com/embeddedt/ModernFix/files/11497079/latest.log)

**Comment by embeddedt** [comment]
This appears to be a bug in Mowzie's Mobs, not ModernFix. But I have added a workaround that should fix it. It will be included in the next release.

**Comment by Le7emps** [comment]
Thx，this situation can also occur with twilightforest and dungeons_gears.
