### ISSUE TITLE
When using Modernfix 1.16.5 the screen resolution gets overriden.

### ISSUE THREAD

**Issue by bravoso** [embeddedt/ModernFix#103]
I've a modpack that relies on the default and expected 1024x768 for the custom main menu to be applied. For some reason, when i add the ModernFix mod, the game changes the resolution for a 16:9 smaller one, where the entire screen gets huge.

On the removal of ModernFix the game opens on the expected 1024x768 resolution inputed by the game laucher.

I've looked on the fixes mixins to find a potential cause, but wasn't sucessfull. Any idea on a possible fix?

**Comment by embeddedt** [comment]
Does it happen if you turn off `mixin.bugfix.preserve_early_window_pos`?

**Comment by bravoso** [comment]
no, it does not! Thank you!

**Comment by embeddedt** [comment]
What launcher are you using that allows setting the resolution and the game actually respecting it? I thought this hasn't worked since 1.6 (i.e. for years).

**Comment by bravoso** [comment]
Curseforge, it uses the default MC launcher

**Comment by embeddedt** [comment]
The next release of ModernFix will automatically disable this change if non-default (i.e. not 854x480) dimensions are specified for the game window by a launcher.
