### ISSUE TITLE
Texture corruption with OptiFine

### ISSUE THREAD

**Issue by LegendaryCrystalFox** [embeddedt/ModernFix#104]
With the latest (1.15.0) I'm getting pink and black textures my entire world is nothing but this:
![2023-05-20_20 08 49](https://github.com/embeddedt/ModernFix/assets/34899528/68006e1a-1305-42d8-954a-4e39a4d8a811)
As well in the tile screen: ![Screenshot 2023-05-20 234803](https://github.com/embeddedt/ModernFix/assets/34899528/249db13f-58ab-428e-9133-441d01e8fe2c)
Version 1.13.1 seems to work without this error im not sure what may be causing it.
I am unable to post the lastest.log due to the file size being to large for GitHub or Pastebin. I do have Optifine installed tho I'm wondering if perhaps that might be an issue? 
I might be able to send over the log file through Discord but I'm not entirely sure (I do have nitro).

**Comment by embeddedt** [comment]
Please test without OptiFine first. If the log file is too large zipping it
will probably work.

**Comment by LegendaryCrystalFox** [comment]
Testing Without OptiFine seemed to have worked but is there any workaround because I would like to keep Optifine for my texture packs?

**Comment by embeddedt** [comment]
If you send the log, I can take a look at it to see if there is anything I can do but OptiFine is very invasive and hard to support.

**Comment by LegendaryCrystalFox** [comment]
[latest.zip](https://github.com/embeddedt/ModernFix/files/11525241/latest.zip)
Here's the latest log let me know if you need the debug or not.

**Comment by embeddedt** [comment]
Disabling `mixin.perf.faster_texture_loading` and `mixin.perf.faster_texture_stitching` in the ModernFix config will fix this; the next version of ModernFix will do it automatically.

**Comment by LegendaryCrystalFox** [comment]
Alright, thank you!

**Comment by LegendaryCrystalFox** [comment]
My world won't load any chunks when re-adding Optifine?
[latest.zip](https://github.com/embeddedt/ModernFix/files/11525434/latest.zip)

**Comment by embeddedt** [comment]
If it only occurs with OptiFine it's likely another compatibility issue, as mentioned on the CF page I do not officially support OptiFine. Unfortunately this time it's not clear which option in ModernFix might be conflicting.

**Comment by LegendaryCrystalFox** [comment]
Alright, thanks again for helping me. I understand alot of mods tend to not have support for OptiFine. I'll probably do more testing on my end and see if I can find a workaround and if not oh well.

**Comment by embeddedt** [comment]
The original incompatibility should now be fixed as of the latest release.
