### ISSUE TITLE
[1.18.2] Crashes with Changed:MC

### ISSUE THREAD

**Issue by Y1rd** [embeddedt/ModernFix#108]
Version 2.6.0 crashes with [Changed:MC](https://github.com/LtxProgrammer/Changed-Minecraft-Mod).
Doesn't happen with version 2.5.2

**Crash Log:**
https://pastebin.com/wdnfXzJZ

**Comment by embeddedt** [comment]
Disabling `mixin.perf.faster_texture_loading` in the ModernFix config should fix it for now; I will make the mod do this automatically in the next release.

**Comment by Y1rd** [comment]
Sounds good, probably related to how the mod mixes textures together (applying latex to a block changes its texture).

**Comment by embeddedt** [comment]
Latest release includes this change.
