### ISSUE TITLE
[Question] About removing biome temperature cache.

### ISSUE THREAD

**Issue by Kasualix** [embeddedt/ModernFix#11]
Does [this](https://github.com/embeddedt/ModernFix/blob/main/src/main/java/org/embeddedt/modernfix/mixin/perf/remove_biome_temperature_cache/BiomeMixin.java) work with [Saturn](https://www.curseforge.com/minecraft/mc-mods/saturn)?

> Saturn fixes biome temperature cache memory leak which eats a lot of memory, now it gives a huge performance boost to the memory.

**Comment by embeddedt** [comment]
They work together fine as far as I know. Mine is more aggressive and bypasses the cache entirely (to match Lithium's behavior in newer versions), while Saturn just tweaks the cache implementation. You don't really need Saturn installed if ModernFix is installed, but it shouldn't cause any issues.
