### ISSUE TITLE
ModernFix Breaks KubeJS NetworkEvents data

### ISSUE THREAD

**Issue by KostromDan** [embeddedt/ModernFix#111]
This is due to the fact that this mod replaces some network classes with its own and as a result, probably some kind of conflict, the event.data becomes empty. 
Breaked events:
/client_scripts/ | NetworkEvents.fromServer
/server_scripts/ | NetworkEvents.fromClient
event.data is alvays empty with modern fix.

**Comment by embeddedt** [comment]
What Minecraft version? I assume you're using Forge.

**Comment by KostromDan** [comment]
> What Minecraft version? I assume you're using Forge.

modernfix-mc1.19.2-forge-3.6.0.jar

**Comment by KostromDan** [comment]
> What Minecraft version? I assume you're using Forge.


scripts for testing:
client:
```js
NetworkEvents.fromServer('test', event => {
    event.player.tell(`fromServer ${event.data}`)
    event.player.sendData('test', {'test':'test'})
})
```
```js
NetworkEvents.fromClient('test', event => {
    event.player.tell(`fromClient ${event.data}`)
})
BlockEvents.rightClicked(event => {
    if (event.hand == 'main_hand') {
        event.player.sendData('test', {'test': 'test'})
    }
})
```

**Comment by KostromDan** [comment]
Tested on fabric, the problem is also relevant there.

**Comment by embeddedt** [comment]
Thanks, I appreciate the example scripts as I couldn't find any documentation on how to use these events. :laughing: 

I was able to track down and fix the underlying issue. The fix will be in the next release. For now disabling `mixin.perf.nbt_memory_usage` will work around it, or you can use the unreleased version via the link in the README.

**Comment by embeddedt** [comment]
Latest release includes the fix, thanks again for the report.
