### ISSUE TITLE
Sophisticated Backpacks On the ground collapse

### ISSUE THREAD

**Issue by fzrdwa123456** [embeddedt/ModernFix#113]
Can you talk to Sophisticated Backpacks mod Compatibility ？
[crash-2023-05-27_23.21.43-client.txt](https://github.com/embeddedt/ModernFix/files/11582353/crash-2023-05-27_23.21.43-client.txt)

**Comment by fzrdwa123456** [comment]
Can you fix it

**Comment by fzrdwa123456** [comment]
My English is not very good because I use a translator

**Comment by fzrdwa123456** [comment]
minecraft1.18.2 forge 40.2.2

**Comment by fzrdwa123456** [comment]
modernfix 2.6.0

**Comment by embeddedt** [comment]
It's an issue with Sophisticated Backpacks which needs to be fixed on their end. See https://github.com/P3pp3rF1y/SophisticatedBackpacks/issues/775.
