### ISSUE TITLE
Crash when using JEI + EMI and searching in Creative tab

### ISSUE THREAD

**Issue by SiverDX** [embeddedt/ModernFix#114]
MC Version: 1.19.2
Mod Version: 3.6.0

See https://github.com/emilyploszaj/emi/issues/177

Is it possible to add an additional check for `emi` & `jei` being present?

EMI: https://www.curseforge.com/minecraft/mc-mods/emi

**Comment by embeddedt** [comment]
I've fixed this in the dev builds, will be in the next release.

**Comment by embeddedt** [comment]
Latest release includes the fix.
