### ISSUE TITLE
Crash when entering the world

### ISSUE THREAD

**Issue by Kasualix** [embeddedt/ModernFix#115]
Modpack: E6E
Latest log:  https://pastebin.ubuntu.com/p/KYVXq5rYfB/ (spam...)
Crash report: https://pastebin.ubuntu.com/p/7YfBhk95FN/

**Comment by embeddedt** [comment]
Seems most likely to be some mod accessing NBT from multiple threads. Guess I will have to make `CanonizingStringMap` thread-safe. Does it happen consistently or only sometimes?

**Comment by Kasualix** [comment]
Sometimes maybe. I created several worlds but only this first one got crashed.

**Comment by embeddedt** [comment]
I think it's most likely some mod interaction that mutates this from multiple threads and making the NBT map thread-safe would reduce performance in all other scenarios. So I think I'll leave this one unfixed, doesn't seem to have been reported commonly.

**Comment by embeddedt** [comment]
After stumbling across a similar issue in 1.20 with a completely different mod I tracked this down to Forge most likely firing a config event to the same mod concurrently. Should be fixed in 5.0.4 and newer by https://github.com/embeddedt/ModernFix/commit/41b71c5e59d4539e4421ff3e43150bb7efde06c6.
