### ISSUE TITLE
[1.18.2] Hang with Dimensional Threading

### ISSUE THREAD

**Issue by Reshy** [embeddedt/ModernFix#118]
https://github.com/CCr4ft3r/DimensionalThreading-Reforged/issues/7

I reported it over on Dimensional threading, but the dev over there says it's an issue with Modern Fix.  It causes the internal server to hang upon entering the End when both mods are installed.

**Comment by embeddedt** [comment]
Thanks. Please confirm that disabling `mixin.bugfix.chunk_deadlock` and/or upgrading to the dev build resolves this.

**Comment by Reshy** [comment]
On the dev build, there's a large lag spike, but it doesn't hang the server completely.

![2023-06-02_03 55 39](https://github.com/embeddedt/ModernFix/assets/2096384/007cdcd2-fa0d-4bad-ae02-e52ce69f9c91)

**Comment by embeddedt** [comment]
If you're entering the End for the first time a lag spike is normal to my knowledge.

**Comment by embeddedt** [comment]
I'm going to close this for now as based on a code analysis, `mixin.bugfix.chunk_deadlock` would have caused the original issue and is now automatically disabled. Do note that I don't conduct my regular testing with Dimensional Threading as it changes fundamental vanilla behavior.
