### ISSUE TITLE
[Crash] After an update to 4.2.0 (1.19.4)

### ISSUE THREAD

**Issue by tajemniktv** [embeddedt/ModernFix#119]
Hi, after updating to the latest (4.2.0) on mc 1.19.4 it sudennly started crashing. It might be most likely a mod incompat. I was hoping that you might see something in logs, so here's a full log: https://mclo.gs/K8cYhuk
And here's just a crash report: https://mclo.gs/EF1yM09

**Comment by SplendidAlakey** [comment]
Having the same exact crash on 1.19.2, Quilt only. Definitely a mod conflict, but not just some single mod. I could narrow down one of mine to [C2ME](https://www.curseforge.com/minecraft/mc-mods/c2me-fabric), however, there are more. You can consistently reproduce the crash with C2ME + ModernFix on Quilt, though.

As a temporary workaround set `mixin.perf.nbt_memory_usage=false` in the config.

**Comment by embeddedt** [comment]
These issues should be resolved in the latest dev build; I will make a release later today.
