### ISSUE TITLE
About priority

### ISSUE THREAD

**Issue by Kasualix** [embeddedt/ModernFix#12]
I saw [this](https://github.com/embeddedt/ModernFix/issues/8#issuecomment-1382952038), but I just don't want to abandon this feature as my modpack always uses one trillion years to start jei when I enter my world.
Can I use "mixin.perf.async_jei=true" in modernfix-mixins.properties to override [this](https://github.com/embeddedt/ModernFix/blob/bee6c6f272d0ffb35998bc3eb4b4c87d67f7d29c/src/main/java/org/embeddedt/modernfix/core/config/ModernFixEarlyConfig.java#L41)?

> _Besides, I'm also a Modern UI user that can't leave it, but I have NEVER crashed with it (and with ModernFix since it first released at Jan 5, 2023) in my 300+ mods' modpack. My modpack don't have a need for strongholds and I have disabled them a long time ago so I can't tell anything with [this](https://github.com/embeddedt/ModernFix/issues/8). But [A0000Xz](https://github.com/A0000Xz) is surely using a old version of Modern UI ([here](https://github.com/embeddedt/ModernFix/issues/7#issuecomment-1382953191)) and it must have bug(s). So I wonder if you could think about it again, should we really abandon "mixin.perf.async_jei" for an older version of Modern UI?_

**Comment by Kasualix** [comment]
Modern UI can also disable its tooltip type in its config
![image](https://user-images.githubusercontent.com/110756250/213756096-9dd366c5-63ad-47cd-9730-796257a8ceaf.png)

**Comment by embeddedt** [comment]
If that option is disabled then you could probably re-enable async JEI without problems. But I would prefer to leave it disabled by default as experienced users would be more likely to know which configs to tweak.

**Comment by Kasualix** [comment]
ok, thank you!
