### ISSUE TITLE
Dynamic resources crash with Physics Mod

### ISSUE THREAD

**Issue by Rad233** [embeddedt/ModernFix#120]
Fabric 1.18.2: 
		fabricloader: Fabric Loader 0.14.10
		incendium: Incendium 5.0.8
		modernfix: ModernFix 2.7.0
		nullscape: Nullscape 1.1.4
		physicsmod: Physics Mod 2.12.3
		terralith_loader: Terralith Loader 1.0.0
		terralith: Terralith 2.2.4
		unfixed-seeds: Unfixed Seeds 1.0.1
**Description:** 
Dynamic resources option enabled+physic mod causes crash in rare cases.
The crash report below should provide enough info: 
[crash-2023-06-03_20.32.35-client.txt](https://github.com/embeddedt/ModernFix/files/11642632/crash-2023-06-03_20.32.35-client.txt)

**Comment by embeddedt** [comment]
Sorry for the delay, pretty sure 5.2.0 will fix this.
