### ISSUE TITLE
[1.18.2] Crash with Dimensional Threading + Ice and Fire

### ISSUE THREAD

**Issue by Reshy** [embeddedt/ModernFix#121]
https://github.com/CCr4ft3r/DimensionalThreading-Reforged/issues/8

Information is here, seems to be a weird three way interaction between these mods from the looks of it.

**Comment by embeddedt** [comment]
Probably a conflict between Ice and Fire and Dimensional Threading. The latter is likely to have compatibility issues with most reasonably complex content mods as they are not designed with independently ticked dimensions in mind. I can only reasonably provide support for ModernFix issues with Dimensional Threading if they can be reproduced without other mods present, as it's a very fundamental change to how Minecraft works internally.
