### ISSUE TITLE
Random Crash

### ISSUE THREAD

**Issue by KostromDan** [embeddedt/ModernFix#122]
I created a new profile with the M-Tech 1.3.16 modpack in order to find a different bug. Created a new world, after a minute of flight, the game crashed. No matter how much I try to repeat it, nothing happens. I tried to recreate the world, but no more crash appeared.
[crash-2023-06-05_14.11.23-server.txt](https://github.com/embeddedt/ModernFix/files/11651883/crash-2023-06-05_14.11.23-server.txt)
[2023-06-05-1.log](https://github.com/embeddedt/ModernFix/files/11651885/2023-06-05-1.log)

**Comment by embeddedt** [comment]
Unfortunately, to my knowledge "Accessing LegacyRandomSource from multiple threads" crashes are not triggered by ModernFix. Even more annoyingly, they are incredibly hard to reproduce. I would check that all your mods are up to date as I believe All the Mods 8 spent some time hunting down causes of this bug and reporting them to the respective mods.
