### ISSUE TITLE
Custom item icon and texture issue with Vault Hunters 3

### ISSUE THREAD

**Issue by MageInBlack** [embeddedt/ModernFix#124]
I know it is a very niche usage issue but i've noticed it and it may be a sign of a bigger problem so i thought it'd be better to warn people that it exists.

Vault Hunters 3 have their own custom items (chromatic iron sickle as an example). By default when loaded with ModernFix, item image gets replaced with a texture square (probably because those items generate their inventory icons using textures).

Using `mixin.perf.faster_texture_loading=false`, disabling this mixin seems to fix the issue.

Using Vault Hunters 3, 3.10.1 version, currently latest. MC 1.18.2, Forge 40.2.1, ModernFix 2.7.1

If you need more information i'd gladly provide it. There is no crash log as there is no crash

**Comment by embeddedt** [comment]
Thanks. Does this still occur with the latest development build?

**Comment by MageInBlack** [comment]
No, it seems to work fine now with the dev build. Thanks a lot

**Comment by embeddedt** [comment]
Fixed in 5.0.0.
