### ISSUE TITLE
[Bug] Missing Textures for the Wizards mod when enabling Dynamic Resources [FABRIC 1.19.2/0.14.21]

### ISSUE THREAD

**Issue by pokesmells** [embeddedt/ModernFix#125]
Hi there, when enabling `mixin.perf.dynamic_resources=true` this causes Spell Animation Textures to be stripped from the atlas.

Disabling this feature causing the textures to work completely fine.

Modernfix version: modernfix-mc1.19.2-fabric-3.7.1
Wizards Version: wizards-fabric-0.9.17+1.19
OS Version: Windows 11
Fabric Loader Version: 0.14.21

https://github.com/embeddedt/ModernFix/assets/33227568/16d50fbe-edea-4f39-b0fd-6347661ea546

**Comment by embeddedt** [comment]
Please confirm it's fixed in 5.0.0.

**Comment by pokesmells** [comment]
I FORGOR TO INCLUDE A FOLDER
wizards:spell_effect

**Comment by pokesmells** [comment]
this one as well  paladins:spell_effect/divine_protection

**Comment by embeddedt** [comment]
Should be fixed in 5.0.1.
