### ISSUE TITLE
[Crash] On StartUp when having Steam N rails installed

### ISSUE THREAD

**Issue by f0kx** [embeddedt/ModernFix#129]
https://pastebin.com/see4K29x

**Comment by embeddedt** [comment]
Please check if the development build fixes this; I think it is the same issue I fixed with Wilder Wild the other day. (It's in the README.)

**Comment by f0kx** [comment]
looks like this will fix it thank you

**Comment by embeddedt** [comment]
This should be fixed in the latest release.
