### ISSUE TITLE
[1.19.2] Async Bug

### ISSUE THREAD

**Issue by MettytheCutiefly** [embeddedt/ModernFix#131]
Playing ATM8, this comes up in server log. I am using prechunk generator to generate the world.

https://pastebin.com/UrHhzkXh

Attached pastebin for issue.

**Comment by embeddedt** [comment]
Looks like a Wither Skeleton Tweaks issue, see https://github.com/Shadows-of-Fire/Wither-Skeleton-Tweaks/issues/35.
