### ISSUE TITLE
[1.20.1] ModernFix Causes Crash After ~5ish Seconds

### ISSUE THREAD

**Issue by R00tB33rMan** [embeddedt/ModernFix#132]
All information provided here: https://pastebin.com/cPxcHiU7

**Comment by embeddedt** [comment]
Hmm, is the latest Fabric API installed?

**Comment by R00tB33rMan** [comment]
The latest was installed, yes. (0.83.1 for 1.20.1). Very obscure issue, for sure. Couldn't really get much else from it/out of it

**Comment by embeddedt** [comment]
The problem is that the crash appears to be caused by Fabric API's mixin, not ModernFix, so I don't really know what I can do to fix it on my end. When running standalone this doesn't occur for me.

**Comment by R00tB33rMan** [comment]
Strange. I'll do some more testing to see what's all goin' on

**Comment by R00tB33rMan** [comment]
Essentially, it appears that Debugify and ModernFix conflict with one-another, which then initiates a crash. Not exactly sure if the two have some correlating patches; however, this is what I've identified from my findings.

**Comment by R00tB33rMan** [comment]
Issue fully invalidated. Turns out that some of Fabric's mappings were incorrectly applied when upgrading from 1.20 to 1.20.1, which resulted in recurring crashes due to instances that are and were not your fault. Had to really go out of my way for this one.

**Comment by embeddedt** [comment]
Interesting! Well, at least I know what to recommend the next time someone reports a weird crash like this on Fabric. Thanks for your efforts.
