### ISSUE TITLE
Problems when combining it with any item sorting mod

### ISSUE THREAD

**Issue by CapNapu** [embeddedt/ModernFix#134]
There is a strange bug that causes, when pairing ModernFix with any mod that helps to sort inventories to cause some items to be placed in the user's hand, practically disabling the ability to sort properly.

Demostration:

https://github.com/embeddedt/ModernFix/assets/110067479/97dc45ca-5d7e-4a7f-8e70-2d86f59a3e73

Variables to consider:

- Only affects specific items such as weapons and armor.
- ModernFix MUST be installed on both server and client (removing it from one of the 2 solves the bug).
- Bug does not appear when playing on singleplayer
- Mods tested: Inventory Profiles Next; Inventory Tweaks Renewed; & Inventory Profiles
- Minecraft Version: 1.16.5 (Forge 36.2.34)
- ModernFix Version: Latest version (5.0.2)

_The bug is present since ModernFix 1.16.1, according to my observations._

**Comment by embeddedt** [comment]
Hmm, weird one. I'm having trouble reproducing it locally (with just ModernFix and Inventory Tweaks Renewed installed, no other mods). Does it happen if `mixin.perf.nbt_memory_usage` is disabled in the config? Are you able to reproduce it with no other mods installed except these two?

**Comment by CapNapu** [comment]
- Does it happen if mixin.perf.nbt_memory_usage is disabled in the config?:
**No it doesn´t. Disabled on both sides**

- Are you able to reproduce it with no other mods installed except these two?:
**Yes. Now Minecraft even crashes sometimes**

_For now, I will keep mixin.perf.nbt_memory_usage as it is, since it technically solves the problem_

**Comment by embeddedt** [comment]
Can I have a look at the crash report?

**Comment by CapNapu** [comment]
[crash-2023-06-19_20.47.19-client.txt](https://github.com/embeddedt/ModernFix/files/11798923/crash-2023-06-19_20.47.19-client.txt)

This crash occurs when you press the sorting button several times without removing the item from your pointer.
(Only happened to me when I enabled mixin.perf.nbt_memory_usage, and the above condition is met.)

**Comment by embeddedt** [comment]
Can you try the latest 1.16 dev build from the README with `mixin.perf.nbt_memory_usage` re-enabled? I think I have probably fixed the issue.

**Comment by CapNapu** [comment]
The development version is working properly, thank you for your time.

**Comment by embeddedt** [comment]
Great, thank you for your patience. This is now fixed in 5.0.4.
