### ISSUE TITLE
Valhelsia Structures patch broken

### ISSUE THREAD

**Issue by Airisii** [embeddedt/ModernFix#135]
I'm experiencing major tps lag or something when ever i tp (dimension or by map) or move away from my base/spawn. I have no idea if this is even the cause but im seeing alot of modernfix stuff in the log and am wondering perhaps is it this? I'm currently testing an older version of the mod to see if this is the actual cause but if you dont care could you look at my log and see if anything sticks out? 
[latest.zip](https://github.com/embeddedt/ModernFix/files/11793482/latest.zip)

**Comment by Airisii** [comment]
It seems version 1.13.1 (1.16.5) works fine but the latest version causes new chunks to not load and gives "waiting for server" via the one probe mod

**Comment by embeddedt** [comment]
Thanks for the report. There is a bug in Valhelsia Structures which causes this and it appears I broke the patch for it during the refactor to support Fabric. Can you check if this is now fixed in the development build?

**Comment by Airisii** [comment]
Sure, but where can I find the development build?

**Comment by embeddedt** [comment]
The README

**Comment by Airisii** [comment]
Testing it now, might take about 12 mins to launch then about 2 to get into the world because i have over 700+ mods

**Comment by Airisii** [comment]
Seems to be working, thanks! (i crashed so it took me a bit longer tho the crash is unrelated to this mod)

**Comment by embeddedt** [comment]
Great. Fixed in 5.0.3 release.
