### ISSUE TITLE
Mod crashes on New Forge version 47.0.4

### ISSUE THREAD

**Issue by ModernGamingWorld** [embeddedt/ModernFix#136]
[crash-2023-06-19_18.37.10-fml.txt](https://github.com/embeddedt/ModernFix/files/11793954/crash-2023-06-19_18.37.10-fml.txt)

**Comment by embeddedt** [comment]
Thanks, this was also reported via Discord, I'll be releasing a new version
for Forge 1.20.1 shortly.

**Comment by embeddedt** [comment]
Fixed in 5.0.3.
