### ISSUE TITLE
Prints warning about incorrect side classloading

### ISSUE THREAD

**Issue by Aiidoneus** [embeddedt/ModernFix#137]
Hello, this is definitely a very low priority issue but thought I would bring it up since I am doing a lot of other stuff tonight with my server. It might be worth while to disable these patches if Modernfix is detected to be running on a dedicated server. Just a thought. Yes, I know it doesn't hurt anything currently so it isn't that big of a deal. =)
I am running;
Minecraft: `1.19.2`
Forge:`43.2.14`
Modernfix: `modernfix-forge-5.0.2+mc1.19.2.jar`

Error:
![image](https://i.imgur.com/bty9u5k.png)

**Comment by embeddedt** [comment]
These warnings should be gone now in 5.0.4, thanks.

**Comment by Aiidoneus** [comment]
Cool! Thanks for all you do.
