### ISSUE TITLE
1.5.0 is incompatible with Dynamic Surroundings 

### ISSUE THREAD

**Issue by GermanPlasma** [embeddedt/ModernFix#14]
ModernFix 1.4.4 and below still worked with it, but using the new ModernFix 1.5.0 results in Dynamic Surroundings throwing a java.lang.ExceptionInInitializerError:null error. Not sure if this can be solved on your end, but it did work before. Would be a shame to not be able to use both at the same time, as I found that ModernFix speeds up my loading by a ton.

Bugreport attached
[crash-2023-01-28_18.46.01-fml.txt](https://github.com/embeddedt/ModernFix/files/10528700/crash-2023-01-28_18.46.01-fml.txt)

**Comment by embeddedt** [comment]
Fixed in 1.5.1. Thanks.
