### ISSUE TITLE
Some mods causes "@Redirect Conflict" and "@Modify Constant" error in pool-thread

### ISSUE THREAD

**Issue by 9ghtX** [embeddedt/ModernFix#142]
Getting this errors in latest.log file
[latest.log](https://github.com/embeddedt/ModernFix/files/11878261/latest.log)

Interesting log lines:
930: @Redirect conflict. Skipping immersive_weathering-common.mixins.json:LevelChunkMixin ... already redirected by supplementaries.mixins.json:LevelChunkMixin
932: @ModifyConstant conflict. Skipping repurposed_structures.mixins.json:structures.StructurePoolMixin ... already redirected by yungsapi.mixins.json:IncreaseStructureWeightLimitMixin
933: @ModifyConstant conflict. Skipping integrated_api.mixins.json:structures.StructurePoolMixin ... already redirected by yungsapi.mixins.json:IncreaseStructureWeightLimitMixin

I suppose it's some adding structures and blocks patching issues in different mods. I couldn't find any settings in their .toml files to somehow fix this. Maybe you can give a clue how to fix this

**Comment by embeddedt** [comment]
These mixin warnings are normal and should appear even without ModernFix added. Unless they are causing a crash or incorrect game behavior, I don't think there is much I can/need to do from my end.
