### ISSUE TITLE
[1.20.1] Crash when ModernFix and LittleTiles are installed

### ISSUE THREAD

**Issue by lays24mc** [embeddedt/ModernFix#143]
Unfortunately my client crashes when I use ModernFix and LittleTiles in version 1.20.1. Here is the log part, since no crash log is created: https://pastebin.com/uwDjbWuw 

If I see it correctly, it is a "priority" conflict. Would it therefore be possible that you adjust this mixin part a little: https://github.com/embeddedt/ModernFix/blob/1.20/common/src/main/java/org/embeddedt/modernfix/common/mixin/perf/cache_strongholds/ServerLevelMixin.java#L42

That should, also according to LittleTiles developer, solve the problem then, so both can be used :)

**Comment by embeddedt** [comment]
Fixed in 5.1.0.
