### ISSUE TITLE
unknown bug or error texture in modernfix-fabric-5.0.4+mc1.19.4

### ISSUE THREAD

**Issue by BoraiperXD** [embeddedt/ModernFix#144]
What's the sudden cause of this bug or incompatibility? I listed it and checked every fabric mods to see if it was compatible, except the ModernFix mod, which has an issue with the textures, and I've seen six times that different blocks have glitch textures, including deepslate that I screenshotted.

Example here:
![2023-06-29_22 54 18](https://github.com/embeddedt/ModernFix/assets/80188692/9b899092-5e94-4690-a6c9-5d2404b1be37)

**Comment by BoraiperXD** [comment]
Tell me about anyone who encountered this, and is there anyway to change it? Ty

**Comment by embeddedt** [comment]
Does this occur when `mixin.perf.faster_texture_stitching` is disabled in the ModernFix config?

**Comment by BoraiperXD** [comment]
but I've tried disabling it and still have glitches. idk how

**Comment by embeddedt** [comment]
Hmm. ~~Also try disabling `mixin.perf.faster_texture_loading` at the same time.~~

EDIT: Nevermind, that doesn't exist on 1.19.4.

**Comment by embeddedt** [comment]
In this case the next step is to determine whether the issue occurs with only ModernFix installed and no other mods. If not it is some type of mod conflict/incompatibility.

**Comment by BoraiperXD** [comment]
I believe your mod has been fixed, and glitches are gone now in the latest version of MC5.1.1 that I tested and created every newworld in. Everything is seems normal thanks

**Comment by embeddedt** [comment]
Great, glad to hear it. I guess it was the same underlying issue as #145.
