### ISSUE TITLE
[1.20.1] Modern Fix 5.1.0 breaks Yellorite Ore Texture

### ISSUE THREAD

**Issue by Peach774** [embeddedt/ModernFix#145]
![image](https://github.com/embeddedt/ModernFix/assets/5171184/ee98ae5a-77ca-4fdc-9a76-40621a3b369d)
You can test this with the newest version of extreme reactors, modern fix 5.1.0, and forge .34

**Comment by embeddedt** [comment]
Thanks, should be fixed in 5.1.1.
