### ISSUE TITLE
[1.19.2 Forge] FPS optimization with the Create mod

### ISSUE THREAD

**Issue by GitJhopa** [embeddedt/ModernFix#146]
Hello! I do not know what your mod does, but I put it on my client and server "for show", but I would like to ask you if it is possible to fix the FPS or optimize it for the Create mod? I'll send you a short video, which more or less shows how it lags and falls, if there are mechanisms or blocks from the Create mod in the visibility zone.

https://youtu.be/i0cYMr1cgIM

**Comment by embeddedt** [comment]
> I do not know what your mod does, but I put it on my client and server "for show"

ModernFix does a lot of things, but two of the more notable features are better load times (generally Forge packs can load up to two times faster) and lower memory usage.

Unfortunately, rendering (particularly as done by Create) is not something I'm familiar with, and so I wouldn't be confident optimizing it at the moment. I may look into it in the future but at the moment my focus is on more general optimizations that benefit any mod.
