### ISSUE TITLE
Enhancement : Forgebackport "Prevent release of custom payload packet buffer" from 1.18 and "Re-add patch to release buffer in custom payload packet" from 1.17

### ISSUE THREAD

**Issue by quentin452** [embeddedt/ModernFix#15]
Forgebackport "Prevent freeing custom payload packet buffer" from 1.18 and "Re-add fix to free buffer in custom payload packet" from 1.17 to potentially fix major memory leak that can crash on big modpack due to lack of memory after 3-6 hours of games caused by packetbuffer.release().

issues : 

https://github.com/MinecraftForge/MinecraftForge/issues/8573
https://github.com/EnigmaticaModpacks/Enigmatica6/issues/4469

codes need to be backported : 

Prevent release of custom payload packet buffer : 
https://github.com/MinecraftForge/MinecraftForge/pull/8181
Re-add patch to release buffer in custom payload packet
https://github.com/MinecraftForge/MinecraftForge/pull/8042

**Comment by embeddedt** [comment]
Added an experimental patch for this but left it off by default until it can be tested more thoroughly.

**Comment by quentin452** [comment]
ok
