### ISSUE TITLE
[1.16] dynamic_resources --- ae2 crash

### ISSUE THREAD

**Issue by wasdspace** [embeddedt/ModernFix#151]
modernfix: https://github.com/embeddedt/ModernFix/actions/runs/5481971436
ae2: https://legacy.curseforge.com/minecraft/mc-mods/applied-energistics-2/files/3608871

easy to reproduce.

[debug.log](https://github.com/embeddedt/ModernFix/files/11974661/debug.log)
[latest.log](https://github.com/embeddedt/ModernFix/files/11974662/latest.log)

**Comment by embeddedt** [comment]
Thanks for the report, fixed in 5.2.0.
