### ISSUE TITLE
Textural Incompatibility -  Dynamic Resources and Industrial Agriculture/Mystical Customization

### ISSUE THREAD

**Issue by PhweeDev** [embeddedt/ModernFix#154]
Hello,

on 1.18.2, using ModernFix' latest version, when trying to use both of the two Mystical Agriculture mods with the following argument in the modernfix-mixin properties file:

mixin.perf.dynamic_resources=true

The textures, block models, and other items like essence are all broken and are the default purple/black or missing texture icon.  Note this only affects the stuff added by those two mods. Not anything in Mystical Agriculture itself. 

Can you look into this?

**Comment by PhweeDev** [comment]
Not sure if logs help, but here:

https://paste.gg/p/anonymous/aa2f22a9de6146e1ba99bf8a653794a3 (With the config)

https://paste.gg/p/anonymous/104cac50d0af478ea7a646e5a47eb294 (Without)

**Comment by embeddedt** [comment]
What are the "two Mystical Agriculture mods"? It's not clear from the logs as there are many other mods present.

**Comment by PhweeDev** [comment]
Mystical Customization and all of the Industrial Agriculture series that are on 1.18. You won't find it as easily with Customization, but just use Industrial Agriculture. You'll see what I mean.

https://www.curseforge.com/minecraft/mc-mods/mystical-customization

https://www.curseforge.com/minecraft/mc-mods/industrial-agriculture (other addons also exist on their profile, but I don't think you need them all to see the issue since it's the same issue in the base Industrial Agriculture as with the other addons for IA)

**Comment by embeddedt** [comment]
Fixed in 5.2.1.
