### ISSUE TITLE
[1.18.2] Dyanmic Resources Causes Changed:MC Latex Block Overlay to Not Render

### ISSUE THREAD

**Issue by ghost** [embeddedt/ModernFix#155]
This damn latex mod again? Oh well...
Forge 1.18.2, enable Dynamic Resources along side having Changed:MC installed and either apply latex to a block or locate a biome, observe. 
![image](https://github.com/embeddedt/ModernFix/assets/100542617/0c1fecce-2cdb-45ea-9113-8dc87d2e637e)

**Comment by embeddedt** [comment]
This unfortunately doesn't look viable to fix; Changed:MC uses a very invasive mixin into the model system instead of relying on the Forge-provided solutions for custom models and model replacement.

**Comment by ghost** [comment]
Alright, I'll throw an issue at the developer to see if they can perhaps do something about it.

**Comment by ghost** [comment]
Issue has been assigned as a bug and set for fixing in v0.12, I'll update here once issue is fixed.

**Comment by LtxProgrammer** [comment]
> This unfortunately doesn't look viable to fix; Changed:MC uses a very invasive mixin into the model system instead of relying on the Forge-provided solutions for custom models and model replacement.

@embeddedt You mention a forge solution for model replacement, though I can't figure what that is, or if it would even work with generated textures based of the original block.

Would you mind as to point me in the right direction?

**Comment by embeddedt** [comment]
You need to look into the Forge `ModelBakeEvent`; it allows you to inject custom models into the model registry by `ModelResourceLocation`. In your case it should be possible to get one model and use it as a reference to construct and put the other models into the registry.

**Comment by LtxProgrammer** [comment]
Thank you very much.

**Comment by ghost** [comment]
Fixed on mod side by LTX @embeddedt
