### ISSUE TITLE
Conflict with config modification of mcdw

### ISSUE THREAD

**Issue by Rad586** [embeddedt/ModernFix#156]
**Game version:** 1.18.2 fabric
**Mod version:** 5.2.2
**Environment:** 
modernfix-fabric-5.2.2+mc1.18.2
mcdw-5.0.4-1.18
cloth-config-6.2.57
fabric-api-0.67.1+1.18.2
**Description:** 
With any item in certain category(e.g. shields, crossbows, longbows) disaled in mcdw config alongside with modernfix 5.2.2, the game crashes. This **only** happens using 5.2.2 version of modernfix(default config).
**Crash-report:** 
[crash-2023-07-10_15.10.10-client.txt](https://github.com/embeddedt/ModernFix/files/11998936/crash-2023-07-10_15.10.10-client.txt)
**Config used:** 
[mcdw_items_registry.json5.txt](https://github.com/embeddedt/ModernFix/files/11998984/mcdw_items_registry.json5.txt)

**Comment by embeddedt** [comment]
Fixed in 5.2.3.
