### ISSUE TITLE
[1.18] Better Bundles crash conflict w/ ModernFix 5.2.2

### ISSUE THREAD

**Issue by PhweeDev** [embeddedt/ModernFix#157]
Hello again,

In the recent update, the mod Better Bundles refused to load unless ModernFix was removed.  Here's the report/log as it might help you.

Report: https://paste.gg/p/anonymous/e5835d843bcb4fb8b405b7edae805ead

Log:  https://paste.gg/p/anonymous/12398e12e9cb490ea827754ebaa5b9ba

Note that this happens even if there is or is not anything in the mixins config for ModernFix. This does not occur on 5.2.1, only on 5.2.2.

**Comment by embeddedt** [comment]
Fixed in 5.2.3.
