### ISSUE TITLE
1.6.0 Beta 3 crash when exiting the end.

### ISSUE THREAD

**Issue by GermanPlasma** [embeddedt/ModernFix#16]
I am not sure if this is of any help, but after trying the newest beta, I experience a repeatable crash when leaving the end (albeit only tested with the /execute in command)

I tried switching off the "rebuild_blockstate_cache_async" option but that does not change anything.
When I loaded the same save (it was crashing on entering the world) with ModernFix 1.6.0 Beta 2, the game worked again.

I do run a heavily modded game, but here is the log. You're doing godly work btw, I literally cannot stand booting up Minecraft without your mod anymore lol.

[crash-2023-02-11_17.24.23-client.txt](https://github.com/embeddedt/ModernFix/files/10714941/crash-2023-02-11_17.24.23-client.txt)

**Comment by embeddedt** [comment]
Do you happen to have the full log when the crash occurs, just in case there's useful information?

**Comment by GermanPlasma** [comment]
I'm happy to help as much as possible!

Here is the full log
[latest.log](https://github.com/embeddedt/ModernFix/files/10715049/latest.log)

**Comment by embeddedt** [comment]
This is fixed now. The issue was that Better Foliage requires its grass models to be set up before joining the world, which is a perfectly reasonable assumption in a regular game, but not in my egregiously optimized one. :laughing:
