### ISSUE TITLE
(1.19.2) 5.2.4 crashes with Lithium

### ISSUE THREAD

**Issue by Fuyukai** [embeddedt/ModernFix#161]
Sorry to ruin your new release. 

Crash log: https://bpa.st/O52XO

5.2.3 works fine.

**Comment by embeddedt** [comment]
The funny part is that I checked Lithium's mixins to see if they would conflict at the time, and didn't notice the item one... will be fixed in a few minutes.

**Comment by NoThrottle** [comment]
Also have this issue with 1.19.4. I was surprised I didn't even know the mod updated and it suddenly just didn't work.
https://mclo.gs/sekqL4i

Edit: Yay its fixed with 5.2.5

**Comment by embeddedt** [comment]
Fixed in 5.2.5, yes.
