### ISSUE TITLE
Crashes with Better Loading Screen

### ISSUE THREAD

**Issue by Mystrik** [embeddedt/ModernFix#164]
Mod version I've mainly tried is is 5.2.5 for forge,

error says " The game crashed whilst initializing game
Error: org.spongepowered.asm.mixin.transformer.throwables.MixinTransformerError: An unexpected critical error was encountered "

I've tried removing lightspeed and other mods I saw that had compatibility issues in the past, but the only thing that let me launch was removing ModernFix (i also tried launching with all versions of the mod available for 1.16.5, no luck). I couldn't find out much from the crash reports, but here's the most recent one anyways.

[crash-2023-07-18_14.31.02-client.txt](https://github.com/embeddedt/ModernFix/files/12081615/crash-2023-07-18_14.31.02-client.txt)

Also here's a full modlist and an exported curseforge pack of my gigantic pack I'm using (sorry lol i like very heavy modded)

[mystrik megapack-bugreportver.zip](https://github.com/embeddedt/ModernFix/files/12081672/mystrik.megapack-bugreportver.zip)

I don't check here too often so if you want any additional info you can contact me on discord, where my name is mystrik

Thanks!

(Crashes milliseconds into reaching loading step 2/9)

![image](https://github.com/embeddedt/ModernFix/assets/38515916/6f2123cc-7523-42ad-8055-623aa7354650)

**Comment by embeddedt** [comment]
ModernFix and Better Loading Screen are unfortunately not compatible. The latter uses a lot of mixins to collect the necessary data to display, which conflict with ModernFix optimizations, and is known to cause crashes on some GPUs.

**Comment by Mystrik** [comment]
Damn that was a fast response lol, thanks for the info, I'll see if I can use an alternative then! 

Thanks!
