### ISSUE TITLE
Dynamic resource breaks MCC Island's custom resourcepack

### ISSUE THREAD

**Issue by TheBossMagnus** [embeddedt/ModernFix#165]
Logs: https://mclo.gs/VAaJReZ
![image](https://github.com/embeddedt/ModernFix/assets/92474350/505c91c7-902f-449e-ace6-4567fe9d6641)
If i disable dynamic resources everything works fine.
ENV: modernfix-fabric-5.2.5 mc1.20.1 on fabric, playing on `play.mccisland.net`

**Comment by embeddedt** [comment]
Downgrading Fabric API to 0.84.0 should resolve this for now, it should be fixed in the next ModernFix release.

**Comment by embeddedt** [comment]
Using 5.3.0 and the latest Fabric API should work fine.
