### ISSUE TITLE
Crash try start minecraft (Fabric)

### ISSUE THREAD

**Issue by Anewri32** [embeddedt/ModernFix#166]
Minecraft: 1.20.1
Fabric: 0.14.21

Minecraft loads normally, but when the menu is displayed, it lasts 1 second open and closes suddenly.
By removing the mod "Modernfix" the problem is solved, the crash could be due to another mod, but I can't find it.

Full Log: https://mclo.gs/y5UUvN1

**Comment by embeddedt** [comment]
This looks like the exact same issue as https://github.com/embeddedt/ModernFix/issues/132, which was caused by some sort of corruption in the launcher, not ModernFix. Try making a fresh 1.20.1 instance and copy the mods/configs folder over.
