### ISSUE TITLE
[Forge 5.3.0-1.19.2] Failed to Load with Immersive Weathering

### ISSUE THREAD

**Issue by BookerCatch** [embeddedt/ModernFix#168]
Please see latest log below. Game fails to load to menu screen with Modern Fix and Immersive Weathering loaded. Reverting to 5.2.5 fixes the issue. This is likely an issue with dynamic resources.

[latest.log](https://github.com/embeddedt/ModernFix/files/12099847/latest.log)

**Comment by embeddedt** [comment]
Thanks, this will be fixed in the next release. For now you can either use the development build linked in the README, or set `mixin.perf.deduplicate_wall_shapes=false` in the config file.

**Comment by BookerCatch** [comment]
Thanks!
