### ISSUE TITLE
[1.19.4/1.20] Conflict with old Fabric API (<0.86.0)

### ISSUE THREAD

**Issue by SAJewers** [embeddedt/ModernFix#169]
Using ModernFix 5.3.1+mc1.20.1 and EBE 0.9+1.20 (latest versions of both), Chests, Ender Chests, and Shulker Boxes are rendered with invalid textures
![2023-07-19_22 38 03](https://github.com/embeddedt/ModernFix/assets/60888972/6b39f359-4b28-4115-91ff-e9bd52666928)

**Comment by embeddedt** [comment]
Does this occur with updated Fabric API (0.86.0 or newer)?

**Comment by SAJewers** [comment]
Sorry using Quilt, not Fabric. Quilt Loader 0.19.2 and QFAPI 7.0.6+0.85.0-1.20.1

I'm guessing then QFAPI needs to update to update to support a newer Frabic API then.

**Comment by embeddedt** [comment]
Yep, which won't happen anytime soon as the QFAPI maintainer is currently on break, and updates are not automated. So I will have to fix this on my end.

**Comment by embeddedt** [comment]
This should be addressed by using the development builds in the README. I will hold off on doing a third release for the day since this issue can be solved for most users by updating Fabric API.

**Comment by embeddedt** [comment]
Should be fixed in 5.3.2.
