### ISSUE TITLE
Spam log : modernfix incompatible with slimeknights.mantle when i go to a certain page of JEI causing freeze.

### ISSUE THREAD

**Issue by quentin452** [embeddedt/ModernFix#17]
[2023-02-13-1.log](https://github.com/embeddedt/ModernFix/files/10718996/2023-02-13-1.log)

**Comment by GermanPlasma** [comment]
slimeknights is the creator of Tinkers, I too have an issues with that one. In my case though, the game simply crashes when interacting with a tinkers crafting bench.

**Comment by embeddedt** [comment]
Same underlying issue as #18 so I will close this one.
