### ISSUE TITLE
Randomly Crashes whenever i do anything with resource packs

### ISSUE THREAD

**Issue by RichPrune** [embeddedt/ModernFix#171]
This entire bug only happens when i enable dynamic resources in the config for performance. Sometimes it doesn't crash when i do one at a time, but most of the time it does. Its a shame considering your mod makes my game run practically.  Also, connected textures don't work at all with this option enabled, but im sure youre aware of that. 1.19.2 forge

[crash-2023-07-21_02.06.31-client.txt](https://github.com/embeddedt/ModernFix/files/12116890/crash-2023-07-21_02.06.31-client.txt)
[crash-2023-07-21_02.07.46-client.txt](https://github.com/embeddedt/ModernFix/files/12116891/crash-2023-07-21_02.07.46-client.txt)

**Comment by embeddedt** [comment]
Thanks, this should be fixed as of 5.3.2.

**Comment by embeddedt** [comment]
And yes, connected textures and dynamic resources do not work together on anything before 1.19.4 at the moment: https://github.com/embeddedt/ModernFix/issues/112

**Comment by RichPrune** [comment]
> Thanks, this should be fixed as of 5.3.2.

omg tysm

**Comment by RichPrune** [comment]
> And yes, connected textures and dynamic resources do not work together on anything before 1.19.4 at the moment: #112

also how far r u into working on it lol

**Comment by embeddedt** [comment]
As mentioned in the other issue it's more ideal for Continuity to be redesigned for better support from its end, however if it never ends up updating I can also patch it myself.

**Comment by RichPrune** [comment]
could you please go about patching it? i get its on their end but id really appreciate, i understand if u dont wanna tho

**Comment by embeddedt** [comment]
Cross-mod patches are not ideal for long-term compatibility so its better for the issue to be fixed on the other end if possible. If Continuity doesn't get another update for these versions I will implement the patch since at that point compatibility is a non-issue.
