### ISSUE TITLE
Client crash on startup with ModernFix and Thermal Integration (1.18.2)

### ISSUE THREAD

**Issue by PigTurtleDev** [embeddedt/ModernFix#173]
1.18.2;   Forge 40.2.9;   ModernFix 5.3.2

176 Mods total, didn't try with less after someone pointed out to me that the crash could have to do with having more than 128 mods loaded

The crash is semi consistent, happened about half the time on ModernFix 5.3.1 and now still occurs (about one in ten times) with ModernFix 5.3.2.

Removing either ThermalIntegration or ModernFix fixes the issue.
 
[crash-2023-07-22_13.50.05-client.txt](https://github.com/embeddedt/ModernFix/files/12136322/crash-2023-07-22_13.50.05-client.txt)

**Comment by embeddedt** [comment]
It looks like a Thermal Integration bug, I'll see if I can patch it from my
side since 1.18 probably isn't supported anymore.

**Comment by embeddedt** [comment]
This crash shouldn't occur anymore when using the dev build linked in the README, or in the next release. CoFH may fix it on their end but the issue also affects 1.16 so I had to patch it anyways.

**Comment by brisingraerowing** [comment]
This 'fix' is crashing on load on the 5.4.0-1.19.2 version of ModernFix with CoFH Core 10.2.1.40. 

ETA: [Crash Log](https://gist.github.com/brisingraerowing/3ecc7e2c5a1284a83e36be24072a14a6)

**Comment by embeddedt** [comment]
Fixed in 5.4.1.
