### ISSUE TITLE
NPE on server shutdown

### ISSUE THREAD

**Issue by andriihorpenko** [embeddedt/ModernFix#174]
I suppose once of the latest builds introduced this exception. This happens every time on server shutdown after all dimensions get saved. IIRC, there were some NightConfig-related commits recently in ModernFix, hope this will help.
_P.S. Providing a screenshot as this exception is not logged neither in latest.log, nor in debug.log_

<img width="1383" alt="255329285-bf6f2e2e-c8c8-44c0-9adc-bb76f2983820" src="https://github.com/embeddedt/ModernFix/assets/13716167/0309e5c8-25f3-4c0a-bad5-443ac1372215">

**Comment by embeddedt** [comment]
Thanks, I've fixed this for the next release.

**Comment by embeddedt** [comment]
Should be fixed as of 5.4.1.
