### ISSUE TITLE
I don't know who to contact, maybe you can fix it?

### ISSUE THREAD

**Issue by GitJhopa** [embeddedt/ModernFix#176]
https://github.com/team-abnormals/savage-and-ravage/issues/153

Your ModernFix mod has already fixed running the Environmental mod from their Abnormals series of mods.
Campaign they have there all the mixins are confused and broken. There is generally a lot of desynchronization, watch the video in that topic.

**Comment by P3rf3ctXZer0** [comment]
Which version?
Which Mod Version?
Other mods present?

Everything I personally used by team abnormals was badly coded at least on 1.19.2

**Comment by GitJhopa** [comment]
1.19.2 Forge
Latest mods version in CurseForge (endergetic mod build in github 1.19.2)
Other mods present? - no only Abnormals test

**Comment by P3rf3ctXZer0** [comment]
Can I have a log file?

**Comment by GitJhopa** [comment]
> Can I have a log file?

no logs and error.

**Comment by GitJhopa** [comment]
> Can I have a log file?

I give you a link to the video, watch everything there

https://github.com/team-abnormals/savage-and-ravage/issues/153

**Comment by embeddedt** [comment]
It's not clear from the video exactly what the issue is, and the chat is not in English so I can't get any information from it either. I think I will pass on fixing this, for now.
