### ISSUE TITLE
Something happens in the cleaning of the RAM, and minecraft starts to freeze a lot.

### ISSUE THREAD

**Issue by GitJhopa** [embeddedt/ModernFix#180]
I use arguments to clear RAM and your mod seems to do it too and it cleans up 5 times faster for me and it feels like minecraft starts to lag, freeze.

My args: https://pastebin.com/GGithAK2

**Comment by embeddedt** [comment]
I'm skeptical this is a ModernFix bug given that no one has reported similar issues recently. Tuning JVM arguments should only be done if you know what you're doing with them, otherwise it will cause strange issues. Does this occur with default flags (e.g. just `-XX:+UseG1GC`)?

**Comment by GitJhopa** [comment]
> I'm skeptical this is a ModernFix bug given that no one has reported similar issues recently. Tuning JVM arguments should only be done if you know what you're doing with them, otherwise it will cause strange issues. Does this occur with default flags (e.g. just `-XX:+UseG1GC`)?

no

**Comment by GitJhopa** [comment]
> I'm skeptical this is a ModernFix bug given that no one has reported similar issues recently. Tuning JVM arguments should only be done if you know what you're doing with them, otherwise it will cause strange issues. Does this occur with default flags (e.g. just `-XX:+UseG1GC`)?

It's just that when I open F3 and look at RAM, there the numbers change in 0.1 ms i.e. very fast cleaning.

**Comment by embeddedt** [comment]
In that case your heap size is probably just too small, or you have somehow tuned the JVM to believe it needs to collect garbage continuously to maintain performance.

**Comment by GitJhopa** [comment]
https://youtu.be/HuozT-dVmMA see Video

**Comment by embeddedt** [comment]
Yeah, after looking at the video I am pretty sure this has nothing to do with ModernFix and is just related to those JVM arguments you used - you've probably caused it to choose a very small young generation size forcing frequent garbage collection. I would just stick with defaults unless they are not working.

**Comment by GitJhopa** [comment]
where can i change this size?

**Comment by embeddedt** [comment]
Unfortunately I do not remember off the top of my head, it may require tweaking several options and the names depend on which Java version/garbage collector is being used.
