### ISSUE TITLE
[Feature Request] Make connections to servers, exit from servers - the transition between dimensions is instant like in Fabric.

### ISSUE THREAD

**Issue by GitJhopa** [embeddedt/ModernFix#181]
Make connections to servers, exit from servers - the transition between dimensions is instant like in Fabric.

on Forge the transition between worlds is always long, on Fabric it is instant. I would like you to be able to implement the speed of Fabric for Forge.

**Comment by embeddedt** [comment]
Is there a publicly available modpack that this occurs in? I've already fixed a number of bottlenecks in Forge that slowed this down, the performance should be similar to Fabric already. It's more likely to be a specific mod slowing it down. It's only fair to compare Fabric and Forge if you are using the exact same mods on both.

**Comment by GitJhopa** [comment]
https://drive.google.com/file/d/1XYMKe2iokZul-kKOXKf6Obp7XxJLO3_N/view?usp=sharing

**Comment by GitJhopa** [comment]
Connecting to the server takes a long time, the transition between worlds is the same.

**Comment by embeddedt** [comment]
Can you send the client log file (latest.log)?

**Comment by GitJhopa** [comment]
[debug.log](https://github.com/embeddedt/ModernFix/files/12147412/debug.log)
[latest.log](https://github.com/embeddedt/ModernFix/files/12147414/latest.log)

**Comment by embeddedt** [comment]
According to ModernFix it takes only 3-6 seconds to join the server, that seems very fast already. I'm not seeing anything to optimize here.

**Comment by GitJhopa** [comment]
On Fabric about 1-2 seconds

**Comment by embeddedt** [comment]
That difference would be highly dependent on mod set, and there is also overhead in Forge to handle config syncing and other features which Fabric doesn't have.
