### ISSUE TITLE
1.19.2 Crashes On Startup

### ISSUE THREAD

**Issue by toErIpNid** [embeddedt/ModernFix#183]
Log: https://hastebin.skyra.pw/ovokonevur.pgsql

Log has other relevant info included.

**Comment by embeddedt** [comment]
Please provide the `latest.log` file as well, not just the crash report.

**Comment by toErIpNid** [comment]
False alarm, it was a Farmer's Delight addon. Will report there as well.

**Comment by toErIpNid** [comment]
Log: https://hastebin.skyra.pw/ubobudurop.prolog

**Comment by embeddedt** [comment]
The log has disappeared now but judging by the stacktrace I saw on mobile when I looked at it the other day, it should happen without ModernFix as well. For anyone who finds this via Google I believe the faulty addon was ~~Ocean's Delight~~ see below.

**Comment by toErIpNid** [comment]
It was specifically the addon "Such Delight" which caused the bug.
