### ISSUE TITLE
The world does not load when entering the server or teleporting

### ISSUE THREAD

**Issue by GitJhopa** [embeddedt/ModernFix#185]
For many players, when entering the server or teleporting, the map does not constantly load (1 rare bug), they use it as x-ray, I attach the logs.
[latest (15).log](https://github.com/embeddedt/ModernFix/files/12167977/latest.15.log)

![image](https://github.com/embeddedt/ModernFix/assets/86250668/71f70ef7-5cee-4846-ba6f-d1da42a9461d)

**Comment by GitJhopa** [comment]
I changed Java, I changed the arguments - it did not help, the error remained the same.

**Comment by GitJhopa** [comment]
mods
![Screenshot_2](https://github.com/embeddedt/ModernFix/assets/86250668/aa0f2e79-932d-4c81-9507-f6f439e32d86)
![Screenshot_1](https://github.com/embeddedt/ModernFix/assets/86250668/03115eb6-f42b-4179-b523-5e150f91222c)

**Comment by GitJhopa** [comment]
This problem appeared after installing ModernFix , can disable some mixin on the client side?

**Comment by embeddedt** [comment]
Try disabling `mixin.bugfix.paper_chunk_patches` on the server side.

**Comment by GitJhopa** [comment]
Are you thinking server side? If the player presses F3+A then everything will be fixed in client

**Comment by embeddedt** [comment]
Oh, in that case it's not the issue I'm thinking of. To be honest I can't really think of a mixin in ModernFix that would cause this, I'd suggest trying without Rubidium, etc. first.

**Comment by GitJhopa** [comment]
> Oh, in that case it's not the issue I'm thinking of. To be honest I can't really think of a mixin in ModernFix that would cause this, I'd suggest trying without Rubidium, etc. first.

never had this problem before with Rubidium

**Comment by GitJhopa** [comment]
But I guess what's the problem

**Comment by embeddedt** [comment]
Oh, another idea is try without Canary.

> never had this problem before with Rubidium

I've had this issue happen to me a couple of times before even without ModernFix but sadly never narrowed down exactly what caused it.

**Comment by GitJhopa** [comment]
![image](https://github.com/embeddedt/ModernFix/assets/86250668/7e1ac004-70b7-4972-9413-3015f4efff4e)

**Comment by embeddedt** [comment]
Unless you can narrow it down to a specific mixin option in ModernFix I don't really know if I can do anything to help with it.

**Comment by maxmistral** [comment]
Hey ! Actualy have the same bug.
I deactivated ModernFix but the problem persists, I don't think it's from this mod.

**Comment by GitJhopa** [comment]
> Hey ! Actualy have the same bug.
> I deactivated ModernFix but the problem persists, I don't think it's from this mod.

hmmm

**Comment by GitJhopa** [comment]
> Hey ! Actualy have the same bug. I deactivated ModernFix but the problem persists, I don't think it's from this mod.

canary mod problem??

**Comment by maxmistral** [comment]
> > Hey ! Actualy have the same bug. I deactivated ModernFix but the problem persists, I don't think it's from this mod.
> 
> canary mod problem??

After some research and tests, the problem comes from rubidium. What I don't understand is that even with a version including the patch, the problem persists...
The problem remains quite random, some players on my server encounter this bug more frequently than others. Also, just accessing the graphics options of rubidium on my side allows me to load the transparent blocks
https://github.com/Asek3/Rubidium/issues/468
https://github.com/The-Aether-Team/The-Aether/issues/1293
https://github.com/Asek3/Rubidium/issues/488

**Comment by embeddedt** [comment]
I'll close this since I don't think it's a ModernFix issue but feel free to continue collecting data here.
