### ISSUE TITLE
Show if an option is enabled or disabled by default in modernfix-mixins.properties

### ISSUE THREAD

**Issue by MenacingPerson** [embeddedt/ModernFix#186]
It would be really helpful.
Something like:

```
#  mixin.bugfix.concurrency=true
```

Or:

```
#  mixin.bugfix.concurrency # Default: true
```

Note in the second one there is a # so that when you uncomment the beginning of the line, it doesn't uncomment that text

The issue with these approaches is that if a modernfix update changes the default, it would be impossible to know. In this case, modernfix should update that text automatically to whatever is correct.

**Comment by embeddedt** [comment]
I've added something along these lines in 5.4.0.

**Comment by MenacingPerson** [comment]
Thank you!
