### ISSUE TITLE
[1.19.2] Incompatible with CoFH core

### ISSUE THREAD

**Issue by StormDragon-64** [embeddedt/ModernFix#188]
As of the 5.4.0 update, the mod is no longer compatible with the CoFH core flag manager, and a crash happens at startup. The game runs fine on 5.3.2 and below. In the changelog for 5.4.0, it mentions fixing an issue with CoFH's flag manager, but at least on 1.19.2, it caused a bigger issue than it solved. 

Here is the [crash report](https://github.com/embeddedt/ModernFix/files/12177701/crash-2023-07-26_15.13.41-client.txt) and the [latest.log](https://github.com/embeddedt/ModernFix/files/12177710/latest.log).

**Comment by embeddedt** [comment]
Fixed in 5.4.1, sorry about that.
