### ISSUE TITLE
Incompatibility with mod Rechiseled with complements. 1.16.5

### ISSUE THREAD

**Issue by Billetiado10** [embeddedt/ModernFix#189]
Minecraft, Version 1.16.5-forge-36.2.39
Mod version: modernfix-forge-5.4.0+mc1.16.5

Rechiseled, Version rechiseled-1.1.2-forge-mc1.16.jar
The textures do not appear correctly, I tried disabling CTM optimizers and not interfering with Fusion mod, but the problem persists, UPDATE everything to the latest version.

Update the mods
fusion-1.0.3-forge-mc1.16.jar
supermartijn642configlib-1.1.7-forge-mc1.16.jar
supermartijn642corelib-1.1.12-forge-mc1.16.jar
![2023-07-24_22 09 43](https://github.com/embeddedt/ModernFix/assets/76263374/66a072ea-db61-4692-959a-a173bd840169)
![2023-07-24_22 09 51](https://github.com/embeddedt/ModernFix/assets/76263374/86bed486-d195-4500-b587-1938002a0e4d)
![2023-07-26_14 11 21](https://github.com/embeddedt/ModernFix/assets/76263374/473b9032-ff98-4e0b-a1db-5acb099101ad)
![2023-07-26_14 11 30](https://github.com/embeddedt/ModernFix/assets/76263374/0f474a04-d47a-4ff4-8680-fe26c9672211)
![2023-07-26_14 11 33](https://github.com/embeddedt/ModernFix/assets/76263374/8b48af90-9657-466e-9865-c9084a241cab)

**Comment by embeddedt** [comment]
Seems that a fix will be made on Fusion's end: https://github.com/SuperMartijn642/Rechiseled/issues/47
