### ISSUE TITLE
Crash on startup when modernfix + applied energistics is istalled

### ISSUE THREAD

**Issue by quentin452** [embeddedt/ModernFix#19]
crash report : 

[crash-2023-02-14_01.47.18-client.txt](https://github.com/embeddedt/ModernFix/files/10727536/crash-2023-02-14_01.47.18-client.txt)

mods lists : 

* modernfix-mc1.16.5-1.6.0-beta3 [13 february](https://github.com/embeddedt/ModernFix/actions/runs/4167278116)
* appliedenergistics2-8.4.7

**Comment by embeddedt** [comment]
Fixed in next commit.
