### ISSUE TITLE
PreLaunch crash

### ISSUE THREAD

**Issue by TheLostInPlace** [embeddedt/ModernFix#191]
Using the modpack Statech Industry (latest version 1.1.2 I believe), when updating ModernFix from version 5.3.2 to 5.4.1, the following error is observed: https://mclo.gs/moYwK7g

Downgrading back to 5.3.2 fixes any issues. No additional mixins have been enabled/disabled (deleted the properties file to make sure, the original file was not altered by the modpack author either).

**Comment by embeddedt** [comment]
You are using Minecraft 1.19.2 with a version of ModernFix compiled for 1.19.4. Switching to the 1.19.2 version should solve your issue.

**Comment by TheLostInPlace** [comment]
That was quite the embarrassing mistake, thanks for the quick reply!
