### ISSUE TITLE
1.20.1 ConnectScreen Crash

### ISSUE THREAD

**Issue by potav** [embeddedt/ModernFix#194]
ModernFix 1.20.1 crashes after launch. 
It seems to be related with `ClientConnection`, `client.gui.screen.ConnectScreen` and `ConnectScreenAccessor` from fabric networking api.

Crash Log:
https://pastebin.com/W2HxXN1z

**Comment by embeddedt** [comment]
https://github.com/embeddedt/ModernFix/issues/166#issuecomment-1642236853

**Comment by potav** [comment]
Launching normally after deleting .fabric folder and fabric configs. Thank you
