### ISSUE TITLE
`OpenGL 1286` issue with ModernFix

### ISSUE THREAD

**Issue by Scarlaid** [embeddedt/ModernFix#195]
I can't tell what's causing this as the only mod that giving this error is ModernFix, without it the game runs fine 
Tried running the game with ModernFix twice, the same without, found out that
- First boot ModernFIx seems to be running fine
- Second boot is when the OpenGL 1286 kicks in
- The other two without ModernFix run absolutely fine without any OpenGL-related

My driver is also on latest, NVIDIA 536.67, playing on Minecraft 1.20.1 - Fabric Loader
Here are the list of logs/video might be useful
- Video: https://streamable.com/0lx7s5
- Log when the game running with ModernFIx present
> https://mclo.gs/UKgG5H6
> https://mclo.gs/Ryxqi8z
- Log without ModernFix
> https://mclo.gs/ZPSBYID
> https://mclo.gs/Q6NfkCp
- My mods: 

My configuration for ModernFix:
![image](https://github.com/embeddedt/ModernFix/assets/90851437/58f12ed3-8e95-4ac2-8656-e2afa73f578c)

Extra info: The same settings running on 1.19.4 was completely fine with no OpenGL-related

**Comment by embeddedt** [comment]
ModernFix shouldn't be affecting any OpenGL state so it seems more likely that this is either an NVIDIA driver issue (they are known for being incredibly buggy) or a bug in another rendering mod. Does it occur if you use the default configuration options, or if you remove Early Loading Screen?

**Comment by Scarlaid** [comment]
Oh wow thanks 👍
You mentioned ELS so I go ahead and disabled it, and the game ran absolutely fine with ModernFix, both the default configuration and the one I'm using.

**Comment by embeddedt** [comment]
It's probably a bug in ELS then, although I'm not sure why ModernFix is needed to trigger it.

**Comment by embeddedt** [comment]
Closing since I don't think there is anything I can do to correct this on my end.
