### ISSUE TITLE
Problem with modernfix-forge-5.5.0+mc1.19.2.jar

### ISSUE THREAD

**Issue by Soldier874** [embeddedt/ModernFix#196]
Hello, when I try the last update on my modpack I have this, with the previous version (5.4.1) 0 problem 

With 5.5.0+

[crash-2023-08-03_18.57.34-client.txt](https://github.com/embeddedt/ModernFix/files/12253233/crash-2023-08-03_18.57.34-client.txt)

[latest.log](https://github.com/embeddedt/ModernFix/files/12253234/latest.log)

With 5.4.1

[latest.log](https://github.com/embeddedt/ModernFix/files/12253265/latest.log)

**Comment by embeddedt** [comment]
Fixed in 5.5.1, release will be available in ~10 minutes.

**Comment by embeddedt** [comment]
5.5.1 has been released.
