### ISSUE TITLE
Scarves throws an error with the latest build of this mod on 1.19.2

### ISSUE THREAD

**Issue by Sunconure11** [embeddedt/ModernFix#197]
https://github.com/falkreon/Scarves/issues/7

**Comment by Sunconure11** [comment]
https://pastebin.com/kKAr3bg9

**Comment by embeddedt** [comment]
Please update to 5.5.1.

**Comment by Sunconure11** [comment]
https://pastebin.com/TyJD44En

Still present. What the hell.

**Comment by Sunconure11** [comment]
Wait, I see the issue here

**Comment by embeddedt** [comment]
You are still using 5.5.0 in that log.

**Comment by Sunconure11** [comment]
It turned out to be something unrelated. I have updated to 5.5.1.
