### ISSUE TITLE
[1.19.2] [Quilt] Corrupt Textures.

### ISSUE THREAD

**Issue by KateReller** [embeddedt/ModernFix#198]
When `mixin.perf.faster_texture_stitching` is true, textures like melon stems, copper, and dandelions will be corrupt. It's unknown which mod is making ModernFix do this,
![2023-08-03_17 25 57](https://github.com/embeddedt/ModernFix/assets/77589809/699648d6-ce97-4346-baaf-39c5cf5c9029)

Log: https://mclo.gs/GrFb2Qa

**Comment by embeddedt** [comment]
Try installing Iris, even if you do not use shaders. There is a known bug in Sodium on older versions that causes this issue which Iris includes a workaround for.
