### ISSUE TITLE
[1.19.2] Crash with Diagonal Fences using Dynamic Resources

### ISSUE THREAD

**Issue by paradoxuum** [embeddedt/ModernFix#199]
With the latest version of Diagonal Fences for 1.19.2 installed, the game will crash on startup with Dynamic Resources enabled.

The method signature for `MultipartAppender#appendDiagonalSelectors` was changed, so a crash occurs from `MultipartAppenderMixin` on startup.

It looks like the changes were made in this commit:
https://github.com/Fuzss/diagonalfences/commit/0c7c8bb28d371beeffe9b0a5ef3433dbff74bf5e

Crash log: https://mclo.gs/NUEM5Ji

**Comment by embeddedt** [comment]
https://github.com/Fuzss/diagonalfences/issues/47

Won't be fixed on my end until this code is refactored into a shared library, at the very least, as Diagonal Windows now also exists and has a similar issue. I am hoping to get this fixed on Diagonal Fences' end instead.

**Comment by mllightitup** [comment]
Would it be better to default to mixin.perf.dynamic_resources.diagonalfences=false until the bug is fixed?

> [Fuzss/diagonalfences#47](https://github.com/Fuzss/diagonalfences/issues/47)
> 
> Won't be fixed on my end until this code is refactored into a shared library, at the very least, as Diagonal Windows now also exists and has a similar issue. I am hoping to get this fixed on Diagonal Fences' end instead.

**Comment by embeddedt** [comment]
This would cause older versions of Diagonal Fences to not show the diagonal connections when dynamic resources is enabled. (There currently isn't a mechanism to apply default changes based off mod version and not just the presence of the mod.)

**Comment by mllightitup** [comment]
Too bad :( When trying to add modernfix to Enigmatica 9, it took me a while to figure out which setting was causing problem

**Comment by embeddedt** [comment]
Fixed in 5.9.1.
