### ISSUE TITLE
1.16.5 - Strange JEI Pixelmon Startup Crash When Combined With ModernFix

### ISSUE THREAD

**Issue by P3rf3ctXZer0** [embeddedt/ModernFix#20]
https://gist.github.com/P3rf3ctXZer0/e304f0778365b7bf2d7d63127c6eeba1

[debug.log](https://github.com/embeddedt/ModernFix/files/10736055/debug.log)

**Comment by embeddedt** [comment]
I've just fixed this in the latest commit on GitHub, but it is not released yet.

**Comment by P3rf3ctXZer0** [comment]
I will close this when its released and I know it works. I promise :D

**Comment by embeddedt** [comment]
1.6.0 has been released with the fix.

**Comment by P3rf3ctXZer0** [comment]
This issue is fixed.
