### ISSUE TITLE
[Question] Features that may affect TPS on startup?

### ISSUE THREAD

**Issue by Rad586** [embeddedt/ModernFix#200]
1.18.2 fabric
This mod does a great job in reducing game loading time and memory usage, but some features may come with a cost. I’m not sure which feature could impact tps after I enter a world. The wiki only shows what these features do. 
Sorry for editing that many times, I accidentally pressed enter and it was created with no content😅

**Comment by embeddedt** [comment]
None of the features should be causing any measurable lag unless explicitly documented. You should be fine. :slightly_smiling_face:
