### ISSUE TITLE
`perf.thread_priorities` crash with Rubidium 0.7.0

### ISSUE THREAD

**Issue by gorillazrule** [embeddedt/ModernFix#201]
Whenever I try to launch the modpack I have created, it crashes before reaching the main menu.

Here is [latest log](https://pastebin.com/XQhPE04u).
List of mods I have installed [here](https://pastebin.com/jp4w4HVx), but when I disable ModernFix, it loads just fine.

**Comment by embeddedt** [comment]
One of your other mods loads a Minecraft class too early, which is bad practice and causes compatibility issues with other mods (like ModernFix). Please try to isolate which other mod is the culprit.

As a workaround you can add `mixin.perf.thread_priorities=false` at the bottom of `config/modernfix-mixins.properties`.

**Comment by embeddedt** [comment]
Apparently Rubidium 0.7.0 breaks this. It will need to be fixed on its end. I'll pin this issue so people coming to the tracker can see it.
