### ISSUE TITLE
Make wiki page more obvious on options screen

### ISSUE THREAD

**Issue by Madis0** [embeddedt/ModernFix#202]
I was just wondering, why use a separate `?` button for the descriptions, instead of displaying them as tooltips on each row.

**Comment by embeddedt** [comment]
Many of the descriptions are too long to fit in tooltips. I could add detection logic for short ones, but I didn't think the `?` button was hard to use, and if clicking a button is annoying to do for many options there is also the listing on the wiki.

**Comment by Madis0** [comment]
Well, as of 1.19.4 all tooltips should fit well, no matter their length. Maybe keep the button for older versions only?

Wiki is nice but requires users to know about its existence and still cross-reference the option names.

**Comment by embeddedt** [comment]
The issue is that I am not sure how multiple paragraphs of information would fit well on a tooltip. Using a separate screen means I can also implement scrolling later if it becomes needed.

I could add a link to the wiki?

**Comment by Madis0** [comment]
Okay, perhaps add a link to the wiki indeed.

**Comment by qznfbnj** [comment]
I have a question
![image](https://github.com/embeddedt/ModernFix/assets/100760086/558e2577-6875-4417-9d3f-55cde5b068f8)

**Comment by embeddedt** [comment]
Added the button in 5.7.0.
