### ISSUE TITLE
Can you optimize the network stack?

### ISSUE THREAD

**Issue by GitJhopa** [embeddedt/ModernFix#203]
Something like Pluto, Krypton?

**Comment by embeddedt** [comment]
Networking is not something I've noted as being a bottleneck so far, and the developers of those mods know more about how Netty works than I do. :laughing: So not planned for now.

**Comment by embeddedt** [comment]
By the way, I'd prefer Discord be used for general questions to avoid the issue tracker being flooded with things that aren't issues.
