### ISSUE TITLE
dynamic_dfu option crashes with Mystic's Biomes

### ISSUE THREAD

**Issue by Thunderrock424242** [embeddedt/ModernFix#204]
[launcher_log.txt](https://github.com/embeddedt/ModernFix/files/12286007/launcher_log.txt)
[latest.log](https://github.com/embeddedt/ModernFix/files/12286012/latest.log)
[crash-2023-08-07_20.15.34-client.txt](https://github.com/embeddedt/ModernFix/files/12286013/crash-2023-08-07_20.15.34-client.txt)

**Comment by embeddedt** [comment]
The `latest.log` file you have sent is not related to the attached crash report as there are no log messages from ModernFix in it. Please send the `latest.log` file that is associated with the crash.

**Comment by Thunderrock424242** [comment]
> The `latest.log` file you have sent is not related to the attached crash report as there are no log messages from ModernFix in it. Please send the `latest.log` file that is associated with the crash.

[latest.log](https://github.com/embeddedt/ModernFix/files/12296317/latest.log)
this is it when i play without modern fix i don't crash but when i do i do crash.

**Comment by embeddedt** [comment]
Adding `mixin.perf.dynamic_dfu=false` at the bottom of `config/modernfix-mixins.properties` should work around it for now.

**Comment by Thunderrock424242** [comment]
Alr thx

**Comment by embeddedt** [comment]
Should be fixed in 5.6.1.
