### ISSUE TITLE
I would like to see a Japanese translation Json added.

### ISSUE THREAD

**Issue by u7f8au7fbd** [embeddedt/ModernFix#205]
This mod is loved by many Japanese mod users, so we have created a Japanese translation of the Json so that more people can use it. If we provide it, would it be possible for you to add it?

**Comment by embeddedt** [comment]
Yep! Send a PR to the `1.16` branch.

**Comment by embeddedt** [comment]
PR has been merged and will be included in the next release.

**Comment by u7f8au7fbd** [comment]
thx
