### ISSUE TITLE
Suggest No Telemetry in the "Ultra Low Memory Footprint" instructions

### ISSUE THREAD

**Issue by 4194304** [embeddedt/ModernFix#208]
pretty simple, telemetry makes the game use more memory so this makes things a lot better
https://modrinth.com/mod/no-telemetry/version/1.7.0

**Comment by embeddedt** [comment]
> telemetry makes the game use more memory

Do you have any data/anecdotal evidence to suggest this makes a substantial difference (at least a megabyte or more)?

**Comment by 4194304** [comment]
when I tested it recently it liked to crash occasionally because of telemetry and when I disabled it I gained around 5 mb of memory

**Comment by 4194304** [comment]
it's extremely difficult to capture the difference with screenshots because the memory counter on the f3 screen changes more times per second than I could capture the difference with

**Comment by embeddedt** [comment]
Alright, I added a note to the page about it.

**Comment by 4194304** [comment]
relating to the subject Sodium 0.5.0 has done something to allow for fancy settings, and a 10 chunk render distance with no issues whatsoever (except when you relog)
![2023-08-09_13 10 23](https://github.com/embeddedt/ModernFix/assets/130800536/6b8fcacc-2dda-41be-b6f7-a6f7b51044cc)
