### ISSUE TITLE
Config changes are detected too early

### ISSUE THREAD

**Issue by ildiem** [embeddedt/ModernFix#210]
Running ModernFix 5.6.1+mc1.19.2 on Forge 43.2.21

Whenever I join a world, a message appears in chat that reads "Run /mfrc after changing configs on disk for them to take effect." The message appears again after a few seconds. I haven't ever touched ModernFix's config; the messages started to appear after updating the mod.

I tried deleting the configs and relaunching the game (which I guess is changing configs on disk) to hopefully reset things but nothing changed.

**Comment by embeddedt** [comment]
This message is harmless, but it's not supposed to detect config changes until after you have finished joining the world. The reason it's there is that Forge mod configs are not reloaded automatically anymore with ModernFix installed, so the message is supposed to inform you to run that command *if* you change a config file yourself. However, some mods modify their own config file by themselves for some reason, and that will also trigger the message.

I don't know if I can prevent this from occurring in all scenarios, so I might look into an alternative way of conveying this information (e.g. rendering the message on the pause screen).

**Comment by embeddedt** [comment]
Is this behavior improved with the beta? https://nightly.link/embeddedt/ModernFix/workflows/gradle/1.19.2/Package.zip

**Comment by embeddedt** [comment]
This should be fixed for good in 5.7.0.
