### ISSUE TITLE
[1.20.1] Crafting Recipes Search Not Working

### ISSUE THREAD

**Issue by WLK33R** [embeddedt/ModernFix#212]
Minecraft 1.20.1 - Modpack BMC4 Forge
Using ModernFix 5.6.0, it's breaking the search in the crafting table.
Confirmed removing the mod from the Client Side restores this functionality.

**Comment by embeddedt** [comment]
Do you have JEI or REI installed? If so this behavior is intentional, as
those mods provide the same functionality and the crafting table search
needs quite a bit of memory and time to load.

**Comment by WLK33R** [comment]
Thank you. 
Yes, JEI is part of the modpack.
Can this function be overridden in configuration? As the default crafting recipe is quicker in my opinion.

**Comment by embeddedt** [comment]
Yes, you can disable `mixin.perf.blast_search_trees`, at the cost of loading time being a bit longer and a bit more memory usage.

**Comment by WLK33R** [comment]
Thank you. Greatly appreciated!
