### ISSUE TITLE
Sodium 0.5+ currently breaks dynamic resources

### ISSUE THREAD

**Issue by TheBossMagnus** [embeddedt/ModernFix#214]
https://mclo.gs/AQXX2m6
During the loading of Minehut's resourcepack, the game sometimes crashes. I only experienced this crash with modernfix and mixin.perf.dynamic_resources enabled, but that might be a coincidence.
It's worth noting a couple of things
* During the resourcepack loading w/o crashes there are some probably related errors in the [log](https://mclo.gs/HwxKJYP)
* Another user is experiencing a similar issue, this time with missing texture on the same configuration: 
![image](https://github.com/embeddedt/ModernFix/assets/92474350/c5272dc9-683f-4998-8112-c56feca330f6)
See: https://github.com/TheBossMagnus/Thunder/issues/12

**Comment by embeddedt** [comment]
This appears to be a Sodium compatibility issue: https://github.com/CaffeineMC/sodium-fabric/issues/2011

**Comment by TheBossMagnus** [comment]
This crash will happen just with mixin.perf.dynamic_resources enabled or in any case?

**Comment by embeddedt** [comment]
It will probably not happen with dynamic_resources disabled, but the reason the issue occurs seems to be a Sodium design change, not a ModernFix bug.

**Comment by embeddedt** [comment]
One solution is to continue using Sodium 0.4.10.

**Comment by embeddedt** [comment]
Fixed in Sodium 0.5.2+.
