### ISSUE TITLE
Dimension threads

### ISSUE THREAD

**Issue by Thunderrock424242** [embeddedt/ModernFix#215]
I heard there was a mod a while back that made it so dimensions were not on a single thread I don't see that anymore it would be nice to have it for 1.20.1

**Comment by embeddedt** [comment]
This feature is not planned for ModernFix as it usually breaks mods that aren't designed with it in mind. ModernFix only includes performance tweaks that are likely to work with nearly every mod. As far as I know Dimensional Threading Reforged will be updated next for 1.20.2.
