### ISSUE TITLE
[1.19.2] Dynamic resources doesn't load Runic Enchanting textures

### ISSUE THREAD

**Issue by Sunconure11** [embeddedt/ModernFix#216]
mixin.perf.dynamic_resources=true 

May be causing items and blocks from it to render without no textures. Nothing else is affected.

**Comment by Sunconure11** [comment]
Can verify this is the case.

**Comment by Sunconure11** [comment]
https://www.curseforge.com/minecraft/mc-mods/runic-enchanting

**Comment by embeddedt** [comment]
Fixed in latest beta build linked in README, will be released as part of 5.7.0 soon :tm:

**Comment by Sunconure11** [comment]
https://modrinth.com/mod/softer-pastels/versions

Can you check this mod too, while you are at it? I noticed some missing textures when playing with it, and am wondering if they are caused by the same issue.

**Comment by embeddedt** [comment]
No, the missing textures/models there appear even without ModernFix.

**Comment by embeddedt** [comment]
Original issue should be fixed in 5.7.0.
