### ISSUE TITLE
[Suggestion-1.20.1-Forge] Option to disable the reload config message that gets sent in chat each world join.

### ISSUE THREAD

**Issue by Gbergz** [embeddedt/ModernFix#218]
Option to disable the reload config message that gets sent in chat each world join.

This message: `"Run /mfrc after changing configs on disk for them to take effect."`

Thanks.
**-** Gbergz

**Comment by embeddedt** [comment]
I think this is a duplicate of #210; the message is not supposed to appear that often. Can you see if the beta (linked in the README) has better behavior?

**Comment by Gbergz** [comment]
Yes with that version it no longer appears on every world load.

**Comment by embeddedt** [comment]
Cool! Underlying issue is fixed in 5.7.0.
