### ISSUE TITLE
1.16.5 - Crash with PuzzleLib and Fuz_ Diagonal Fences

### ISSUE THREAD

**Issue by P3rf3ctXZer0** [embeddedt/ModernFix#22]
https://gist.github.com/P3rf3ctXZer0/3f1da2e84b71c33f6952179bbf757b62

using 1.6.0 Modern fix.

**Comment by embeddedt** [comment]
Should be fixed in 1.6.1.

**Comment by P3rf3ctXZer0** [comment]
Testing now.

**Comment by P3rf3ctXZer0** [comment]
It is fixed thank you.
