### ISSUE TITLE
Random crash with Epic Fight installed

### ISSUE THREAD

**Issue by CapNapu** [embeddedt/ModernFix#220]
Crash Report: https://gist.github.com/CapNapu/7c0c245f08412d23a0189538a188e4c0

**Comment by embeddedt** [comment]
I think this is an Epic Fight bug; I do not see anything in the crash report that points to ModernFix.

**Comment by CapNapu** [comment]
Then, there is not much that can be done, Epic Fight stopped supporting 1.16.5 around a year ago. And they flatly refuse to patch any bug, (Even the critical ones) despite announcing the complete opposite on their Discord, but well, shenanigans...

**Comment by embeddedt** [comment]
Do you know if that dragon was in the End or not/whether the dragon fight
was active with a boss bar? My only guess for why that crash would happen
is if a dragon was spawned separately from the vanilla battle.

**Comment by CapNapu** [comment]
The dragon was summoned, but that doesn't matter because the next time the server didn't crash after doing exactly the same thing.

**Comment by CapNapu** [comment]
When I join the server, I see that the console spams reports, but it doesn't crashes as such, so it lets me join.

Then, doing anything (literally) can cause the server to go into a "vegetative state" (since it logs me out and gives me an error, but the server is still on), and after a while it crashes for real.

This error only happens when the console spams reports, and that is rare to happen (hence the "Random" in the title).
