### ISSUE TITLE
fabric-5.7.0-1.20.1 breaks water pushing mobs

### ISSUE THREAD

**Issue by donington** [embeddedt/ModernFix#222]
I have a chicken farm and with the latest version on modrinth (fabric-5.7.0+mc1.20.1) they are not being pushed by the water anymore and can walk freely as though there is no flowing water.  They do however, still suffer from suffocation and just drown themselves.

The previous version (fabric-5.6.1+mc1.20.1) did not have this issue.

**Comment by embeddedt** [comment]
Thanks for this. Can you check if the beta I have just put out fixes the issue? https://nightly.link/embeddedt/ModernFix/workflows/gradle/1.20/Package.zip

**Comment by donington** [comment]
I will test when I have a chance!

**Comment by donington** [comment]
It did not fix it, unfortunately.  Still seems to behaving strangely.  I might have time to take a closer look at this tomorrow.

**Comment by embeddedt** [comment]
That is strange, can you send the `latest.log` file from running with the beta?

**Comment by donington** [comment]
I've had some time to poke a bit deeper this morning, and I'm confident that this is a mod conflict of some sort.  I set up a test environment and it worked fine with only ModernFix.  The issue is recreated when both ModernFix and Lithium are installed.

Using that minimized test environment, here's the log:  [https://pastebin.com/tVp3YAcz](https://pastebin.com/tVp3YAcz)

**Comment by embeddedt** [comment]
Thanks. The log shows that my fix did not work, which is weird as it worked in dev. I'll look into this soon.

**Comment by embeddedt** [comment]
Ok, *this* time the fix should work. Can you try again? The link above should be updated.

**Comment by donington** [comment]
It appears to be back to normal.  Nice!

**Comment by embeddedt** [comment]
Fix released in 5.7.1.
