### ISSUE TITLE
[1.16.5] Incompatible with Modern Beta with Fabric modloader

### ISSUE THREAD

**Issue by Cloud547** [embeddedt/ModernFix#224]
Crash report: [crash-2023-08-20_13.51.20-server.txt](https://github.com/embeddedt/ModernFix/files/12388832/crash-2023-08-20_13.51.20-server.txt)
Log file: [latest.log](https://github.com/embeddedt/ModernFix/files/12388833/latest.log)

**Comment by embeddedt** [comment]
Disabling `mixin.perf.compress_biome_container` will fix this for now.

**Comment by embeddedt** [comment]
ModernFix disables that automatically in 5.7.1.
