### ISSUE TITLE
1.16.5 - Dedicated Server - World Build Crash Caused by Null Biome Namespace

### ISSUE THREAD

**Issue by P3rf3ctXZer0** [embeddedt/ModernFix#23]
https://gist.github.com/P3rf3ctXZer0/f43675b6a4c28f3bb1f18d197051ce75

**Comment by embeddedt** [comment]
Thanks, I should test on dedicated servers more frequently. It's fixed in 1.7.0.

**Comment by P3rf3ctXZer0** [comment]
> Thanks, I should test on dedicated servers more frequently. It's fixed in 1.7.0.

Leave it to me ;D
