### ISSUE TITLE
[ENHANCEMENT] Please add option to toggle the ModernFix_version in the bottom left of the game menu.

### ISSUE THREAD

**Issue by VOLKOUL** [embeddedt/ModernFix#230]
It would help achieve a clean look for those who want it. In the config you'd be able to toggle the ModernFix version on and off, so instead of ModernFix 5.7.1+mc1.19.2 there'd be nothing.

**Comment by Kichura** [comment]
> It would help achieve a clean look for those who want it. In the config you'd be able to toggle the ModernFix version on and off, so instead of ModernFix 5.7.1+mc1.19.2 there'd be nothing.

Just set `mixin.features.branding` to false in the modernfix config.

**Comment by embeddedt** [comment]
The correct name is `mixin.feature.branding`, but yes, in theory this should work.

**Comment by VOLKOUL** [comment]
THANK YOU! I couldn't figure out how to do that!
