### ISSUE TITLE
'mixin.perf.dynamic_block_codecs' is undocumented

### ISSUE THREAD

**Issue by dbl7id** [embeddedt/ModernFix#232]
There is no entry in the wiki for what this option does and affects

**Comment by dbl7id** [comment]
After doing a 2 minute research, I'm assuming it's related to Mojang's DFU. Is it safe to assume then that with the optmiization these codecs are loaded only when they are called or needed?

**Comment by embeddedt** [comment]
Mojang creates and stores a codec object for every block, which is completely fine for most modpacks. If you are trying to make a mod with a million blocks (as I was doing for some testing), this becomes rather expensive. The optimization modifies the game to generate the codecs on the fly, but mods that expect the codec to always be present (e.g. C2ME) will break. That is why it's not on by default. It's not really worth enabling unless you have hundreds of thousands of blocks, and I have never seen a real pack meeting that criteria.

**Comment by embeddedt** [comment]
Should be documented now.
