### ISSUE TITLE
Resource pack with invalid files causes dynamic resources to crash

### ISSUE THREAD

**Issue by ZZZank** [embeddedt/ModernFix#237]
I want to use [this resources pack](https://www.curseforge.com/minecraft/texture-packs/xekr-redstone-display/files/4159604) on my 1.16.5 instance. When Dynamic Resources is off, the process of changing res pack runs smoothly. But I then enabled Dynamic Resources, the game will crash during launching. 

I tried to remove any mods but ModernFix, this problem is still there. 
Crah report: [crash-2023-09-13_17.10.53-client.txt](https://github.com/embeddedt/ModernFix/files/12595687/crash-2023-09-13_17.10.53-client.txt)

I also tried starting a new instance, with Dynamic Resources pre-configured to on. It will report "unable to reload resources" when trying to change res pack. It didnt crash, but the res pack will not be loaded. 
log: 
[latest(dynres_on).log](https://github.com/embeddedt/ModernFix/files/12595719/latest.dynres_on.log)
[latest(dynres_off).log](https://github.com/embeddedt/ModernFix/files/12595721/latest.dynres_off.log)

**Comment by embeddedt** [comment]
This is because the resource pack contains a file with an invalid name (`models/block/pressure_plate_down x.json`). Resource pack files should not contain spaces. Manually removing the file from the pack fixes the issue.
