### ISSUE TITLE
Dynamic Resources breaks Vampirism's Altar of Inspiration Blood Level Filling

### ISSUE THREAD

**Issue by TheDrOfDoctoring** [embeddedt/ModernFix#242]
Reproducible on at least [Vampirism](https://www.curseforge.com/minecraft/mc-mods/vampirism-become-a-vampire) 1.9.5 and Modernfix 5.7.2 with Dynamic Resources enabled. Likely applies to all recent versions of vampirism other than 1.19.2, but I haven't tested them thoroughly.

To reproduce once joined world with dynamic resources enabled - 
- Become vampire with ``/vampirism level`` command
- Place an altar of inspiration and use bottles of blood on it
- With dynamic resources enabled, blood levels will not change.

![Screenshot from 2023-09-20 19-43-36](https://github.com/embeddedt/ModernFix/assets/59176662/bfa46e59-c550-408d-8fa1-f26cef89cd0a)
This is what it would look like normally

**Comment by embeddedt** [comment]
Please confirm that the beta fixes this (link in README).

**Comment by TheDrOfDoctoring** [comment]
Yes, fixed in beta, ty!

**Comment by embeddedt** [comment]
Released in 5.7.4.
