### ISSUE TITLE
Strongholds caching seems incompatible with c2me

### ISSUE THREAD

**Issue by Rad586** [embeddedt/ModernFix#245]
**Game:** 
fabric 1.18.2
**Environment:** 
c2me-fabric-mc1.18.2-0.2.0+alpha.7.38
modernfix-fabric-5.7.2+mc1.18.2
fabric-api-0.76.0+1.18.2
**Log:** 
https://gist.github.com/Rad233/b417dfbacab245355a081b5f7205f05f

**Comment by embeddedt** [comment]
Thanks, I'll make it disable itself when C2ME is present.
