### ISSUE TITLE
[1.19.2] Datapack issue upon creating a new world while having Fungal Infection: Spore 2.0.0X installed.

### ISSUE THREAD

**Issue by UnderPixel1475** [embeddedt/ModernFix#246]
I do believe the issue is with the_harbinger69's Fungal Infection: Spore mod. But, in any case, the debug.log file still will be attached below.

[debug.log](https://github.com/embeddedt/ModernFix/files/12707810/debug.log)

**Comment by embeddedt** [comment]
Cannot reproduce with the following set of mods - I was able to create a new world without issues.

![image](https://github.com/embeddedt/ModernFix/assets/42941056/3b5de92d-411a-4633-8307-534ca6b65911)

[This](https://legacy.curseforge.com/minecraft/mc-mods/fungal-infection-spore/files/4765189) is the version of Fungal Infection: Spore I used.

**Comment by embeddedt** [comment]
Are you able to reproduce with just those 2 mods in a fresh world?

**Comment by UnderPixel1475** [comment]
> Are you able to reproduce with just those 2 mods in a fresh world?

Hey embed. I deeply apologize for not being able to have seen your replies to my report, as I have been dealing with issues regarding my own personal life lately.

I did try your suggestion, I went ahead and disabled all of my mods in my modlist, leaving only Spore, ModernFix and FerriteCore (for the sake of my potato computer's memory) activated. Then, I tried creating a new world and ran into the same issue in the proccess of validating the datapacks, "Failed to validate datapacks."  Anyhoo, I will leave the debug.log file below and the complete version of my modlist (which has expanded these past few days, also I did change the dynamic_resources to false in the config file of ModernFix, in-order for it to work alongside Connectedness) for investigation's sake.

[modlist.txt](https://github.com/embeddedt/ModernFix/files/12771241/modlist.txt)

[debug.log](https://github.com/embeddedt/ModernFix/files/12771237/debug.log)

And also, I am genuinely thankful for your attention, not many mod developers are as attentive as you are.

**Comment by embeddedt** [comment]
It appears that you enabling `dynamic_block_codecs` is what broke it. :stuck_out_tongue: That option is experimental and I have only validated that it works with vanilla so far. I'll try to fix this in the future, but I'm quite swamped at the moment so I recommend just turning it off - there isn't really any benefit it will bring for the average modpack.

**Comment by UnderPixel1475** [comment]
> It appears that you enabling `dynamic_block_codecs` is what broke it. 😛 That option is experimental and I have only validated that it works with vanilla so far. I'll try to fix this in the future, but I'm quite swamped at the moment so I recommend just turning it off - there isn't really any benefit it will bring for the average modpack.

That was exactly the source of the issue, I would never have figured that out, lol. Was able not only to create a world but to spawn in it, also I completely understand if your busy trust me, I know the feeling. Besides like you said it yourself, it's not like it has a huge performance improvement to bigass modpacks like mine, and the problem's been solved so thanks a lot embed, we need more devs like you, keep perfecting your craft.
