### ISSUE TITLE
PizzaCraft mod textures not loading correctly 1.18.2

### ISSUE THREAD

**Issue by Billetiado10** [embeddedt/ModernFix#249]
I put the error here from the other mod, since in the debug.log it appears that modernfix does not correctly load the item pizza_slice and also the entity

Forge Version:1.18.2 40.2.10
Mod Version: modernfix-forge-5.7.4+mc1.18.2
Mod Version PizzaCraft: PizzaCraft-1.18.2-5.1.7
Lastest.log: https://mclo.gs/ZFYwEK5
Debug.log: https://mclo.gs/VWPEpTQ

https://github.com/Tiviacz1337/PizzaCraft/issues/101
![image](https://github.com/embeddedt/ModernFix/assets/76263374/027e48f2-0852-4748-ab98-8e47acb7fbe3)
![image](https://github.com/embeddedt/ModernFix/assets/76263374/50cc125f-7227-486c-90b2-63e486c33eee)
![image](https://github.com/embeddedt/ModernFix/assets/76263374/068c753e-8896-4e03-b9e3-8dac1dc8fae1)
![image](https://github.com/embeddedt/ModernFix/assets/76263374/86c8c838-5957-4347-9e67-753f8a4ea0b0)

**Comment by embeddedt** [comment]
Can you try to reproduce it with this test build and send the new log? It doesn't happen for me so I'll have to try and get more useful debug information via test builds.

[testbuild.zip](https://github.com/embeddedt/ModernFix/files/12751076/testbuild.zip)

**Comment by Billetiado10** [comment]
Okay, let me reproduce the problem

**Comment by Billetiado10** [comment]
This is the latest.log and some ModernFix errors appear, I also share the debug.log I'll give you a Video of what exactly happens with my World

Latest.log: https://mclo.gs/mIi5dZI
Debug.Log: https://mclo.gs/oExCSoX
![image](https://github.com/embeddedt/ModernFix/assets/76263374/684058b0-1efc-414d-aa3c-76eecf5e67c6)
VIDEO
https://youtu.be/AfPa1IvSNr0
I can share my worlds with you if you need them

**Comment by embeddedt** [comment]
I commented on the other issue - I don't see an easy way to fix this from my end at the moment.
