### ISSUE TITLE
[Question] About 441 Chunk Loading

### ISSUE THREAD

**Issue by Kasualix** [embeddedt/ModernFix#25]
What's the difference between [this](https://github.com/embeddedt/ModernFix/commit/bc5b85efcca5460bcfa3a9020b0314ed364c3ec5#diff-5092d313b350cad19ce5958401e15db24e6ca45aa7908c2c2a0526152ae1f13e) and [Ksyxis](https://github.com/VidTu/Ksyxis/blob/forge-1.16/src/main/java/ru/vidtu/ksyxis/mixins/MinecraftServerMixin.java)? Is this more stable and compatible? Is this incompatible with Ksyxis?

**Comment by embeddedt** [comment]
If both ModernFix and Ksyxis are installed then ModernFix takes priority. In theory my version of the patch should be slightly more stable, although it's hard to confirm without a specific example of a mod which doesn't work with Ksyxis.

**Comment by Kasualix** [comment]
Ok, thank you!
