### ISSUE TITLE
Dynamic Resources incompatible with Oculus (1.18.2)

### ISSUE THREAD

**Issue by Mqony** [embeddedt/ModernFix#250]
How to Reproduce: Enable Dynamic Resources and install Oculus.
About half of the chunks will become ghost chunks when the world is loaded. If you load a new chunk, that game crashes with this crash report.
[crash-2023-10-01_19.27.14-client.txt](https://github.com/embeddedt/ModernFix/files/12779158/crash-2023-10-01_19.27.14-client.txt)

**Comment by embeddedt** [comment]
Do you have a full log?

**Comment by Mqony** [comment]
Yes, here
[latest.log](https://github.com/embeddedt/ModernFix/files/12779200/latest.log)

**Comment by embeddedt** [comment]
The log suggests that the actual reason for the crash was an incompatibility with Dynamic Trees, which is [known](https://github.com/DynamicTreesTeam/DynamicTrees/issues/795), and needs to be fixed on their end. I think it was fixed on newer versions but I don't know if the fix was ever backported.

**Comment by Mqony** [comment]
It was caused by Dynamic Trees, I don't know why it was working fine when I disable Oculus.
