### ISSUE TITLE
Dynamic Resources Incompatible with Physics Mod

### ISSUE THREAD

**Issue by Mqony** [embeddedt/ModernFix#252]
**Issue**
The game crashes immediately upon loading into a world when Dynamic Resources is on and physics mod is installed.
[crash-2023-10-02_17.45.54-client.txt](https://github.com/embeddedt/ModernFix/files/12787450/crash-2023-10-02_17.45.54-client.txt)
[latest.log](https://github.com/embeddedt/ModernFix/files/12787451/latest.log)

**Comment by embeddedt** [comment]
This should be fixed in 5.8.1.
