### ISSUE TITLE
Incompatible with TrashSlot by BlaytheNinth

### ISSUE THREAD

**Issue by SoftboyMC** [embeddedt/ModernFix#256]
When ModernFix is enabled in Forge 1.20.1, the TrashSlot trash slot is hidden, and the delete keybind doesn't work.

**Comment by embeddedt** [comment]
I cannot reproduce this in a standalone instance with ModernFix and Trash Slot; the slot seems to show up without issues, and is functional. I'm using Forge 47.1.3.

**Comment by SoftboyMC** [comment]
I can't replicate it either. Guess it only happens on Mondays.
