### ISSUE TITLE
1.18.2 updates 5.7.0, 5.7.1, 5.7.2, 5.7.4 crash modpack

### ISSUE THREAD

**Issue by xFirefalconx** [embeddedt/ModernFix#257]
I am currently running my modpack (Forge 40.2.10, 1.18.2) on Modernfix 5.6.1, every never version crashes with the same error message. 
Seems to happen since 5.7.0, but I also tested with everything up until 5.7.4. 

Something about the weapon leveling mod (version 1.4.3) I am using? Not sure. 

[latest.log](https://github.com/embeddedt/ModernFix/files/12852556/latest.log)

To reproduce... I suppose using the latest version of "Royal Equines: Petrified Magic" (curseforge modpack) and then upgrading Modernfix to a higher version. Not tested though. Discovered while making updates and upgrading the pack to its next version. Might also be create or some other weird thing. Still debugging everything.

**Comment by embeddedt** [comment]
Sounds like the same issue as https://github.com/embeddedt/ModernFix/issues/226; Weapon Leveling was built incorrectly.

**Comment by xFirefalconx** [comment]
Thanks for the info! Seems WeaponLeveling is currently being reworked, according to the dev.
