### ISSUE TITLE
modernfix-forge-5.8.0+mc1.18.2.jar and modernfix-forge-5.8.1+mc1.18.2.jar cause Code -1

### ISSUE THREAD

**Issue by Silk-Hood** [embeddedt/ModernFix#258]
Downgrading to modernfix-forge-5.7.4+mc1.18.2.jar fixes issue
https://paste.ee/p/pFDa2

[latest.log](https://github.com/embeddedt/ModernFix/files/12886312/latest.log)
Mods:
  [✔️] AdHooks-1.18.2-8.0.0.0-build.0342.jar
  [✔️] AkashicTome-1.5-20.jar
  [✔️] alexsdelight-1.18.2-1.3.3.jar
  [✔️] alexsmobs-1.18.6.jar
  [✔️] Amplified_Nether_v1.1.1.jar
  [✔️] appleskin-forge-mc1.18.2-2.5.1.jar
  [✔️] Aquaculture-1.18.2-2.3.12.jar
  [✔️] ars_creo-1.18.2-2.2.0.jar
  [✔️] ars_industria-1.18.2-0.3.jar
  [✔️] ars_nouveau-1.18.2-2.9.0.jar
  [✔️] AutoRegLib-1.7-53.jar
  [✔️] balm-3.2.6.jar
  [✔️] bettercombat-forge-1.6.2+1.18.2.jar
  [✔️] betterfpsdist-1.18.2-1.5.jar
  [✔️] bettervillage-forge-1.18.2-3.2.0.jar
  [✔️] BiomesOPlenty-1.18.2-16.0.0.134.jar
  [✔️] blueprint-1.18.2-5.5.0.jar
  [✔️] caelus-forge-1.18.1-3.0.0.2.jar
  [✔️] canary-mc1.18.2-0.2.4.jar
  [✔️] carryon-1.18.2-1.17.1.12.jar
  [✔️] chefs-delight-1.0.2-forge-1.18.2.jar
  [✔️] citadel-1.11.3-1.18.2.jar
  [✔️] cloth-config-6.5.102-forge.jar
  [✔️] Clumps-forge-1.18.2-8.0.0+17.jar
  [✔️] Compat-O-Plenty-1.18.2-2.0.1.jar
  [✔️] Controlling-forge-1.18.2-9.0+23.jar
  [✔️] create_recycle_1.0.2_forge_1.18.2.jar
  [✔️] create-1.18.2-0.5.1.e.jar
  [✔️] createaddition-1.18.2-1.0.0.jar
  [✔️] CullLessLeaves-Reforged-1.18.2-1.0.5.jar
  [✔️] curios-forge-1.18.2-5.0.9.1.jar
  [✔️] curiouselytra-forge-1.18.1-5.0.1.0.jar
  [✔️] debugify-1.10.0-forge-1.18.2.jar
  [✔️] DistantHorizons-1.6.5a-1.18.2.jar
  [✔️] DoggyTalents-1.18.2-2.5.11.jar
  [✔️] domesticationinnovation-1.4.2-1.18.2.jar
  [✔️] drawerfps-1.18.2-2.4.jar
  [✔️] DungeonsArise-1.18.2-2.1.52-release.jar
  [✔️] dynamiclightsreforged-1.18.2_v1.3.3.jar
  [✔️] ends_delight-1.18.2-1.2.1.jar
  [✔️] EnhancedBlockEntities-Reforged-1.18.2-0.8.0.jar
  [✔️] entityculling-forge-1.6.1-mc1.18.2.jar
  [✔️] FarmersDelight-1.18.2-1.2.3.jar
  [✔️] feature_nbt_deadlock_be_gone_forge-2.0.0+1.18.2.jar
  [✔️] ferritecore-4.2.2-forge.jar
  [✔️] forbidden_arcanus-1.18.2-2.1.3.jar
  [✔️] ForgeEndertech-1.18.2-9.0.7.1-build.1530.jar
  [✔️] forgivingvoid-forge-1.18.1-6.0.1.jar
  [✔️] geckolib-forge-1.18-3.0.57.jar
  [✔️] getittogetherdrops-forge-1.18.2-1.3.jar
  [✔️] global_packs-forge-1.18.2-1.12.4_forge.jar
  [✔️] goblintraders-1.8.0-1.18.2.jar
  [✔️] guardvillagers-1.18.2.1.4.3.jar
  [✔️] iceandfire-2.1.12-1.18.2.jar
  [✔️] ImmersiveEngineering-1.18.2-8.4.0-161.jar
  [✔️] Incendium_1.18.2_v5.0.8.jar
  [✔️] infernal-expansion-1.18.2-2.5.0.jar
  [✔️] inventorypets-1.18.2-2.0.19.jar
  [✔️] invhud.forge.1.18.2-3.4.18.jar
  [✔️] Jade-1.18.2-forge-5.3.0.jar
  [✔️] jei-1.18.2-forge-10.2.1.1005.jar
  [✔️] JustEnoughProfessions-1.18.2-1.3.0.jar
  [✔️] JustEnoughResources-1.18.2-0.14.1.171.jar
  [✔️] kleeslabs-forge-1.18.2-11.1.1.jar
  [✔️] kotlinforforge-3.12.0-all.jar
  [✔️] lazydfu-1.0-1.18+.jar
  [✔️] libraryferret-forge-1.18.2-4.0.0.jar
  [✔️] Mantle-1.18.2-1.9.45.jar
  [✔️] modernfix-forge-5.8.0+mc1.18.2.jar
  [✔️] morestoragedrawers-1.18.2-1.1.2.jar
  [✔️] mvs-3.0.8-1.18.2.jar
  [✔️] Neat-1.8-31.jar
  [✔️] netherportalfix-forge-1.18.2-9.0.1.jar
  [✔️] NethersDelight-1.18.2-2.2.0.jar
  [✔️] Nullscape_1.18.2_v1.1.4.jar
  [✔️] ocrenderfix_sodium-forge-1.2.0.jar
  [✔️] OreExcavation-1.10.162.jar
  [✔️] ParCool-1.18.2-3.1.0.4-R.jar
  [✔️] Patchouli-1.18.2-71.1.jar
  [✔️] player-animation-lib-forge-1.0.2+1.18.jar
  [✔️] Quark-3.2-358.jar
  [✔️] QuarkOddities-1.18.jar
  [✔️] reforgium-1.18.2-1.0.12a.jar
  [✔️] Regrowth-1.18.2-40.31.2.jar
  [✔️] repurposed_structures_forge-5.1.14+1.18.2.jar
  [✔️] rubidium_extras-1.18.2_v1.3.2.jar
  [✔️] rubidium-0.5.6.jar
  [✔️] rubidium-extra-0.4.18+mc1.18.2-build.86.jar
  [✔️] saturn-mc1.18.2-0.0.4.jar
  [✔️] selene-1.18.2-1.17.14.jar
  [✔️] Serene Seasons-1.18.2-7.0.0.13.jar
  [✔️] sereneseasonfix-1.18.2-1.0.6.jar
  [✔️] SimpleBackups-1.18.2-1.1.13.jar
  [✔️] sliceanddice-forge-1.3.2.jar
  [✔️] smallships-forge-1.18.2-2.0.0-a2.3.1.jar
  [✔️] sophisticatedbackpacks-1.18.2-3.18.60.906.jar
  [✔️] sophisticatedcore-1.18.2-0.5.87.416.jar
  [✔️] spark-1.10.38-forge.jar
  [✔️] StorageDrawers-1.18.2-10.2.1.jar
  [✔️] supplementaries-1.18.2-1.5.18.jar
  [✔️] TCIntegrations-1.18.2-2.0.18.1.jar
  [✔️] tconplanner-1.18.2-1.2.0.jar
  [✔️] TConstruct-1.18.2-3.6.4.113.jar
  [✔️] TerraBlender-forge-1.18.2-1.2.0.126.jar
  [✔️] TextruesRubidiumOptions-1.0.8-mc1.18.2.jar
  [✔️] tombstone-7.6.6-1.18.2.jar
  [✔️] tooltipscroller-1.18-1.0.0.jar
  [✔️] toomanyglyphs-1.18.1-2.0.7.15321.jar
  [✔️] upgrade_aquatic-1.18.2-4.0.0.jar
  [✔️] valhelsia_core-forge-1.18.2-0.4.0.jar
  [✔️] valhelsia_structures-1.18.2-0.1.1.jar
  [✔️] vanilla-refresh-1.4.16e.jar
  [✔️] waystones-forge-1.18.2-10.2.1.jar
  [✔️] Xaeros_Minimap_23.8.2_Forge_1.18.2.jar
  [✔️] xaeros_waystones_compability-1.18.2-1.0.jar
  [✔️] XaerosWorldMap_1.34.1_Forge_1.18.2.jar
  [✔️] YungsApi-1.18.2-Forge-2.2.9.jar
  [✔️] YungsBetterDungeons-1.18.2-Forge-2.1.0.jar
  [✔️] YungsBetterMineshafts-1.18.2-Forge-2.2.jar
  [✔️] YungsBetterNetherFortresses-1.18.2-Forge-1.0.0.jar
  [✔️] YungsBetterStrongholds-1.18.2-Forge-2.1.1.jar
  [✔️] YungsBridges-1.18.2-Forge-2.1.0.jar

**Comment by embeddedt** [comment]
You have Debugify installed - this is probably https://github.com/embeddedt/ModernFix/issues/233, which is an issue with Debugify.

**Comment by Silk-Hood** [comment]
Thank you.

**Comment by Silk-Hood** [comment]
Oh wait nevermind I updated saturn and the isssue comes back.
https://paste.ee/p/F0Y4F
Mods:
  [✔️] AdHooks-1.18.2-8.0.0.0-build.0342.jar
  [✔️] AkashicTome-1.5-20.jar
  [✔️] alexsdelight-1.18.2-1.3.3.jar
  [✔️] alexsmobs-1.18.6.jar
  [✔️] Amplified_Nether_v1.1.1.jar
  [✔️] appleskin-forge-mc1.18.2-2.5.1.jar
  [✔️] Aquaculture-1.18.2-2.3.12.jar
  [✔️] ars_creo-1.18.2-2.2.0.jar
  [✔️] ars_industria-1.18.2-0.3.jar
  [✔️] ars_nouveau-1.18.2-2.9.0.jar
  [✔️] AutoRegLib-1.7-53.jar
  [✔️] balm-3.2.6.jar
  [✔️] bettercombat-forge-1.6.2+1.18.2.jar
  [✔️] betterfpsdist-1.18.2-1.5.jar
  [✔️] bettervillage-forge-1.18.2-3.2.0.jar
  [✔️] BiomesOPlenty-1.18.2-16.0.0.134.jar
  [✔️] blueprint-1.18.2-5.5.0.jar
  [✔️] caelus-forge-1.18.1-3.0.0.2.jar
  [✔️] canary-mc1.18.2-0.2.4.jar
  [✔️] carryon-1.18.2-1.17.1.12.jar
  [✔️] chefs-delight-1.0.2-forge-1.18.2.jar
  [✔️] citadel-1.11.3-1.18.2.jar
  [✔️] cloth-config-6.5.102-forge.jar
  [✔️] Clumps-forge-1.18.2-8.0.0+17.jar
  [✔️] Compat-O-Plenty-1.18.2-2.0.1.jar
  [✔️] Controlling-forge-1.18.2-9.0+23.jar
  [✔️] create_recycle_1.0.2_forge_1.18.2.jar
  [✔️] create-1.18.2-0.5.1.e.jar
  [✔️] createaddition-1.18.2-1.0.0.jar
  [✔️] CullLessLeaves-Reforged-1.18.2-1.0.5.jar
  [✔️] curios-forge-1.18.2-5.0.9.1.jar
  [✔️] curiouselytra-forge-1.18.1-5.0.1.0.jar
  [✔️] DistantHorizons-1.6.5a-1.18.2.jar
  [✔️] DoggyTalents-1.18.2-2.5.11.jar
  [✔️] domesticationinnovation-1.4.2-1.18.2.jar
  [✔️] drawerfps-1.18.2-2.4.jar
  [✔️] DungeonsArise-1.18.2-2.1.52-release.jar
  [✔️] dynamiclightsreforged-1.18.2_v1.3.3.jar
  [✔️] ends_delight-1.18.2-1.2.1.jar
  [✔️] EnhancedBlockEntities-Reforged-1.18.2-0.8.0.jar
  [✔️] entityculling-forge-1.6.1-mc1.18.2.jar
  [✔️] FarmersDelight-1.18.2-1.2.3.jar
  [✔️] feature_nbt_deadlock_be_gone_forge-2.0.0+1.18.2.jar
  [✔️] ferritecore-4.2.2-forge.jar
  [✔️] forbidden_arcanus-1.18.2-2.1.3.jar
  [✔️] ForgeEndertech-1.18.2-9.0.7.1-build.1530.jar
  [✔️] forgivingvoid-forge-1.18.1-6.0.1.jar
  [✔️] geckolib-forge-1.18-3.0.57.jar
  [✔️] getittogetherdrops-forge-1.18.2-1.3.jar
  [✔️] global_packs-forge-1.18.2-1.12.4_forge.jar
  [✔️] goblintraders-1.8.0-1.18.2.jar
  [✔️] guardvillagers-1.18.2.1.4.3.jar
  [✔️] iceandfire-2.1.12-1.18.2.jar
  [✔️] ImmersiveEngineering-1.18.2-8.4.0-161.jar
  [✔️] Incendium_1.18.2_v5.0.8.jar
  [✔️] infernal-expansion-1.18.2-2.5.0.jar
  [✔️] inventorypets-1.18.2-2.0.19.jar
  [✔️] invhud.forge.1.18.2-3.4.18.jar
  [✔️] Jade-1.18.2-forge-5.3.0.jar
  [✔️] jei-1.18.2-forge-10.2.1.1005.jar
  [✔️] JustEnoughProfessions-1.18.2-1.3.0.jar
  [✔️] JustEnoughResources-1.18.2-0.14.1.171.jar
  [✔️] kleeslabs-forge-1.18.2-11.1.1.jar
  [✔️] kotlinforforge-3.12.0-all.jar
  [✔️] lazydfu-1.0-1.18+.jar
  [✔️] libraryferret-forge-1.18.2-4.0.0.jar
  [✔️] Mantle-1.18.2-1.9.45.jar
  [✔️] modernfix-forge-5.8.1+mc1.18.2.jar
  [✔️] morestoragedrawers-1.18.2-1.1.2.jar
  [✔️] mvs-3.0.8-1.18.2.jar
  [✔️] Neat-1.8-31.jar
  [✔️] netherportalfix-forge-1.18.2-9.0.1.jar
  [✔️] NethersDelight-1.18.2-2.2.0.jar
  [✔️] Nullscape_1.18.2_v1.1.4.jar
  [✔️] ocrenderfix_sodium-forge-1.2.0.jar
  [✔️] OreExcavation-1.10.162.jar
  [✔️] ParCool-1.18.2-3.1.0.4-R.jar
  [✔️] Patchouli-1.18.2-71.1.jar
  [✔️] player-animation-lib-forge-1.0.2+1.18.jar
  [✔️] Quark-3.2-358.jar
  [✔️] QuarkOddities-1.18.jar
  [✔️] reforgium-1.18.2-1.0.12a.jar
  [✔️] Regrowth-1.18.2-40.31.2.jar
  [✔️] repurposed_structures_forge-5.1.14+1.18.2.jar
  [✔️] rubidium_extras-1.18.2_v1.3.2.jar
  [✔️] rubidium-0.5.6.jar
  [✔️] rubidium-extra-0.4.18+mc1.18.2-build.86.jar
  [✔️] saturn-mc1.18.2-0.0.5.jar
  [✔️] selene-1.18.2-1.17.14.jar
  [✔️] Serene Seasons-1.18.2-7.0.0.13.jar
  [✔️] sereneseasonfix-1.18.2-1.0.6.jar
  [✔️] SimpleBackups-1.18.2-1.1.13.jar
  [✔️] sliceanddice-forge-1.3.2.jar
  [✔️] smallships-forge-1.18.2-2.0.0-a2.3.1.jar
  [✔️] sophisticatedbackpacks-1.18.2-3.18.60.906.jar
  [✔️] sophisticatedcore-1.18.2-0.5.87.416.jar
  [✔️] spark-1.10.38-forge.jar
  [✔️] StorageDrawers-1.18.2-10.2.1.jar
  [✔️] supplementaries-1.18.2-1.5.18.jar
  [✔️] TCIntegrations-1.18.2-2.0.18.1.jar
  [✔️] tconplanner-1.18.2-1.2.0.jar
  [✔️] TConstruct-1.18.2-3.6.4.113.jar
  [✔️] TerraBlender-forge-1.18.2-1.2.0.126.jar
  [✔️] TextruesRubidiumOptions-1.0.8-mc1.18.2.jar
  [✔️] tombstone-7.6.6-1.18.2.jar
  [✔️] tooltipscroller-1.18-1.0.0.jar
  [✔️] toomanyglyphs-1.18.1-2.0.7.15321.jar
  [✔️] upgrade_aquatic-1.18.2-4.0.0.jar
  [✔️] valhelsia_core-forge-1.18.2-0.4.0.jar
  [✔️] valhelsia_structures-1.18.2-0.1.1.jar
  [✔️] vanilla-refresh-1.4.16e.jar
  [✔️] waystones-forge-1.18.2-10.2.1.jar
  [✔️] Xaeros_Minimap_23.8.2_Forge_1.18.2.jar
  [✔️] xaeros_waystones_compability-1.18.2-1.0.jar
  [✔️] XaerosWorldMap_1.34.1_Forge_1.18.2.jar
  [✔️] YungsApi-1.18.2-Forge-2.2.9.jar
  [✔️] YungsBetterDungeons-1.18.2-Forge-2.1.0.jar
  [✔️] YungsBetterMineshafts-1.18.2-Forge-2.2.jar
  [✔️] YungsBetterNetherFortresses-1.18.2-Forge-1.0.0.jar
  [✔️] YungsBetterStrongholds-1.18.2-Forge-2.1.1.jar
  [✔️] YungsBridges-1.18.2-Forge-2.1.0.jar

**Comment by embeddedt** [comment]
This is a bug with one of Saturn's mixins.

```
Caused by: org.spongepowered.asm.mixin.throwables.MixinApplyError: Mixin [saturn.mixins.json:world.temperature_cache.BiomeMixin] from phase [DEFAULT] in config [saturn.mixins.json] FAILED during APPLY
	at MC-BOOTSTRAP/org.spongepowered.mixin/org.spongepowered.asm.mixin.transformer.MixinProcessor.handleMixinError(MixinProcessor.java:636)
	at MC-BOOTSTRAP/org.spongepowered.mixin/org.spongepowered.asm.mixin.transformer.MixinProcessor.handleMixinApplyError(MixinProcessor.java:588)
	at MC-BOOTSTRAP/org.spongepowered.mixin/org.spongepowered.asm.mixin.transformer.MixinProcessor.applyMixins(MixinProcessor.java:379)
	... 25 more
Caused by: org.spongepowered.asm.mixin.transformer.throwables.InvalidMixinException: PRIVATE @Overwrite method m_47505_ in saturn.mixins.json:world.temperature_cache.BiomeMixin cannot reduce visibiliy of PUBLIC target method
	at MC-BOOTSTRAP/org.spongepowered.mixin/org.spongepowered.asm.mixin.transformer.MixinPreProcessorStandard.conformVisibility(MixinPreProcessorStandard.java:485)
	at MC-BOOTSTRAP/org.spongepowered.mixin/org.spongepowered.asm.mixin.transformer.MixinPreProcessorStandard.attachSpecialMethod(MixinPreProcessorStandard.java:458)
	at MC-BOOTSTRAP/org.spongepowered.mixin/org.spongepowered.asm.mixin.transformer.MixinPreProcessorStandard.attachOverwriteMethod(MixinPreProcessorStandard.java:419)
	at MC-BOOTSTRAP/org.spongepowered.mixin/org.spongepowered.asm.mixin.transformer.MixinPreProcessorStandard.attachMethods(MixinPreProcessorStandard.java:349)
	at MC-BOOTSTRAP/org.spongepowered.mixin/org.spongepowered.asm.mixin.transformer.MixinPreProcessorStandard.attach(MixinPreProcessorStandard.java:302)
	at MC-BOOTSTRAP/org.spongepowered.mixin/org.spongepowered.asm.mixin.transformer.MixinPreProcessorStandard.createContextFor(MixinPreProcessorStandard.java:280)
	at MC-BOOTSTRAP/org.spongepowered.mixin/org.spongepowered.asm.mixin.transformer.MixinInfo.createContextFor(MixinInfo.java:1288)
	at MC-BOOTSTRAP/org.spongepowered.mixin/org.spongepowered.asm.mixin.transformer.MixinApplicatorStandard.apply(MixinApplicatorStandard.java:292)
	at MC-BOOTSTRAP/org.spongepowered.mixin/org.spongepowered.asm.mixin.transformer.TargetClassContext.apply(TargetClassContext.java:383)
	at MC-BOOTSTRAP/org.spongepowered.mixin/org.spongepowered.asm.mixin.transformer.TargetClassContext.applyMixins(TargetClassContext.java:365)
	at MC-BOOTSTRAP/org.spongepowered.mixin/org.spongepowered.asm.mixin.transformer.MixinProcessor.applyMixins(MixinProcessor.java:363)
```
