### ISSUE TITLE
Crash when breaking a Solar Panel from Cyclic

### ISSUE THREAD

**Issue by Catomax262** [embeddedt/ModernFix#260]
crash: https://crashy.net/8603bcd8-1425-4bfa-8541-7f0cefc8f658

**Comment by embeddedt** [comment]
This looks like a bug in Cyclic; the cache it uses for block shapes is not thread-safe.

**Comment by embeddedt** [comment]
I've added a patch for it from ModernFix's end since getting it fixed in Cyclic will probably be slow.

**Comment by embeddedt** [comment]
This crash should not occur with 5.9+.
