### ISSUE TITLE
Game becomes unresponsive, all I can do is move around but game no longer updates.

### ISSUE THREAD

**Issue by Devestatio** [embeddedt/ModernFix#261]
With my MC 1.20.1 - FML mod pack, I get this error in the log, and once it shows up, it gets stuck in a loop, and I have to force close my game session.

[00:30:54] [ModernFix integrated server watchdog/ERROR] [or.em.mo.wo.IntegratedWatchdog/]: A single server tick has taken 330670, more than 40000 milliseconds
[00:30:55] [ModernFix integrated server watchdog/ERROR] [or.em.mo.wo.IntegratedWatchdog/]: Thread Dump:
"Render thread" prio=10 Id=1 RUNNABLE

https://www.transfernow.net/dl/Modern_Fix_Crash

**Comment by embeddedt** [comment]
This isn't an issue with ModernFix; it's just providing you more information than vanilla so you can actually find the cause of the problem (it's nearly impossible to track down the problematic mod without). In this case NoMoWanderer is the cause of the freeze; it appears to be tracked here: https://github.com/J-Dill/NoMoWanderer/issues/16

**Comment by Devestatio** [comment]
Ah ok, I wasn't able to find that part in the log, where it stated that it was NoMoWanderer, it just kept spamming The Modern Fix part. Thank you for pointing that out.
