### ISSUE TITLE
Crash With Windows Sizeing

### ISSUE THREAD

**Issue by Natedogwoooof** [embeddedt/ModernFix#263]
idk if this is a moderen fix issue but when i removed moderenfix it fixed the issue

OS Linux Unbuntu 20.4 LTS

Minecraft 1.16.5 
[crash-2023-10-14_12.54.59-client.txt](https://github.com/embeddedt/ModernFix/files/12907403/crash-2023-10-14_12.54.59-client.txt)

forge 36.2.39

idk if this is a Moderenfix issue but i removed it and then it fixed my issue so im guessing it is

**Comment by embeddedt** [comment]
The crash appears to be caused by a Rubidium mixin. I would recommend seeing if swapping to Embeddium fixes it.

**Comment by Natedogwoooof** [comment]
> The crash appears to be caused by a Rubidium mixin. I would recommend seeing if swapping to Embeddium fixes it.

fixed it swapping to embeddium fixed my issue.
