### ISSUE TITLE
Config screen automatically scrolls to the top when going back from the help screen

### ISSUE THREAD

**Issue by Fuyukai** [embeddedt/ModernFix#266]
1. Click question mark button next to a config option
2. Press done
3. Config screen scrolls up.

This makes it kinda annoying to configure things. It would be great if the scroll location was kept the same. 

This is on Fabric 1.20.1 if that makes any difference.

**Comment by qznfbnj** [comment]
Me too
https://github.com/embeddedt/ModernFix/pull/153#issuecomment-1626886717
![image](https://github.com/embeddedt/ModernFix/assets/100760086/4a15edc6-d986-4feb-b882-641d8425d4f7)

**Comment by embeddedt** [comment]
The scroll location is preserved in 5.9+.
