### ISSUE TITLE
Dynamic Block Codecs causes crash with Farmer's Delight

### ISSUE THREAD

**Issue by Fuyukai** [embeddedt/ModernFix#267]
Le datafixerupper has arrived.

Full Prism log: https://gist.github.com/Fuyukai/6e9604ce436720bbdb194f4816e186f3

**Comment by embeddedt** [comment]
There is a known flaw with dynamic block codecs when it loads the data of some mods; that's why it's not enabled by default. I think this is the same issue as https://github.com/embeddedt/ModernFix/issues/246.

**Comment by Fuyukai** [comment]
Alright. Just good to have a record of it I guess.
