### ISSUE TITLE
Dynamic resources causes TreeChop blocks to be invisible

### ISSUE THREAD

**Issue by Willem07** [embeddedt/ModernFix#269]
Download:
[modernfix-forge-5.8.1+mc1.20.1](https://legacy.curseforge.com/minecraft/mc-mods/modernfix/files/4792389)
[TreeChop-1.20.1-forge-0.18.3](https://legacy.curseforge.com/minecraft/mc-mods/treechop/files/4685647)

Turn on the line `mixin.perf.dynamic_resources=true` in _`modernfix-mixins.properties`_

invisible chop tree
![2023-10-17_14 18 05](https://github.com/embeddedt/ModernFix/assets/51959206/9ebeb4bc-e972-4f2a-b964-204ca11d9f66)

**Comment by Willem07** [comment]
1.20.1-forge-47.2.1

**Comment by embeddedt** [comment]
I can't reproduce this in a standalone instance with Forge 47.2.1, ModernFix 5.8.1 and TreeChop 0.18.3; even with dynamic resources enabled the tree model renders without problems.

![2023-10-17_09 25 48](https://github.com/embeddedt/ModernFix/assets/42941056/07981b3f-9e30-43d1-a8d4-fc20006ad8a3)

**Comment by Willem07** [comment]
It's a pity, there might be an issue with the video card driver. The tree model renders without any problems on my friends' computers.

**Comment by embeddedt** [comment]
I don't think it is related to dynamic resources since the behavior is not consistent across different systems, so yeah - probably GPU-related.
