### ISSUE TITLE
[Feature] Show the default value of each mixin options in modernfix-mixins.properties

### ISSUE THREAD

**Issue by ZZZank** [embeddedt/ModernFix#27]
I found (in the source file) that some mixin rules, like "feature.reduce_loading_screen_freezes", are disabled by default. But meanwhile, I cannot know whether a option is enabled, disabled or varied through modernfix-mixins.properties. I think adding something like "= value" will be helpful. 

EDIT: I checked the ModernFixEarlyConfig.java again, and find `writer.write(key + "=" + value + "\n");` . Strangely, this code doesn't seem to be working. 

EDIT_AGAIN: I regenerated those config files twice, but the options are still not shown.

**Comment by Kasualix** [comment]
[here](https://github.com/embeddedt/ModernFix/blob/0cf089febedeab72b43457f25e864c85cd1072a0/src/main/java/org/embeddedt/modernfix/core/config/ModernFixEarlyConfig.java#L204)

**Comment by Kasualix** [comment]
> EDIT: I checked the ModernFixEarlyConfig.java again, and find `writer.write(key + "=" + value + "\n");` . Strangely, this code doesn't seem to be working.
这行的作用不是用来加默认值的，而是用来加你写过的值的。
没有这行的话，如果你在properties里写点开关mixin的东西，每次启动游戏它们都会被移除。

**Comment by ZZZank** [comment]
[issue#47](https://github.com/embeddedt/ModernFix/pull/47)
