### ISSUE TITLE
[1.19.2] ModernFix watchdog/ERROR

### ISSUE THREAD

**Issue by Doctor-Duck** [embeddedt/ModernFix#270]
Hello,

I am running a FML modpack and get an watchdog/ERROR from ModernFix saying: "A single server tick has taken 40001, more than 40000 milliseconds." 

I know that this isn't an issue with ModernFix, as mentioned in #261, but I was unsure where to begin looking to figure out what causes this issue. Any help at all would be appreciated!

The thread dump: https://pastebin.com/ZNtbR0EK

**Comment by embeddedt** [comment]
It looks like it's NoMoWanderer in this thread dump as well.

**Comment by Doctor-Duck** [comment]
It was in fact because of NoMoWanderer.
