### ISSUE TITLE
[Fabric 1.20.1] ModernFix causes Creative inventory search to always be empty

### ISSUE THREAD

**Issue by Quasi-Detective** [embeddedt/ModernFix#272]
This only happens when paired with certain mods, such as CarryOn (but there are PLENTY of others). Otherwise, removing ModernFix, the creative search works with all of the mods I have installed. Only problem: game hardly loads anymore because ModernFix also happens to be what keeps the game functioning. But I really need Creative's search function to work, because the way crap gets sorted in Creative is brain-meltingly dumb and I can never find what I need without scouring for minutes at a time.

Without ModernFix: if the game loads, typing "ee" in Creative search shows a bunch of items with "ee" in the name.
With ModernFix: the game WILL load for sure, but typing "ee" in Creative search (or even just "e") shows absolutely no items.

Worth noting it SORT OF seemed to work on Fabric Loader 0.14.23, but I had to downgrade to 0.14.22 to use Polymorph because for some reason no one's updating it to support 0.14.23. Now it's completely broken if ModernFix is installed.

Why is it doing this? Why is ModernFix even touching the Creative search function at all? Please help.

**Comment by embeddedt** [comment]
When REI or JEI are installed, ModernFix modifies creative search to use their search facilities, as vanilla's search functionality takes a very long time to initialize. I would need to see a log to figure out why this causes creative search to not work at all, but you can also disable that feature by adding `mixin.perf.blast_search_trees=false` at the bottom of `config/modernfix-mixins.properties`.

**Comment by Quasi-Detective** [comment]
> When REI or JEI are installed, ModernFix modifies creative search to use their search facilities, as vanilla's search functionality takes a very long time to initialize. I would need to see a log to figure out why this causes creative search to not work at all, but you can also disable that feature by adding `mixin.perf.blast_search_trees=false` at the bottom of `config/modernfix-mixins.properties`.

Oh, thank god. I had REI 12.0.665 installed, and for some reason it was bugging out immensely, and its search feature wasn't working at all. What's strange is that REI + ModernFix sometimes works based on what mods are installed... I guess this issue is mostly with REI though. Uninstalling REI (I rarely used it anyway) solved the issue, and now the Creative search feature works with ModernFix installed again. Thank you!
