### ISSUE TITLE
mixin conflict between ModernFix and Lithium [Fabric 1.18.2]

### ISSUE THREAD

**Issue by PlayfulPiano** [embeddedt/ModernFix#274]
Relevant line from latest.log:
`[03:39:17] [Server thread/WARN]: Method overwrite conflict for removeIf in modernfix-common.mixins.json:bugfix.paper_chunk_patches.SortedArraySetMixin from mod modernfix, previously written by me.jellysquid.mods.lithium.mixin.world.chunk_tickets.SortedArraySetMixin. Skipping method.`

Modernfix 5.8.1
Lithium 0.10.3

Fabric v0.14.23 (mc v1.18.2)

No functionality issues discovered, but wanted to report this mixin conflict just in case.

**Comment by embeddedt** [comment]
This is known, and should be harmless. But thanks for the report. :)
