### ISSUE TITLE
Server crash, probably because of this mod?

### ISSUE THREAD

**Issue by DonorKrovi** [embeddedt/ModernFix#275]
Minecraft Version
1.20.x

Mod Loader
Forge

Mod Loader Version
47.1.3

Mod Version
modernfix-forge-5.8.1+mc1.20.1

Describe the Issue
I'm loading chunks in the world and it's very difficult for me to determine what is causing the server to freeze and crash, I have an assumption that this is related to this mod, can you help me?

Logs
https://mclo.gs/1Db0xSg

My optimization mods:
AI-Improvements-1.20-0.5.2, chunksending-1.20.1-2.6, chunkumulator-1.0.3+MC1.20.1, Chunky-1.3.92, ferritecore-6.0.1-forge, getittogetherdrops-forge-1.20-1.3, memoryleakfix-forge-1.17+-1.1.2, modernfix-forge-5.8.1+mc1.20.1, servercore-forge-1.3.7+1.20.1, smoothchunk-1.20.1-3.1, starlight-1.1.2+forge.1cda73c,

**Comment by embeddedt** [comment]
Since you are using 1.20.1 this is most likely caused by Starlight. As far as I know, ModernFix does not cause watchdog freezes.
