### ISSUE TITLE
[CRASH] [1.20.1] UNSURE IF THIS IS MODERNFIX BUT...

### ISSUE THREAD

**Issue by Camawama** [embeddedt/ModernFix#276]
My modpack is crashing when I enter certain areas. I have ModernFix installed and I am wondering if it is the culprit here. The crash report contained a lot of information and I am normally good at debugging crash reports but this one is confusing. I saw ModernFix mentioned many times in the crash.

CRASH REPORT:
[crash-2023-10-25_20.41.05-client.txt](https://github.com/embeddedt/ModernFix/files/13172169/crash-2023-10-25_20.41.05-client.txt)

**Comment by embeddedt** [comment]
No, I don't think it's ModernFix. Another mod is probably accessing the client-side world's random number generator on the wrong thread - this is not allowed, and will cause random crashes. You can try installing [BetterRandomSourceConcurrencyCrash](https://legacy.curseforge.com/minecraft/mc-mods/betterrandomsourceconcurrencycrash) as a debugging aid to provide more information when the crash happens next - do not keep it installed afterwards as it will slow down the game.

**Comment by Camawama** [comment]
Thank you for the useful info! Apologies for the false report.
