### ISSUE TITLE
better end forge incompatablity forge 1.16.5

### ISSUE THREAD

**Issue by Natedogwoooof** [embeddedt/ModernFix#277]
when i have dynamic resource nabled my game crashes when loading with betterendforge

minecraft: forge 1.16.5

forge verson: 36.2.39
[crash-2023-10-26_13.30.03-client.txt](https://github.com/embeddedt/ModernFix/files/13181462/crash-2023-10-26_13.30.03-client.txt)

**Comment by Natedogwoooof** [comment]
better end forge verson is 1.16.5  1.6.3

**Comment by embeddedt** [comment]
I believe https://legacy.curseforge.com/minecraft/mc-mods/better-end-potato-edition fixes this, among other things.

**Comment by Natedogwoooof** [comment]
> I believe https://legacy.curseforge.com/minecraft/mc-mods/better-end-potato-edition fixes this, among other things.

yep i used that one i forgot to close this sorry
