### ISSUE TITLE
exception_access_violation with Axiom

### ISSUE THREAD

**Issue by Daniel99j2** [embeddedt/ModernFix#279]
When using Axiom, and any version of modernfix above 5.7, then a exception_access_violation will occur.
Devs of axiom said the issue was with 5.8+ modernfix
[hs_err_pid24616.log](https://github.com/embeddedt/ModernFix/files/13194008/hs_err_pid24616.log)
[latest.log](https://github.com/embeddedt/ModernFix/files/13194009/latest.log)

**Comment by embeddedt** [comment]
This should be fixed in the beta (link available in README); please confirm if you have time.
