### ISSUE TITLE
Minecraft completly breaks

### ISSUE THREAD

**Issue by hankjelino** [embeddedt/ModernFix#28]
![image](https://user-images.githubusercontent.com/118378633/222809096-63e9d146-0663-43fa-9aca-14246e40f79e.png)
![image](https://user-images.githubusercontent.com/118378633/222809815-3578b8d6-a44f-4aeb-a7d6-0259e7997f54.png)

Minecraft completly breaks when using the mod, removing it completly fixes the issue. I am running FTB Academy 1.16 with a few performance mods (all of which should be compatible, at least they worked in 1.7 and prior).  [modlist](https://pastebin.com/wvvML3dY)

I am using modernfix 1.9, updated from 1.7

**Comment by embeddedt** [comment]
Please send your `latest.log` file when this occurs.

**Comment by hankjelino** [comment]
[latest.log](https://github.com/embeddedt/ModernFix/files/10885583/latest.log)

**Comment by embeddedt** [comment]
Thanks. You can add `mixin.perf.faster_texture_stitching=false` to `config/modernfix-mixins.properties` as a workaround for now; that should let you launch and play the game without issues.

Can I ask what launcher you are using?

**Comment by Kasualix** [comment]
PrismLauncher

**Comment by embeddedt** [comment]
I wonder why the LWJGL version is so modern then. Anyways, I will add a fix.

**Comment by hankjelino** [comment]
The LWJFL version is 3.3.1 because I changed it (no reason, changed it back to 3.2.2 now) but after applying the workaround architecture refuses to load, not letting me play anyway.
[latest.log](https://github.com/embeddedt/ModernFix/files/10885718/latest.log)

**Comment by embeddedt** [comment]
Try without Performant installed.

**Comment by hankjelino** [comment]
Yup, it works now. Thanks for the quick help.

**Comment by Kasualix** [comment]
Oh, betterfpsdist is really a demon.

**Comment by embeddedt** [comment]
The next version of ModernFix will work fine with LWJGL 3.3 for anyone who happens to select it.
