### ISSUE TITLE
[1.19.2][Forge] Missing textures with Modern Train Parts w/ Dynamic Resources

### ISSUE THREAD

**Issue by kawaiicakes** [embeddedt/ModernFix#281]
**Minecraft 1.19.2, Forge 43.2.14**
**ModernFix 5.8.1**
**Modern Train Parts 0.2.2**

Enabling Dynamic Resources causes textures on the shipping containers to be missing. I've noticed this on the red container specifically. Probably happens with the other colours. 

I will be reporting this to the Create: Modern Train Parts devs as well.

**Comment by embeddedt** [comment]
Fixed in 5.9.1. It was a ModernFix issue.
