### ISSUE TITLE
Question - Do I need Async Loader if using this mod?

### ISSUE THREAD

**Issue by P3rf3ctXZer0** [embeddedt/ModernFix#285]
Self Titled

**Comment by embeddedt** [comment]
Not sure what mod "Async Loader" is.

**Comment by P3rf3ctXZer0** [comment]
Sorry dyslexia async-locator-forge-1.20-1.3.0.jar https://www.curseforge.com/minecraft/mc-mods/async-locator

**Comment by embeddedt** [comment]
ModernFix does not replace that mod on any version the original exists on. The feature only exists in the 1.16 version since Async Locator isn't available there.
