### ISSUE TITLE
crash with mekanism and mixin.perf.dynamic_resources=true

### ISSUE THREAD

**Issue by mllightitup** [embeddedt/ModernFix#289]
If there are wires from the mekanism near you, it crashes (With mixin.perf.dynamic_resources=true enabled).
This seemed to start happening after the update from 5.9.0 to 5.9.1

I use the enigmatica 6 expert modpack (1.16.5)

[crash-2023-11-07_21.10.44-client.txt](https://github.com/embeddedt/ModernFix/files/13284485/crash-2023-11-07_21.10.44-client.txt)

**Comment by embeddedt** [comment]
Can you provide steps to reproduce this with just Mekanism & ModernFix installed (i.e. which blocks to place, or search for in the creative inventory)?

**Comment by mllightitup** [comment]
> Can you provide steps to reproduce this with just Mekanism & ModernFix installed (i.e. which blocks to place, or search for in the creative inventory)?

I'm not sure if this only happens with mekanism and modernfix and not in the modpack. I will test this.

In my case the energy cell(basic) from powah and a couple of mechanisms(fluid encapsulator, pyrolyzer and similar) from thermal series were connected to each other with wires from mekanism (basic universal cable)

I will also double-check if the previous version of modernfix works or not in my case

**Comment by mllightitup** [comment]
steps to reproduce(clean new instance):
https://www.youtube.com/watch?v=2IvcdInTrhc

https://github.com/embeddedt/ModernFix/assets/43480503/c41332bc-ef3d-4137-8463-1818c518e64e

[crash-2023-11-07_23.19.17-client.txt](https://github.com/embeddedt/ModernFix/files/13288738/crash-2023-11-07_23.19.17-client.txt)

full log:
https://mclo.gs/z7IdfFg

**Comment by embeddedt** [comment]
Thanks for the video! The issue was fairly simple to fix and I am releasing 5.9.2 now.
