### ISSUE TITLE
[Bug] Stuck when entering the world.

### ISSUE THREAD

**Issue by wasdspace** [embeddedt/ModernFix#29]
modernfix: 1.9.0-2-g84ba47f

[latest.log](https://github.com/embeddedt/ModernFix/files/10887641/latest.log)
Infinite freeze, no crash.

**Comment by Kasualix** [comment]
去Dungeons Libraries的配置文件里把Enable Elite Mobs选项关掉，那玩意兼容老烂了，非常容易出问题。

**Comment by wasdspace** [comment]
不行呀，一样进不去。
Same result, sry.

**Comment by Kasualix** [comment]
再来点日志嘛
log pls

**Comment by wasdspace** [comment]
Dungeon Suites 都移除了：
Dungeon Suites have been all removed:
[debug.log](https://github.com/embeddedt/ModernFix/files/10888020/debug.log)
[latest.log](https://github.com/embeddedt/ModernFix/files/10888021/latest.log)

**Comment by embeddedt** [comment]
I think this is a conflict with Roadrunner. I will add a fix.

**Comment by embeddedt** [comment]
Please try again with the latest commit.

**Comment by wasdspace** [comment]
Works perfectly! Thank you so much!
