### ISSUE TITLE
[Question] Compability with memory leak fix? 

### ISSUE THREAD

**Issue by Rad586** [embeddedt/ModernFix#290]
`mixin.bugfix.buffer_builder_leak` and https://github.com/FxMorin/MemoryLeakFix/blob/1.19/src/main/java/ca/fxco/memoryleakfix/mixin/customPayloadLeak/MinecraftClient_freeBufferMixin.java
`mixin.perf.remove_biome_temperature_cache` and https://github.com/FxMorin/MemoryLeakFix/blob/1.19/src/main/java/ca/fxco/memoryleakfix/mixin/biomeTemperatureLeak/Biome_threadLocalMixin.java
` mixin.perf.compact_bit_storage` and https://github.com/FxMorin/MemoryLeakFix/blob/1.19/src/main/java/ca/fxco/memoryleakfix/mixin/spongePoweredLeak/Main_clientLoadedMixin.java

**Comment by Rad233** [comment]
Seems that `mixin.perf.remove_biome_temperature_cache` is already been implemented in https://github.com/FxMorin/MemoryLeakFix/blob/1.19/src/main/java/ca/fxco/memoryleakfix/mixin/biomeTemperatureLeak/Biome_threadLocalMixin.java

**Comment by Rad586** [comment]
Not sure if there's more. https://github.com/fxmorin/MemoryLeakFix/wiki/Current-Fixes#both
Is it really necessary to use memory leak fix mod if one already installed modernfix?

**Comment by embeddedt** [comment]
The only patch that these mods have in common is `remove_biome_temperature_cache`, and it is generally harmless to have multiple versions of that patch applied. The other two patches are not the same.

As for the other fixes, it depends on whether your mods are affected by these memory leaks. Personally, I have never needed that mod, but your mileage may vary.
