### ISSUE TITLE
[Question] Enhanced Block Entities and dynamic resources

### ISSUE THREAD

**Issue by Rad586** [embeddedt/ModernFix#291]
So I noticed that Enhanced Block Entities did some changes in model bakery(https://github.com/FoundationGames/EnhancedBlockEntities/blob/1.19/src/main/java/foundationgames/enhancedblockentities/client/model/DynamicBakedModel.java). 
However, unlike #107 , in 1.19.2 fabric, they somehow work together without visual glitches. 
I was wondering if using them together results in even better performance?

**Comment by embeddedt** [comment]
I believe the "DynamicBakedModel" EBE uses is only for its own purposes of replacing the chest, etc. renderers, and does not apply to other models.

> I was wondering if using them together results in even better performance?

As long as it works, yes, because ModernFix currently makes no optimizations to chests by itself.
