### ISSUE TITLE
[1.16.5Forge] Async Locator works wrong with explorer map

### ISSUE THREAD

**Issue by GoldenTotem** [embeddedt/ModernFix#292]
Minecraft 1.16.5  Forge 36.2.35  Modernfix 5.9.2

1. Get a explorer map
    1.1 Use loot table function "minecraft:exploration_map" to a map. I have made a very simple datapack which contain a mansion 
          explorer map  [Test.zip](https://github.com/embeddedt/ModernFix/files/13320618/Test.zip)
    1.2 Install the datapack and /reload
    1.3 Use command /loot give @s loot aaa:b
2. The map will be broken and always "working"
3. If you use /setblock ~ ~ ~ chest{LootTable:"aaa:b"} , map will be generated correctly in the chest, but if you break the chest before generating the loot table, map will still get broken.

I have seen #241 and [10](https://github.com/thebrightspark/AsyncLocator/issues/10), maybe these two are the same problem. But it still occurs in the latest version, I just want to know whether the problem is truly fixed and which version fix the problem. If the problem is not fixed, what can I do now.   :)

**Comment by embeddedt** [comment]
It sounds like the same bug as upstream Async Locator: https://github.com/thebrightspark/AsyncLocator/issues/10, which has not been fixed.

As a workaround, you can disable this patch by adding `mixin.perf.async_locator=false` to `config/modernfix-mixins.properties`.
