### ISSUE TITLE
1.20.1 Forge Server Crash

### ISSUE THREAD

**Issue by Primia** [embeddedt/ModernFix#294]
ModernFix Version: 5.9.2+mc1.20.1
Crashlog: https://mclo.gs/WdNoGZv

**Comment by embeddedt** [comment]
I am pretty sure this crash is not caused by ModernFix, it doesn't modify the relevant parts of the game code. One of your mods is most likely manipulating the list of loaded chunks on the wrong thread, unfortunately, the log does not say which one.
