### ISSUE TITLE
[1.20.1] [5.9.2] Suspicious async chunkload

### ISSUE THREAD

**Issue by DankestO** [embeddedt/ModernFix#295]
I have been receiving an incredible amount of spam on my server, I really don't know what to do, it's frustrating.
`Suspicious async chunkload, pass -Dmodernfix.debugBadChunkloading=true for more details`
Constantly.
I tried to do what it tells me, but once I put "-Dmodernfix.debugBadChunkloading=true" in "modernfix-mixins.properties" it disappears from properties. and it keeps constantly sending me that spam to the point of lagging the entire server without me being able to do anything.
I imagine I'm doing something wrong?

**Comment by embeddedt** [comment]
Please send the `latest.log` file.

**Comment by DankestO** [comment]
[latest.log](https://github.com/embeddedt/ModernFix/files/13326566/latest.log)

**Comment by embeddedt** [comment]
Try adding `-Dmodernfix.debugBadChunkloading=true` to the JVM arguments and send the new log

**Comment by DankestO** [comment]
So that's where I should have put it, that was wrong xD
[latest.log](https://github.com/embeddedt/ModernFix/files/13326622/latest.log)

**Comment by embeddedt** [comment]
It seems that Map Atlases updates its maps by loading chunks on a worker thread. This is unusual for a mod to do, but doesn't appear to be causing server freezes, so the log message from ModernFix can be safely ignored in this case. I may remove that message and only print something in the log if the server has actually frozen for an extended period of time.

**Comment by DankestO** [comment]
Well, the server usually drops messages like:
"I can't keep up! Is the server overloaded? It's running at 10010 ms or 200 ticks behind"
after every certain message from Modernfix, and the game takes a while to open chests and react to everything.

It's strange that it only happens in certain places on the map, I don't understand why, I just know that as soon as Modernfix starts to constantly warn me about it, the lag starts, I think that before it didn't happen only with Map Atlases, but I didn't explore much enough to discover that, I really don't know about all this.

**Comment by DankestO** [comment]
Ok, it didn't occur to me to try it without Modernfix xD
It seems that lag does not appear in the areas where it should appear. So it is likely that it is the Modernfix logs that are causing me this problem with the slowness of the server.

**Comment by embeddedt** [comment]
I have removed that log message in the beta - https://nightly.link/embeddedt/ModernFix/workflows/gradle/1.20/Package.zip
Can you see if the lag is gone?

Note that you should also remove `-Dmodernfix.debugBadChunkloading=true` from the JVM arguments, as it will slow down the game if present.

**Comment by DankestO** [comment]
I just tried it, and yup, I no longer notice any slowness on the server, thank you very much for this quick fix :D!
