### ISSUE TITLE
[1.16.5] Blast search trees make tag searching unavailable in creative inventory

### ISSUE THREAD

**Issue by GoldenTotem** [embeddedt/ModernFix#298]
Minecraft 1.16.5  Forge 36.2.35  Modernfix 5.9.2  JEI 7.8.0.1009

1. Typing "#minecraft:saplings" in creative search, then all saplings will be searched.
2. Turn on blast search trees, typing "#minecraft:saplings" in creative search will search nothing.
3. Delete namespace "minecraft", then saplings will occur again.

Blast search trees will exclude namespace in item tags. If you use "#sand", both "#minecraft:sand" and "forge:sand" will be given and you cannot choose one of them.

**Comment by embeddedt** [comment]
Thanks for the report. It's a limitation of JEI's tag searching feature, and can't be easily fixed on ModernFix's end. Disabling the option is the best workaround if you require the ability to choose a specific namespace. I added a note to the FAQ.
