### ISSUE TITLE
[Bug] Astral Sorcery causes huge texture atlas to be generated

### ISSUE THREAD

**Issue by wasdspace** [embeddedt/ModernFix#3]
forge: 36.2.39
modernfix: 1.2.0

Shadow:
![2023-01-05_18 55 43](https://user-images.githubusercontent.com/85009668/210765659-7b98ecc8-7a70-4521-9e5c-b77e112d4005.png)

Faint Amaranth in Astral Sorcery:
![2023-01-05_18 55 51](https://user-images.githubusercontent.com/85009668/210765977-c3ee3051-11c8-4efa-8970-b4434e9c5449.png)

Water and Lantern:
![2023-01-05_18 56 15](https://user-images.githubusercontent.com/85009668/210766129-1587709b-1c41-4a06-87c4-c4847366c5b2.png)

Torch:
![2023-01-05_18 56 43](https://user-images.githubusercontent.com/85009668/210766193-59344639-367f-4cc6-be37-7f5214100d9c.png)

Campfire:
![2023-01-05_18 56 47](https://user-images.githubusercontent.com/85009668/210766304-9619fe67-ebef-4ddb-bf2b-b7bd07f5663c.png)

Seagrass:
![2023-01-05_18 57 02](https://user-images.githubusercontent.com/85009668/210766378-78d0b233-0cb3-44e4-950f-fdfb833e603a.png)

Although they may not be useful, there are: 
[latest.log](https://github.com/embeddedt/ModernFix/files/10351590/latest.log)
[debug.log](https://github.com/embeddedt/ModernFix/files/10351591/debug.log)

**Comment by embeddedt** [comment]
Thank you! This version should hopefully fix the issues.

[newversion.zip](https://github.com/embeddedt/ModernFix/files/10353803/newversion.zip)

**Comment by wasdspace** [comment]
It works! Thank you!
