### ISSUE TITLE
Alex's Mobs texture bug relation (maybe)

### ISSUE THREAD

**Issue by Vinzound** [embeddedt/ModernFix#304]
https://github.com/AlexModGuy/AlexsMobs/issues/1857

A few weeks ago I reported a bug in Alex Mob's that causes a texture of a mob from that mod to not be processed correctly. With an evaluation, I was able to realize that it only happens when I have ModernFix activated. 

I don't know what interaction that visual bug could have with this mod :(

**Comment by embeddedt** [comment]
Please send your `logs/latest.log` file.

**Comment by Vinzound** [comment]
[latest.log](https://github.com/embeddedt/ModernFix/files/13445852/latest.log)

**Comment by embeddedt** [comment]
The latest beta should fix this (link is in the README). I will make a new release soon.

**Comment by Vinzound** [comment]
I have tested the most recent beta and it is now fixed, thanks! :)

Do you recommend I use the beta for the meantime, or should I wait for its release?

**Comment by embeddedt** [comment]
You can use the beta for the time being; it should be stable.

**Comment by embeddedt** [comment]
Fixed in 5.10.0.
