### ISSUE TITLE
ModernFix removes EverlastingAbilities' search ability

### ISSUE THREAD

**Issue by WordStormRose** [embeddedt/ModernFix#306]
I'm a modpack developer, and I just stumbled upon this problem and I cannot for the life of me figure it out. The mod Everlasting Abilities usually allows players to search in creative mode for specific ability totems, but in combination of ModernFix that feature is broken, making it so that only one totem shows up when searched. So far in survival worlds it's been Speed 1 and in creative worlds it's been Absorption 1. I've narrowed it down to ModernFix specifically in the context of my pack (Duad Beruzhaldan), but having only Everlasting Abilities, ModernFix, and the respective requirements/strong recommendations in a profile doesn't reproduce the problem. Everything's worked fine with Everlasting Abilities until I added ModernFix, so I know none of the other mods in my pack are a problem.
I'm going to keep trying to figure this out, but I'm utterly baffled and if there's any way that you guys can help that would be wonderful. The developers of Everlasting Abilities had nothing helpful to say when I submitted the issue report to them.

Steps to reproduce the problem:

    Load versions 1.2.81 or 1.2.82 of the modpack Duad Beruzhaldan. ModernFix was added in 1.2.81.
    Load the game and go into creative or otherwise search for 'ability totem'.

Expected behaviour:

Usually I'm able to search and select specific totems to use at the start of a game (often for roleplaying a character but usually because I'm quite fond of step assist). Usually, when I search 'ability totem' (or just 'ability') a selection of all available totems appears in the creative menu, and when I search for a specific one - ie step assist - it shows up.

Versions:

    Everlasting Abilities: 1.8.2
    ModernFix: 5.9.3
    Minecraft: 1.18.2
    Forge: 40.2.10

**Comment by embeddedt** [comment]
If they rely specifically on mechanics of creative search, and you have JEI installed, it is probably https://github.com/embeddedt/ModernFix/wiki/General-FAQ#why-does-tag-searching-in-creative-behave-differently.

**Comment by WordStormRose** [comment]
The same thing happens when I search in JEI; only one totem shows up (Absorbtion 1 for creative worlds and Speed 1 for survival worlds). I've looked back at my other bug report, and the EverlastingAbilities devs said that it might have something to do with nbt tags, which is what determines what ability each totem has.

**Comment by embeddedt** [comment]
You should try disabling `mixin.perf.blast_search_trees` then if you want vanilla's creative search functionality to be used in the creative inventory. By default ModernFix applies JEI searching to the creative inventory.

**Comment by WordStormRose** [comment]
How do I do that?

**Comment by embeddedt** [comment]
Edit `config/modernfix-mixins.properties` and add `mixin.perf.blast_search_trees=false` at the bottom

**Comment by embeddedt** [comment]
Or, you can search for ModernFix in Forge's mod list and use the config GUI. Note that you need to restart the game after changing ModernFix options.

**Comment by WordStormRose** [comment]
That worked, thank you!!!
