### ISSUE TITLE
strange noise

### ISSUE THREAD

**Issue by SHADOWBOY8432** [embeddedt/ModernFix#307]
after i installed the mod the far textures (about 5 blocks away from the player) have noisy blury textures like i see some strange particles on wood logs and grass please fix or if there an option for that in the config tell me so i disable it

**Comment by embeddedt** [comment]
There isn't enough information to action this issue. What Minecraft version & modloader are you using? Are you testing with ModernFix alone or with other mods installed?

**Comment by SHADOWBOY8432** [comment]
Forge 1.20.1On 27 Nov 2023 12:20 am, embeddedt ***@***.***> wrote:
There isn't enough information to action this issue. What Minecraft version & modloader are you using? Are you testing with ModernFix alone or with other mods installed?

**Comment by embeddedt** [comment]
> Are you testing with ModernFix alone or with other mods installed?

This is an important question.
