### ISSUE TITLE
Tiny Potato model buggy when Dynamic Resources enabled

### ISSUE THREAD

**Issue by anoomolu** [embeddedt/ModernFix#308]
Hiya, I think this got lost in the discord channel.

Enabling dynamic resources (Modernfix 5.9.3) on both Forge and Fabric 1.20.1 with Botania installed causes the Tiny Potato model to look weird.

![image](https://github.com/embeddedt/ModernFix/assets/77850233/c99e9907-f667-4f76-9ab8-57ee6ed8a19a)

The error in question: [Render thread/WARN] [minecraft/ModelBakery]: Unable to load model: 'botania:tiny_potato/' referenced from: botania:tiny_potato/: java.io.FileNotFoundException: botania:models/tiny_potato/.json.

It works fine with dynresources disabled.

**Comment by embeddedt** [comment]
Thanks for the report; should be fixed in 5.10.0.
