### ISSUE TITLE
Ensure Lightspeed compatibility

### ISSUE THREAD

**Issue by Cixon** [embeddedt/ModernFix#31]
Heya embeddedt!
Is there anyway you can disable mixin-injections/client start-up changes in the event it detects[ Lightspeed ](https://www.curseforge.com/minecraft/mc-mods/lightspeedmod)mod?
I really enjoy lightspeed and it's a fair-bit faster on my system compared to Modernfix. I'd love if you could please disable only your client-startup modifications in favor of Lightspeed mod's modifications. Thanks!

**Comment by Cixon** [comment]
here's the log btw in-case you're interested as to what happens if both mods are installed:

[latest.log](https://github.com/embeddedt/ModernFix/files/10891494/latest.log)

**Comment by embeddedt** [comment]
I will not be supporting Lightspeed, as it is both closed-source and obfuscated, making it near-impossible to know exactly what it patches. I'd like to encourage players to use open-source performance mods, as they are generally easier for modders to add support for and lend to a more collaborative community. If/when Lightspeed becomes open-source in the future then I will consider adding support on my end.

**Comment by Vaelzan** [comment]
FYI - the developer of Lightspeed mentioned in the comments section on CurseForge that they will be releasing the source code soon. It might be worth revisiting the policy if they do.

**Comment by embeddedt** [comment]
It will depend on the license they use for the code.

**Comment by Kasualix** [comment]
it's open source with GNU LESSER GENERAL PUBLIC LICENSE now!
https://github.com/CCr4ft3r/lightspeed

**Comment by Cixon** [comment]
![Screenshot (237)](https://user-images.githubusercontent.com/69068153/224496199-4ddcee52-44de-40f4-ab41-939f34925a09.png)

Wow! You guys are on it; Thank you embedded for honoring Lightspeed compatibility, I respect this a lot!

**Comment by embeddedt** [comment]
@Cixon I checked and Lightspeed 1.0.0 and ModernFix seem to launch fine together in StoneBlock 3. Is there anything else I need to do from my end?

**Comment by Cixon** [comment]
> disable only your client-startup modifications in favor of Lightspeed mod's modifications. 

This comment is irrelevant currently because I honestly had a issue first pairing Modernfix with Lightspeed but with the new updates between the two, this client startup failure seizes to exist now which is great. Went from 244 seconds to 112 seconds using [Legacy modpack](https://www.curseforge.com/minecraft/modpacks/legacy-forge)

> @Cixon I checked and Lightspeed 1.0.0 and ModernFix seem to launch fine together in StoneBlock 3. Is there anything else I need to do from my end?

Nope! As of right now everything appears to be in working order. If any bug occurs in the future I'll send over to your radar!
