### ISSUE TITLE
Server Freeze during World Pre-generation with ModernFix 5.10.0 on Minecraft Forge 1.19.2 (on a BIG modpack)

### ISSUE THREAD

**Issue by YannD-Deltagon** [embeddedt/ModernFix#311]
I'm encountering a server freeze issue when using ModernFix version 5.10.0 with Minecraft Forge version 1.19.2 (forge 1.19.2-43.3.5) and Java JDK-21 on a dedicated Windows 11 64-bit server. 
The issue occurs during the world pre-generation process.

## Modpack
I am using a large modpack : [LMP](https://legacy.curseforge.com/minecraft/modpacks/lmp)

## Server Setup
- **OS:** Windows 11 64-bit
- **Java Version:** JDK-21
- **Batch File Configuration:
```
set JAVA_MCSS="C:\Program Files\Java\jdk-21\bin\java.exe"
%JAVA_MCSS% @user_jvm_args.txt @libraries/net/minecraftforge/forge/1.19.2-43.3.5/win_args.txt nogui %*
```
- **JVM Arguments (`user_jvm_args.txt`):**
```
-Xms4G
-Xmx12G
-XX:+UseG1GC
-XX:+ParallelRefProcEnabled
-XX:MaxGCPauseMillis=200
-XX:+UnlockExperimentalVMOptions
-XX:+DisableExplicitGC
-XX:+AlwaysPreTouch
-XX:G1NewSizePercent=30
-XX:G1MaxNewSizePercent=40
-XX:G1HeapRegionSize=8M
-XX:G1ReservePercent=20
-XX:G1HeapWastePercent=5
-XX:G1MixedGCCountTarget=4
-XX:InitiatingHeapOccupancyPercent=15
-XX:G1MixedGCLiveThresholdPercent=90
-XX:G1RSetUpdatingPauseTimePercent=5
-XX:SurvivorRatio=32
-XX:+PerfDisableSharedMem
-XX:MaxTenuringThreshold=1
-Dusing.aikars.flags=https://mcflags.emc.gs/
-Daikars.new.flags=true
```

## Issue
The server freezes without any error messages or logs when I execute the `/pregen start gen radius Test SQUARE 0 0 300 minecraft:overworld FAST_CHECK_GEN` command.
There is no crash, but the server becomes unresponsive.
Players can move within already loaded chunks, but this is only due to their local cache; they cannot interact with anything in the game world.
Server logs show that the pre-generation process has frozen, but there are no error messages or any additional information.
The same is observed in log4j logs.
Memory dumps do not reveal any apparent issues causing the freeze.

## Troubleshooting Steps
- Attempted to diagnose with Log4j configurations.
- Memory dumps were attempted without success.
- Disabled mods in batches of 15 to isolate the problem.
- Identified that disabling ModernFix seems to resolve the issue.

## Comparison with Previous Version
The issue does not occur with ModernFix version 5.9.3 under the same conditions.

**Comment by YannD-Deltagon** [comment]
Nope, close, is not this mods, sorry :D 
Lezgo disabled mods in batches of 5

**Comment by YannD-Deltagon** [comment]
Actually, it seems that the issue does indeed originate from ModernFix on a dedicated server
However, even the older versions are not functioning properly

**Comment by embeddedt** [comment]
Please enable `mixin.feature.spam_thread_dump` in the ModernFix config, reproduce the issue, wait a minute after the server freezes, and then send the `latest.log` file.

**Comment by YannD-Deltagon** [comment]
I've followed your instructions and enabled mixin.feature.spam_thread_dump in the ModernFix config
The server doesn't crash or freez now... 
Instead, ModernFix seems to be detecting errors and creating dumps effectively. Despite these detected errors and the creation of dumps, the pre-generation process with Chunky continues to advance
[latest.log](https://github.com/embeddedt/ModernFix/files/13600169/latest.log)

**Comment by embeddedt** [comment]
The only thing `mixin.feature.spam_thread_dump` does is create some more lag on the server from having to dump all that information :laughing:, so it sounds like it might be a timing bug in another mod, not ModernFix.

**Comment by YannD-Deltagon** [comment]
Ok, good, I'll keep it active. Maybe after a reboot or something, as I'm at 98% of my map generation, so I guess I'll close this.
Thanks for the help, and I'll activate it again if I encounter the issue again to find the problematic mod

By the way, great mods, this feature is really useful ;)
