### ISSUE TITLE
Water is missing on multiplayer servers

### ISSUE THREAD

**Issue by road2react** [embeddedt/ModernFix#312]
1.20.2 with mod version 5.10.10

To reproduce:
- Log into bedwarspractice.club
- Go forwards and slightly left

![image](https://github.com/embeddedt/ModernFix/assets/93143714/043208a8-3286-4130-a675-4227548f2b87)

With ModernFix installed, the water in this image will be missing, and will not slow down player movement

Might be similar to #222 

Surprisingly, the issue is gone if I join a singleplayer world (water works in singleplayer). After I join and log out, water in multiplayer servers works as expected.

**Comment by embeddedt** [comment]
Please provide a `latest.log` file.

**Comment by embeddedt** [comment]
I made a change in 5.10.1 that will probably fix this issue.
