### ISSUE TITLE
When installing Gregtech Modern and enabling dynamic resource loading simultaneously, it can cause surface mineral particles to lose their texture

### ISSUE THREAD

**Issue by Sovina1991** [embeddedt/ModernFix#313]
When installing Gregtech Modern and enabling dynamic resource loading simultaneously, it can cause surface mineral particles to lose their texture

**Comment by Sovina1991** [comment]
![1702025601_479060_wuQI](https://github.com/embeddedt/ModernFix/assets/47661362/61be88b1-2780-4f18-b7b2-ee9ff9fcc28f)

**Comment by embeddedt** [comment]
I can't reproduce this with the garnet sand indicator in a standalone instance with GTCEu + ModernFix (dynamic resources on) + Embeddium. Appears to work fine.

![2023-12-19_11 17 59](https://github.com/embeddedt/ModernFix/assets/42941056/fa9ab7f2-2d1a-4ea8-bc66-e04abc61371a)
