### ISSUE TITLE
[1.16] Fix Sophisticated Backpacks CME

### ISSUE THREAD

**Issue by Kasualix** [embeddedt/ModernFix#314]
Add [this mixin](https://github.com/MCTeamPotato/SophisticatedBackpacksCMECrashFix/blob/1165/src/main/java/com/teampotato/sbcmefix/mixin/BackpackShapesMixin.java) to resolve the [CME](https://github.com/P3pp3rF1y/SophisticatedBackpacks/issues/775) crash on sophisticated backpacks placing.

**Comment by embeddedt** [comment]
Added in 5.10.1.
