### ISSUE TITLE
Remove MixinExtras

### ISSUE THREAD

**Issue by Madis0** [embeddedt/ModernFix#315]
I suggest removing MixinExtras from the JAR and depending on Fabric Loader 0.15.0 instead, as it already contains it. 

I made this an issue instead of a PR though because I'm not fully sure about your build process and on which versions of Minecraft would you want to do the change (1.20+? 1.20.2+? 1.19+?).

**Comment by embeddedt** [comment]
I will do this for 1.20.4+, to be consistent with what I did for the NeoForge module.

**Comment by embeddedt** [comment]
MixinExtras is not shipped in builds for Minecraft 1.20.4 and newer as of 5.10.1.
