### ISSUE TITLE
Conflict with Smooth Boot Reloaded

### ISSUE THREAD

**Issue by 1936268516** [embeddedt/ModernFix#317]
It crashes when it loads.
[crash-2023-12-11_17.51.10-client.txt](https://github.com/embeddedt/ModernFix/files/13633719/crash-2023-12-11_17.51.10-client.txt)

**Comment by 1936268516** [comment]
I'm using AI to check the crash log and say: (It looks like you're having some problems running Minecraft, and the stack trace is showing a java.util.ConcurrentModificationException. this exception usually occurs in a multi-threaded environment, when one thread is traversing a collection, and another thread tries to modify the structure of the collection (for example, by adding or removing elements), which raises the exception).

**Comment by embeddedt** [comment]
I don't think this can be caused by ModernFix. It appears one of your other mods is modifying the list of resource packs during resource reloading. Unfortunately, the crash log doesn't say which mod.
