### ISSUE TITLE
[1.18.2] Dynamic resources causes CTM glass to disappear

### ISSUE THREAD

**Issue by ghost** [embeddedt/ModernFix#318]
steps:

1. Install only [CTM v1.1.5+5] and [ModernFix v5.10.0].
2. Modify file [modernfix-mixins.properties] to make dynamic resources effective.
3. Load CTM texture pack with any connected glass panel texture. (For example, [MC Connected CTM] or [Better Clear Glass Bordered])
4. See error : Start the game, place some glass panels, the texture of the glass panel has disappeared.

**Comment by embeddedt** [comment]
Fixed in 5.11.0.
