### ISSUE TITLE
Crash with More Culling on 5.10.1

### ISSUE THREAD

**Issue by lostopkk** [embeddedt/ModernFix#319]
https://mclo.gs/otL1kyU

It doesn't crash if you go back to the previous version

**Comment by embeddedt** [comment]
Crash appears to be happening in code from More Culling.

**Comment by bons66** [comment]
Same issue. Previous version work fine. MC 1.21.1 + Fabric 0.15.1
[crash-2023-12-12_10.48.24-client.txt](https://github.com/embeddedt/ModernFix/files/13645213/crash-2023-12-12_10.48.24-client.txt)
[latest.log](https://github.com/embeddedt/ModernFix/files/13645215/latest.log)

When I disable Continuity (More Culling present in my modpack.) - game is loading. 
[latest.log](https://github.com/embeddedt/ModernFix/files/13645269/latest.log)
When I disable More Culling (and enable Continuity) - game is loading.
[latest.log](https://github.com/embeddedt/ModernFix/files/13645313/latest.log)

**Comment by embeddedt** [comment]
This crash is occurring in More Culling's code; I do not see a way to fix it on my end.
