### ISSUE TITLE
[1.20.4] Game crash with Neoforge-20.4.20-beta

### ISSUE THREAD

**Issue by Enderman112** [embeddedt/ModernFix#320]
Game crashes after start
Game launches normally with Neoforge-20.4.12-beta
Modernfix version:modernfix-neoforge-5.10.1+mc1.20.4.jar
[crash-2023-12-12_22.19.41-fml.txt](https://github.com/embeddedt/ModernFix/files/13649227/crash-2023-12-12_22.19.41-fml.txt)

**Comment by embeddedt** [comment]
Thanks. It's caused by this NeoForge release being stricter about how events are registered; I will fix it when I have a chance (probably tonight or tomorrow).

**Comment by Enderman112** [comment]
Okay, thanks.

**Comment by embeddedt** [comment]
Should be fixed in 5.10.2.
