### ISSUE TITLE
modernfix5.10.1 Mixin.perf.clear_fabric_mapping_tables is not found in config/modernfix-mixins.properties.

### ISSUE THREAD

**Issue by BlackRiceXY** [embeddedt/ModernFix#325]

**Comment by embeddedt** [comment]
Please provide more info (e.g. Minecraft version, modloader). The option only exists when using Fabric.

**Comment by BlackRiceXY** [comment]
I apologize, I only remembered to follow the steps to implement the Ultra-Low Memory Footprint and forgot that I was forge
