### ISSUE TITLE
Description: Rendering overlay  net.minecraftforge.fml.ModLoadingException: AstikorCarts (astikorcarts) encountered an error during the enqueue_imc event phase §7java.lang.IllegalStateException: Rendersystem called from wrong thread

### ISSUE THREAD

**Issue by JuddJohnsonIV** [embeddedt/ModernFix#33]
Description: Rendering overlay

net.minecraftforge.fml.ModLoadingException: AstikorCarts (astikorcarts) encountered an error during the enqueue_imc event phase
§7java.lang.IllegalStateException: Rendersystem called from wrong thread

Latest: https://pastebin.com/0GHZB1MF Spam hell was cut to max size
Crash Report: https://pastebin.com/ex8AvGih

**Comment by embeddedt** [comment]
For now you can use `mixin.perf.fast_baking=false` as a workaround (add it to the `modernfix-mixins.properties` file). I will fix this in the next release.

**Comment by embeddedt** [comment]
Should be fixed in 3.1.0.
