### ISSUE TITLE
crafting Items using REI's Move Items method on the crafting table that comes with a traveler's backpack causes the world to freeze

### ISSUE THREAD

**Issue by wumengzhixing** [embeddedt/ModernFix#335]
Version：1.18.2
ModernFix：modernfix-forge-5.11.1+mc1.18.2.jar
Forge：40.2.10
REI：RoughlyEnoughItems-8.3.681-forge.jar
Traveler's Backpack：TravelersBackpack-1.18.2-7.1.46.jar
My friend, can you help me with this problem?
[Error reporting-2023-12-28_22.25.19.zip](https://github.com/embeddedt/ModernFix/files/13787790/Error.reporting-2023-12-28_22.25.19.zip)

**Comment by embeddedt** [comment]
Does your backpack contain a lot of items? The log shows that all the time is being spent in ModernFix's data copying code, but it should be just as fast as vanilla, so I suspect the problem is just that the backpack is too complex.

**Comment by wumengzhixing** [comment]
> Does your backpack contain a lot of items? The log shows that all the time is being spent in ModernFix's data copying code, but it should be just as fast as vanilla, so I suspect the problem is just that the backpack is too complex.

No, if I remember correctly, I only had about seven items in my backpack

**Comment by embeddedt** [comment]
I tried what you described and was able to reproduce the issue, but it happens without ModernFix installed too. So it is a bug in either REI or Traveler's Backpack.

**Comment by wumengzhixing** [comment]
> I tried what you described and was able to reproduce the issue, but it happens without ModernFix installed too. So it is a bug in either REI or Traveler's Backpack.
Well, I saw an error message from ModernFix and thought it was a ModernFix problem, sorry to bother you

**Comment by embeddedt** [comment]
No problem. ModernFix was just notifying you that the server froze. :laughing:
