### ISSUE TITLE
[Forge 1.20.1]: Crash when it started raining possible conflict with Biome Particle Weather

### ISSUE THREAD

**Issue by Gamerbolts** [embeddedt/ModernFix#336]
I have a heavily altered version of ATM9. I was running my game and it was fine then it started to rain. My crash log says between ModernFix and Biome Particle Weather, so I have posted to both githubs.

Here is my crashlog
[crash-2023-12-28_13.27.13-client.txt](https://github.com/embeddedt/ModernFix/files/13788993/crash-2023-12-28_13.27.13-client.txt)

And my Latest log
[latest.log](https://github.com/embeddedt/ModernFix/files/13788995/latest.log)

**Comment by embeddedt** [comment]
This is not ModernFix's fault - it just optimizes the code that prints this error, but the exact same failure would occur with the unmodified code.
