### ISSUE TITLE
[1.20.1] Modernfix calling config before mod is loaded

### ISSUE THREAD

**Issue by Reshy** [embeddedt/ModernFix#337]
https://github.com/Cazsius/Spice-of-Life-Carrot-Edition/issues/149#issuecomment-1869865486

https://pastebin.com/Nma141Fd

**Comment by embeddedt** [comment]
Please verify that this issue occurs with only ModernFix and the other mod installed, and send the associated log & crash report.

**Comment by embeddedt** [comment]
I am pretty sure ModernFix is doing nothing wrong here and the other mod's assumption was incorrect.
