### ISSUE TITLE
[Request] Entity Wall Damage Check

### ISSUE THREAD

**Issue by TqLxQuanZ** [embeddedt/ModernFix#339]
Mostly applies to modded entity or enemies that has higher attack range, usually what happens is that the damage dealer and the damage received target has a wall in between, but still able to deal damage regardless bypassing the wall.

Stuff like glass pane has thin collision will have an obvious effect.

This is mainly a request for ModernFix, if it's impossible or doesn't make sense in this mod feel free to close the ticket!

**Comment by embeddedt** [comment]
Thanks for the request. I think I will opt not to include this in ModernFix because it would change gameplay behavior in an obvious manner, and seems like the type of glitch that some farms might be relying on.
