### ISSUE TITLE
[1.18.2] Incompatible with Debugify after ModernFix 5.6.1v

### ISSUE THREAD

**Issue by xSyphel** [embeddedt/ModernFix#340]
Hi, I discovered that when using both [Debugify 1.11.0](https://www.curseforge.com/minecraft/mc-mods/debugify/files/3812301) mod and ModernFix (Any version between: 5.7.0-5.11.1), causes the game to crash with a crash exit code 1 and no proper crash log. 

I'm not sure which mod is at fault. I didn't see this being reported anywhere, but I thought I'd mention this issue.

**Comment by embeddedt** [comment]
This is Debugify's fault and caused by them building the mod incorrectly. See https://github.com/embeddedt/ModernFix/issues/233.
