### ISSUE TITLE
Create bug + ModernFix After the latest updates, the trains no longer run correctly. They now don't travel if they end up in another chunk.

### ISSUE THREAD

**Issue by kitovoi111** [embeddedt/ModernFix#342]
After the latest updates, the trains no longer run correctly. They now don't travel if they end up in another chunk.

**Comment by kitovoi111** [comment]
Forge 1.19.2 version

**Comment by kitovoi111** [comment]
https://youtu.be/89mkWXerP-M

Players complain that when a train enters a new chunk, it lags or does not move at all, and sometimes ceases to be visible.

**Comment by kitovoi111** [comment]
https://github.com/AbdElAziz333/Canary/issues/200

**Comment by embeddedt** [comment]
It's very unlikely that ModernFix is the cause of this, as there aren't any patches that I'd expect to affect train movement and there have not been any reports of such an issue before. Please verify that this occurs in a standalone instance with only ModernFix & Create installed, and provide steps to reproduce.

**Comment by embeddedt** [comment]
Closing as there was no response.
