### ISSUE TITLE
Using dynamic resources on 5.11.1 causes textures to be missing on tubnet.gg

### ISSUE THREAD

**Issue by KingRocco21** [embeddedt/ModernFix#343]
Version: 1.20.1
Mods: Only Mod Menu and ModernFix
Here is an image of the TubNet lobby on 5.11.1:
![2024-01-01_16 07 54](https://github.com/embeddedt/ModernFix/assets/107735070/b4a30b00-35fa-4710-8754-2c08401daf3f)
Here is an image of the TubNet lobby on 5.11.0: 
![2024-01-01_16 09 16](https://github.com/embeddedt/ModernFix/assets/107735070/940d31a3-3b32-4140-bfb3-25ae838d77e5)
Here is a link to the log file for 5.11.1: https://mclo.gs/A1Omcmu

This does not happen with dynamic resources off

**Comment by KingRocco21** [comment]
Here is a link to the log file for 5.11.0: https://mclo.gs/zvFgcv5

**Comment by KingRocco21** [comment]
Btw I'm a community tester for tubnet.gg. Would you like me to ask them to fix their model files, like you mentioned in the commit? If so, give me a full rundown of the issue so I can forward the request.
No guarantees that it will be fixed though, since they probably care more about supporting vanilla than supporting mods.

**Comment by KingRocco21** [comment]
Wow that was unfortunate timing, Tubnet is shutting down on the 12th so you no longer have to worry about it :P

**Comment by embeddedt** [comment]
The underlying issue is fixed in 5.12.0 regardless.
