### ISSUE TITLE
[1.20.4][Neoforge-20.4.76-beta]Game crashes

### ISSUE THREAD

**Issue by Enderman112** [embeddedt/ModernFix#345]
Game crashes after start
Minecraft version:1.20.4
Neoforge version:20.4.76-beta
![图片](https://github.com/embeddedt/ModernFix/assets/75347659/91a39014-633e-435a-97b3-8b35f6c47fcf)
[latest.log](https://github.com/embeddedt/ModernFix/files/13831956/latest.log)
game start normally with Neoforge-20.4.69-beta
Maybe the crash is caused by The Networking Refactor in Neoforge-20.4.70-beta?

**Comment by embeddedt** [comment]
Use https://nightly.link/embeddedt/ModernFix/workflows/gradle/1.20.4/Package.zip until the next release.

**Comment by Enderman112** [comment]
> Use https://nightly.link/embeddedt/ModernFix/workflows/gradle/1.20.4/Package.zip until the next release.

okay,thanks

**Comment by embeddedt** [comment]
Should be fixed in 5.12.0.
