### ISSUE TITLE
[Suggestuion] Allow toggling dymanicCacheGen feature

### ISSUE THREAD

**Issue by AnikeiPS** [embeddedt/ModernFix#346]
After implementing dynamic cache generation (I think [this action](https://github.com/embeddedt/ModernFix/actions/runs/7217070010)) MoreCulling crashes when powering piston (`at net.minecraft.class_4970$class_4971$class_3752.redirect$hlp000$moreculling$customCullingShape(class_4970.java:2406) ~[client-intermediary.jar:?]`). Add toggle to turn off/on this feature in config.

**Comment by embeddedt** [comment]
The MoreCulling crashes are caused by mixins on their end that make too many assumptions, and have been reported to them: https://github.com/FxMorin/MoreCulling/issues/195

Nonetheless, this feature can already be toggled by disabling `mixin.perf.reduce_blockstate_cache_rebuilds`.
