### ISSUE TITLE
Geto NOT working

### ISSUE THREAD

**Issue by Kylo629** [embeddedt/ModernFix#347]
In the mod Jujutsu Craft (Sorcery Fight), Getos and only Getos abilities do not work at all with ModernFix installed. Everything else runs fine but ModernFix completely breaks it for 1.16.5. Please let me know if this fixable.

**Comment by embeddedt** [comment]
As mentioned on Discord, please provide *specific* steps to reproduce this issue, and explain the desired vs current behavior. Otherwise I have to spend a lot of time figuring out how Jujutsu Craft works myself.
