### ISSUE TITLE
Game crashes upon booting up; GregTech is sus

### ISSUE THREAD

**Issue by SirPeteThe1st** [embeddedt/ModernFix#348]
When booting up the game after an update, it crashes upon loading. My crash report is as follows:

https://pastebin.com/4R4ZBqcn

Please advise.

**Comment by embeddedt** [comment]
Please send the `latest.log` file. This crash does not appear related to ModernFix at all.

**Comment by embeddedt** [comment]
Is this still an issue? There is not enough information provided to diagnose the problem.

**Comment by SirPeteThe1st** [comment]
It resolved itself. Game operates just fine. Sorry for your inconvenience.

**Comment by embeddedt** [comment]
:+1:  Great!

**Comment by ChapperNi** [comment]
sorry for posting on a completed issue, but how'd you fix it? im having the exact same problem

**Comment by SirPeteThe1st** [comment]
I just restarted it, and it ran perfectly fine. I know, it's odd.
