### ISSUE TITLE
Crashing in 1.20.4

### ISSUE THREAD

**Issue by gnilobaiter** [embeddedt/ModernFix#349]
Minecraft version: 1.20.4
Fabric version: 0.15.3
ModernFix version: trying on 5.11.1, 5.11.0
Launcher: Modrinth App
PC: RTX 4080 + I7-10700KF + 32 RAM
**Log: https://mclo.gs/Cw2GgZM**

Crashes before the game starts, I only have time to see the log. Without ModernFix all ok.

**Comment by embeddedt** [comment]
Disable `mixin.feature.direct_stack_trace`, it's not enabled by default and the mixin seems to have issues in your instance

**Comment by gnilobaiter** [comment]
[crash-2024-01-09_23.00.44-client.txt](https://github.com/embeddedt/ModernFix/files/13878426/crash-2024-01-09_23.00.44-client.txt)
Now crashing with crash-report

**Comment by gnilobaiter** [comment]
Oh sorry, RTSS crashing. All ok
