### ISSUE TITLE
Textures missing while using modern fix

### ISSUE THREAD

**Issue by NolanHewitt** [embeddedt/ModernFix#350]
<img width="569" alt="Screenshot 2024-01-10 225611" src="https://github.com/embeddedt/ModernFix/assets/52480898/8cde7fd2-5b8c-4e88-aaab-91aa889f5cbb">
<img width="561" alt="Screenshot 2024-01-10 225619" src="https://github.com/embeddedt/ModernFix/assets/52480898/e34aebb1-8343-4b71-b921-4bcda17a8df6">
[latest.log](https://github.com/embeddedt/ModernFix/files/13897532/latest.log)

**Comment by NolanHewitt** [comment]
Only happens with dynamic resources enabled, only seems to effect the vanilla set of tools. Sorry the images are so oversaturated, screenshots with HDR on in opengl games is funky on my PC for some reason

**Comment by Phoenix-Starlight** [comment]
Your resource packs are broken. Also models are missing it seems.

**Comment by embeddedt** [comment]
I suspect it's the same issue as #343. What happens if you use https://nightly.link/embeddedt/ModernFix/workflows/gradle/1.20/Package.zip ?

**Comment by NolanHewitt** [comment]
Looks like its fixed with the newest version. Thank you!

**Comment by embeddedt** [comment]
This should be solved with the latest release(s).
