### ISSUE TITLE
Doesn't load with Embeddium

### ISSUE THREAD

**Issue by om3ga6400** [embeddedt/ModernFix#355]
whenever i have both mods installed it permanently stalls

**Comment by embeddedt** [comment]
Please provide more information.

* What Minecraft version are you using?
* Does this occur with only ModernFix & Embeddium installed? If not, please try to determine what other mods are needed to reproduce the issue.
* Please provide the `latest.log` file when the freeze happens.

**Comment by om3ga6400** [comment]
restarted my pc and it works now wtf

**Comment by om3ga6400** [comment]
sry
