### ISSUE TITLE
[ModernFix integrated server watchdog/ERROR]: A single server tick has taken 40001, more than 40000 milliseconds

### ISSUE THREAD

**Issue by ZeekZodiac** [embeddedt/ModernFix#356]
### Bug Description

Randomly on my world I run into an issue where my world will randomly lag and I have to completely shut it down through task manager to fix it, not sure how its lagging or how to fix, any assistance would be greatly appreciated. 

### Reproduction Steps

Not even sure how to reproduce, its completely random, sometimes I can play for an hour and it doesn't happen or i could play for 5 minutes. 

### Log File

https://mclo.gs/RsDfeZW

**Comment by embeddedt** [comment]
This isn't a ModernFix bug; it just provides extra information as to why the world freezes (compared to vanilla, which tells you nothing). Based on the log, the game is stuck on computing entity collisions, so I'm suspicious there are simply a lot of entities in the world in one location. Unfortunately, I don't know what location that is, or what mod is causing it.
