### ISSUE TITLE
 crash when entering the game

### ISSUE THREAD

**Issue by JohnsonRock3000** [embeddedt/ModernFix#357]
### Bug Description

at the loading stage

### Reproduction Steps

at the loading stage

### Log File

[latest.log](https://github.com/embeddedt/ModernFix/files/14025135/latest.log)

**Comment by embeddedt** [comment]
Another one of your mods is loading Minecraft code too early, there is nothing ModernFix can do to fix that. However, disabling `mixin.perf.thread_priorities` in the config might work around the issue.

**Comment by JohnsonRock3000** [comment]
and how to do it?

**Comment by embeddedt** [comment]
Add `mixin.perf.thread_priorities=false` at the bottom of `config/modernfix-mixins.properties`.

**Comment by JohnsonRock3000** [comment]
When I change it to false and log in, it throws me out, I look in the config, and there it is true again

**Comment by embeddedt** [comment]
Lines starting with `#` are a comment and changing them won't have an effect.

**Comment by JohnsonRock3000** [comment]
and what do I need to change then?
