### ISSUE TITLE
ModernFix causes a crash

### ISSUE THREAD

**Issue by Lithum-12** [embeddedt/ModernFix#359]
### Bug Description

After installing ModernFix, Minecraft won't start.

### Reproduction Steps

MC Version:1.20.2
ModernFix Version : 5.10.1+mc1.20.2
NeoForge Version : 20.2.88
Java Version : jdk-17.0.9
Platform : Windows 11 Pro

### Log File

[latest.log](https://github.com/embeddedt/ModernFix/files/14110628/latest.log)

**Comment by embeddedt** [comment]
1.20.2 is not supported anymore. Please use 1.20.4 or 1.20.1.
