### ISSUE TITLE
1.19.2 - Dedicated Server Fails to Start and Hangs after (Preparing Spawn Area) and Freezes server at 0% With ModernFix Present on Server

### ISSUE THREAD

**Issue by P3rf3ctXZer0** [embeddedt/ModernFix#36]
Latest https://gist.github.com/P3rf3ctXZer0/37f6157ef5db4ecc7716e8f04ea2678b
Debug https://gist.github.com/P3rf3ctXZer0/a4779cc477eb04211e3d7e9395843eb8

**Comment by P3rf3ctXZer0** [comment]
Bump - is this something you care about?

**Comment by embeddedt** [comment]
Please try to reproduce the issue with less mods if possible.

**Comment by P3rf3ctXZer0** [comment]
Still broken 
modernfix-mc1.19.2-3.1.0.jar

**Comment by P3rf3ctXZer0** [comment]
> Please try to reproduce the issue with less mods if possible.

This will not happen unless I need to re-write the modpack which I already did once. I understand needing to do major debugging but I do not have the time. 

I ask you keep this issue open until its fixed or I have time. I will test it every time you release a version. When it works as intended I will close it.

**Comment by Disnejar** [comment]
I had a simmilar issue when I updated to the newest version of Valhelsia 5 (5.0.16), which was the same version this mod got added, I removed it from the server side and now it works.

**Comment by embeddedt** [comment]
I'll try reproducing using a Valhesia 5 server.

**Comment by Disnejar** [comment]
I'm using docker compose with the itzg image, that may've also impacted this.

**Comment by embeddedt** [comment]
I created a fresh Valhesia 5.0.16 server, which started without problems. I then stopped the server and restarted it on the same world, which also worked fine. So I still cannot reproduce this.

Did you make any config changes? Can I have a copy of the world where this issue occurs?

**Comment by Disnejar** [comment]
The only configs I changed were the ones from the waystones mod. 
You can try to update it from 5.0.14b to 5.0.16, that was what I did on my server.

**Comment by embeddedt** [comment]
I'll try the update.

**Comment by Disnejar** [comment]
I can get you a copy of the world and configs tomorrow.

Sincerely,
Filip Orlowski

niedz., 12 mar 2023, 22:29 użytkownik embeddedt ***@***.***>
napisał:

**Comment by embeddedt** [comment]
Upgraded world still seems to load fine unfortunately. Perhaps the issue is seed-dependent. I'll wait to hear back from you.

**Comment by embeddedt** [comment]
I extracted this ZIP into the server root so it should have all the same configs as you. The world successfully loads. I did see the following warning about missing mods in the log, not sure why, since these all look like client-side mods to me.

```
ambientenvironment (version 8.0+3 -> MISSING)                                                                                                                                                    
ambientsounds (version 5.2.13 -> MISSING)                                                                                                                                                        
betteradvancements (version 0.2.2.142 -> MISSING)                                         
betterf3 (version 4.0.0 -> MISSING)                                                             
bhmenu (version 1.19.2-1.3 -> MISSING)                                                                                                                                                           
bwncr (version 3.14.1 -> MISSING)                                                                                                                                                                
catalogue (version 1.7.0 -> MISSING)                                                                                                                                                             
chat_heads (version 0.10.4 -> MISSING)                                                                                                                                                           
cherishedworlds (version 6.0.1+1.19.2 -> MISSING)                                                                                                                                                
configured (version 2.0.1 -> MISSING)                                                                                                                                                            
controlling (version 10.0+7 -> MISSING)                                                                                                                                                          
defaultoptions (version 15.0.0 -> MISSING)                                                                                                                                                       
fallingleaves (version 1.3.1 -> MISSING)                                                                                                                                                         
fancymenu (version 2.13.3 -> MISSING)                                                                                                                                                            
farsight_view (version 1.19.2-2.1 -> MISSING)                                                                                                                                                    
fpsreducer (version 1.19.2-2.1 -> MISSING)                                                                                                                                                       
lightoverlay (version 7.0.1 -> MISSING)    
```

**Comment by P3rf3ctXZer0** [comment]
It looks like we have the same issue with structure manager except mine hangs. XD

**Comment by Disnejar** [comment]
> I extracted this ZIP into the server root so it should have all the same configs as you. The world successfully loads. I did see the following warning about missing mods in the log, not sure why, since these all look like client-side mods to me.
> 
> ```
> ambientenvironment (version 8.0+3 -> MISSING)                                                                                                                                                    
> ambientsounds (version 5.2.13 -> MISSING)                                                                                                                                                        
> betteradvancements (version 0.2.2.142 -> MISSING)                                         
> betterf3 (version 4.0.0 -> MISSING)                                                             
> bhmenu (version 1.19.2-1.3 -> MISSING)                                                                                                                                                           
> bwncr (version 3.14.1 -> MISSING)                                                                                                                                                                
> catalogue (version 1.7.0 -> MISSING)                                                                                                                                                             
> chat_heads (version 0.10.4 -> MISSING)                                                                                                                                                           
> cherishedworlds (version 6.0.1+1.19.2 -> MISSING)                                                                                                                                                
> configured (version 2.0.1 -> MISSING)                                                                                                                                                            
> controlling (version 10.0+7 -> MISSING)                                                                                                                                                          
> defaultoptions (version 15.0.0 -> MISSING)                                                                                                                                                       
> fallingleaves (version 1.3.1 -> MISSING)                                                                                                                                                         
> fancymenu (version 2.13.3 -> MISSING)                                                                                                                                                            
> farsight_view (version 1.19.2-2.1 -> MISSING)                                                                                                                                                    
> fpsreducer (version 1.19.2-2.1 -> MISSING)                                                                                                                                                       
> lightoverlay (version 7.0.1 -> MISSING)    
> ```

That's because I'm using the AUTO_CURSEFORGE type on the itzg image on docker compose, which uses the client-side file of the mods, and removes the client-side ones. I think :)

**Comment by embeddedt** [comment]
@P3rf3ctXZer0 @Disnejar This should be fixed in 3.1.1. It's been uploaded to CF but review takes a while, so I've also attached a ZIP with this version here.

[3.1.1.zip](https://github.com/embeddedt/ModernFix/files/10960827/3.1.1.zip)

**Comment by Kanzaji** [comment]
Ya welcome for help debugging this 😄

**Comment by P3rf3ctXZer0** [comment]
This is fixed

**Comment by embeddedt** [comment]
Most of the credit should go to @Kanzaji for taking their time to try and reproduce on their setup, without which I would probably still be attempting to hunt down the cause.

**Comment by P3rf3ctXZer0** [comment]
Well then thank you @Kanzaji as said normally I would not mind bug hunting.
