### ISSUE TITLE
Recipe Book Not Working with JEI Installed

### ISSUE THREAD

**Issue by khazenor** [embeddedt/ModernFix#360]
### Bug Description

Recipe book search does not work with Jei also installed.

### Reproduction Steps

- install the following mods
  - forge 1.20.1 47.2.20
  - jei-1.20.1-forge-15.2.0.27
  - modernfix-forge-5.9.3+mc1.20.1
- start the instance and create a new world
- make a crafting table and open the recipe book
- try searching for an item in the recipe book

What happens:
- all search results disappear when the user start typing in the recipe book search bar.

What should happen:
- search result should populate as the user types in the search bar.

### Log File

[latest.log](https://github.com/embeddedt/ModernFix/files/14117691/latest.log)

**Comment by embeddedt** [comment]
This is an intentional optimization. See https://github.com/embeddedt/ModernFix/wiki/General-FAQ#why-doesnt-the-recipe-book-work-anymore-with-jeirei-installed for more information.

**Comment by khazenor** [comment]
Ahh I see!  Thanks for the info!
