### ISSUE TITLE
Game crashes on a modded server

### ISSUE THREAD

**Issue by SmoothieCubie** [embeddedt/ModernFix#362]
### Bug Description

I was on a modded server when my client crashed and it said ModernFix caused the crash

### Reproduction Steps

Crashes on a modded server

### Log File

[2024-02-06-2.log.gz](https://github.com/embeddedt/ModernFix/files/14177211/2024-02-06-2.log.gz)

**Comment by embeddedt** [comment]
Crash was not caused by ModernFix; the Forge crash report analyser falsely blames performance mods a lot of the time. Check that you are using the exact same mod versions & config files on the client and server.
