### ISSUE TITLE
ModernFix + LightmansCurrency [Render thread/WARN] Forge

### ISSUE THREAD

**Issue by Krimatoria** [embeddedt/ModernFix#366]
### Bug Description

[LightmansCurrency](https://github.com/Lightman314/LightmansCurrency/issues/193) - pay attention to this branch, there is a part of the and the developer's answer about this problem. The code from the Log file is also there.

### Reproduction Steps

lightmanscurrency-1.19.2-2.2.0.3a.jar
modernfix-forge-5.13.0+mc1.19.2.jar

### Log File

[09Feb2024 13:15:46.843] [Render thread/WARN] [ModernFix/]: PathResourcePack base class instantiated with root path of mod file lightmanscurrency-1.19.2-2.2.0.3a.jar. This probably means a mod should be calling ResourcePackLoader.createPackForMod instead. Applying workaround.

**Comment by embeddedt** [comment]
This warning can be ignored if it's not causing issues; it exists because in many (but not all) cases, calling `PathResourcePack` in this way will lead to unexpected results (see https://github.com/way2muchnoise/JustEnoughResources/pull/408#issuecomment-1658528916).

**Comment by Krimatoria** [comment]
> This warning can be ignored if it's not causing issues; it exists because in many (but not all) cases, calling `PathResourcePack` in this way will lead to unexpected results (see [way2muchnoise/JustEnoughResources#408 (comment)](https://github.com/way2muchnoise/JustEnoughResources/pull/408#issuecomment-1658528916)).

Ok)

**Comment by Krimatoria** [comment]
> This warning can be ignored if it's not causing issues; it exists because in many (but not all) cases, calling `PathResourcePack` in this way will lead to unexpected results (see [way2muchnoise/JustEnoughResources#408 (comment)](https://github.com/way2muchnoise/JustEnoughResources/pull/408#issuecomment-1658528916)).

Worker-ResourceReload-4/WARN - And is this error as minor in itself as the Path Resource Pack? I just keep a lot of such errors in 1.20.1 and thought maybe it just looks like this in the new version now?)
