### ISSUE TITLE
[1.20.4] Crash upon using with terralith - CachingStructureManager Error

### ISSUE THREAD

**Issue by lota09** [embeddedt/ModernFix#367]
### Reproduction Steps

May occured upon opening chunk containing terralith mod structure

### Log File

[crash-2024-02-15_14.18.33-server.txt](https://github.com/embeddedt/ModernFix/files/14299500/crash-2024-02-15_14.18.33-server.txt)

**Comment by embeddedt** [comment]
You probably need to allocate more memory to the game, this doesn't look like a bug to me. Complex structures require more memory to load successfully.
