### ISSUE TITLE
error: invalid source release 17 with --enable-preview

### ISSUE THREAD

**Issue by Eggmanplant** [embeddedt/ModernFix#369]
### Bug Description

this happens when trying to build via intellij (1.20.5 branch) on linux

### Reproduction Steps

try to build the fabric version of the 1.20.5 branch via intellij on linux

### Log File

no. it doesnt build.

**Comment by embeddedt** [comment]
CI uses Temurin 17 to build and it works fine; what JDK version are you using?

**Comment by Eggmanplant** [comment]
temurin fixed the issue.
