### ISSUE TITLE
Random crash in a multi-mod environment in 1.20.1

### ISSUE THREAD

**Issue by Sovina1991** [embeddedt/ModernFix#374]
### Bug Description

Collapse when walking to specific locations

### Reproduction Steps

Collapse when walking to specific locations

### Log File

[crash-2024-03-06_12.08.49-server.txt](https://github.com/embeddedt/ModernFix/files/14504534/crash-2024-03-06_12.08.49-server.txt)

**Comment by embeddedt** [comment]
It doesn't appear to be caused by ModernFix; the Forge crash report analyzer incorrectly blames it because it optimizes some of the code that's running at the time. One of your other mods is likely accessing structure data from the wrong thread.
