### ISSUE TITLE
Client crashes when opening inventory in creative mode on a server in 1.20.1

### ISSUE THREAD

**Issue by JDanielRC** [embeddedt/ModernFix#375]
### Bug Description

Whenever I open the creative inventory, my game crashes. However, this only happens on my server, not in singleplayer.

ModernFix version: 5.13.0

### Reproduction Steps

Join a modded server (Custom modded server with all the mods 9 modpack and a few extras)
Go into creative
Open your inventory
See issue

### Log File

[crash-2024-03-07_01.32.55-client.txt](https://github.com/embeddedt/ModernFix/files/14520536/crash-2024-03-07_01.32.55-client.txt)

**Comment by embeddedt** [comment]
Not a ModernFix bug; check that the server & client have exactly the same mod versions and config files.

**Comment by JDanielRC** [comment]
Thanks! Did some double checking around the modpack and found a mod that was added as a dependency and wasn't added to the server, valhesia furniture in case anyone founds this on a future, removed it from my own client and issue got fixed.
