### ISSUE TITLE
Latest release incompatible with Optifine (1.20.1)

### ISSUE THREAD

**Issue by ElRokur** [embeddedt/ModernFix#376]
### Bug Description

The game crashes on start with Optifine on 1.20.1 and modern fix 5.14.0
Ofc, the game goes fine without Optifine and only modern fix 5.14.0.
The game goes fine if i downgrade Modern Fix to 5.13 even with Optfine.

### Reproduction Steps

Game crashes on Startup:

MC 1.20.1
OptiFine_1.20.1_HD_U_I6
modernfix-forge-5.14.0+mc1.20.1.jar

Game goes fine:

MC 1.20.1
OptiFine_1.20.1_HD_U_I6
modernfix-forge-5.13.0+mc1.20.1.jar

### Log File

[latest.log](https://github.com/embeddedt/ModernFix/files/14542726/latest.log)

thats the log of the crash

**Comment by embeddedt** [comment]
This will be fixed in the next release, but as noted in the log using OptiFine with ModernFix isn't officially supported, and you may run into other issues.

**Comment by embeddedt** [comment]
Should be fixed in 5.15.0.
