### ISSUE TITLE
Is this a modernfix caused crash?

### ISSUE THREAD

**Issue by funnycubeguy** [embeddedt/ModernFix#377]
### Bug Description

Server crashes

### Reproduction Steps

Just updated to the latest version of modernfix and seem to get this issue on all my servers. Is it related to modernfix? Thanks

### Log File

https://pastes.dev/WSH7VuccaV

**Comment by embeddedt** [comment]
No, another mod is accessing the chunk system from the wrong thread, which causes a `ConcurrentModificationException` when the main server thread tries to update chunk data.
