### ISSUE TITLE
[1.20.4] Diagonal Fences crash on launch

### ISSUE THREAD

**Issue by ghost** [embeddedt/ModernFix#378]
### Bug Description

v5.14.0 of ModernFix
v20.4.0 of Diagonal Fences

### Reproduction Steps

Install Diagonal Fences
Install ModernFix
Try to run the game

### Log File

[latest.log](https://github.com/embeddedt/ModernFix/files/14625330/latest.log)

**Comment by embeddedt** [comment]
Looks like the same More Culling issue as https://github.com/embeddedt/ModernFix/issues/328, try removing it.
