### ISSUE TITLE
Some blocks from Eden Ring Reforked are missing textures

### ISSUE THREAD

**Issue by ErzeKawek** [embeddedt/ModernFix#379]
### Bug Description

Textures for Parignum, Balloon Mushroom Block, And Gravilite Shows. This Issue Applies to All 1.20.1-1.20.4 Versions For ModernFix

### Reproduction Steps

1. Put Eden Ring Reforked And ModernFix Together in A Pack
2. Enable Dynamic Resources
3. Place One Of The Blocks Mentioned on the Description

### Log File

[latest.log](https://github.com/embeddedt/ModernFix/files/14666043/latest.log)

**Comment by embeddedt** [comment]
Fixed in 5.15.0
