### ISSUE TITLE
[1.18.2] Crash with Dynamic Trees

### ISSUE THREAD

**Issue by Lozf** [embeddedt/ModernFix#38]
Using the newest release for 1.18.2, forge loader 40.2.0

[latest.log](https://github.com/embeddedt/ModernFix/files/10949501/latest.log)
[crash-2023-03-11_13.06.44-server.txt](https://github.com/embeddedt/ModernFix/files/10949502/crash-2023-03-11_13.06.44-server.txt)

**Comment by embeddedt** [comment]
This is a bug in Dynamic Trees; I cannot do anything from my end unless I add a hack to work around their issue. See https://github.com/DynamicTreesTeam/DynamicTrees/issues/758.

**Comment by Lozf** [comment]
Ok, thanks for looking at it!

**Comment by embeddedt** [comment]
Latest version of ModernFix should work around this issue; it tries to behave more similarly to vanilla.

**Comment by Lozf** [comment]
I just tried it out, works awesome!  Thank you!!!! :D saves me so much time loading now.
