### ISSUE TITLE
Baking Errors With CreateFramed

### ISSUE THREAD

**Issue by SaltSouls** [embeddedt/ModernFix#380]
### Bug Description

When loading the models from createframed, modernfix throws a bunch of errors baking errors.

### Reproduction Steps

1. Load createframed alongside modernfix
2. Run game
3. Watch errors roll in
4. ???
5. Profit

### Log File

[latest.log](https://github.com/embeddedt/ModernFix/files/14675702/latest.log)
[debug.log](https://github.com/embeddedt/ModernFix/files/14675704/debug.log)

**Comment by embeddedt** [comment]
Seeing some errors in the log with dynamic resources turned on is normal. There are a lot of hacks needed to make it work with the various ways in which mods inject custom models. As long as the blocks/items render fine in game, the errors can be ignored.
