### ISSUE TITLE
[1.20.1] Just need some guidance and modernfix was all I had to go on.

### ISSUE THREAD

**Issue by Terra-B-Welch** [embeddedt/ModernFix#383]
I didn't want to post this as a bug, as I know it's likely not even related to ModernFix, but it's ModernFix's logs that led me to this GitHub.

I threw together a personal use modpack for 1.20.1, and on Windows it ran perfectly fine without issue, however about a week ago I decided to migrate over to Linux and ever since then my 1.20.1 modpack has been having this issue where the internal server just hangs and I get a ton of modernfix integrated server watchdog stuff in the logs.

I provided my latest log from my latest test here.
https://pastes.io/1r2omhiehi

I'm not expecting any fixes from this mod, as I know this mod isn't the cause, as I said I just need some guidance and the watchdog thing was the most obvious part of the log to me, so I thought I'd ask here.

My other modpacks all work on Linux, it's only my 1.20.1 modpack having this issue.

**Comment by P3rf3ctXZer0** [comment]
please use this if you want help. https://mclo.gs

**Comment by Terra-B-Welch** [comment]
I don't know why the paste site makes any difference but whatever. Here.
https://mclo.gs/YQ02vHo

**Comment by embeddedt** [comment]
The server appears to be stalling on writing region files to the disk, which suggests that either the disk is slow, you have very large chunks being saved, or a mod is spamming unnecessary chunk saves.

**Comment by Terra-B-Welch** [comment]
Hm if it's a slow disk then I wonder if I set up a partition incorrectly during my migration then, I'm not sure if partitions might be the cause, otherwise why would it have worked perfectly while it was on Windows?

The fact the modpack was working without issue on windows is what's making me think I messed up a partition, thanks for the help anywho.

**Comment by Terra-B-Welch** [comment]
Well I think I can confirm it's one of the mods in the modpack causing it, maybe one of those mods doesn't like linux.

I say this as I did a test in a 1.20.1 instance with only this mod and had no issues, I'll be closing this now and trying to figure out the mod myself I guess, thanks for the guidance anywho.

**Comment by Terra-B-Welch** [comment]
so get this, for some god forsaken reason, my hang issue does not occur if I run my modpack through the windows version of multimc using wine via lutris, it's absolute jank, but my issue has finally been fixed, and I just felt like sharing that.
