### ISSUE TITLE
Crashing on 24w13a

### ISSUE THREAD

**Issue by Eggmanplant** [embeddedt/ModernFix#386]
### Bug Description

Crashing on 24w13a. Nothing more.

### Reproduction Steps

Build the 1.20.5 branch and try to run the game.

### Log File

[log.txt](https://github.com/embeddedt/ModernFix/files/14814493/log.txt)

**Comment by embeddedt** [comment]
Does the latest commit fix it?

**Comment by Eggmanplant** [comment]
Will check later.

**Comment by embeddedt** [comment]
It's definitely fixed in 24w14a, ran that build with no problems in production.
