### ISSUE TITLE
Some font replaced with square using Modernfix on 1.20.4

### ISSUE THREAD

**Issue by Anonyku05** [embeddedt/ModernFix#388]
### Bug Description

So basically, while using modernfix, there are some fonts that seems to be missing for some reasons, look at the screens below:
![image](https://github.com/embeddedt/ModernFix/assets/48128391/7b862b78-767b-4842-81d3-375a09ffa93d)
Instead of this:
![image](https://github.com/embeddedt/ModernFix/assets/48128391/58546255-5871-4f20-8501-6aced3fb59f0)
Screens above Jade mod

![image](https://github.com/embeddedt/ModernFix/assets/48128391/9b18a9cf-8ef6-49fd-b7bc-16a7c8806473)
Screen above text utilities mod

I've gone threw my entire modpack of nearly 200 mods to figure it out lol

### Reproduction Steps

1- Install modernfix on fabric 1.20.4
2- Use the fabric api and jade mod (possibly an issue coming from another mod but not sure)

### Log File

[latest.log](https://github.com/embeddedt/ModernFix/files/14879312/latest.log)

**Comment by embeddedt** [comment]
I cannot reproduce this in a standalone instance with ModernFix & Jade on Fabric 1.20.4. Please check that you have not made any changes to the ModernFix config file, as there is an option (`mixin.feature.disable_unihex_font`) which if enabled will cause many special characters to not render.

**Comment by Anonyku05** [comment]
> I cannot reproduce this in a standalone instance with ModernFix & Jade on Fabric 1.20.4. Please check that you have not made any changes to the ModernFix config file, as there is an option (`mixin.feature.disable_unihex_font`) which if enabled will cause many special characters to not render.

The issue was indeed coming from this, i've put false on the option and now everything is back to normal ! Thanks a lot !
![image](https://github.com/embeddedt/ModernFix/assets/48128391/7a2a412c-bc10-4018-9585-7977f6befb7a)
![image](https://github.com/embeddedt/ModernFix/assets/48128391/12b4092b-971c-4a42-8525-28366e07517a)

**Comment by embeddedt** [comment]
Great!
