### ISSUE TITLE
1.20.1 unable to use search bar in crafting table with JEI installed.

### ISSUE THREAD

**Issue by RefinedRain** [embeddedt/ModernFix#389]
### Bug Description

Went through to delete many mods in a pack. Found Modernfix was the issue. I was unable to use the crafting bench search bar to look up crafting recipes. Suspected J.E.I. and confirmed there's something restricting the ability to look up in the search bar. 

### Reproduction Steps

I Updated ModernFix 1.20.1 with the most updated and compatable J.E.I.  tried version 5.15 and 5.14 forge versions. 

### Log File

[latest.log](https://github.com/embeddedt/ModernFix/files/14880371/latest.log)

**Comment by embeddedt** [comment]
This is intended behavior if JEI is installed. https://github.com/embeddedt/ModernFix/wiki/General-FAQ#why-doesnt-the-recipe-book-work-anymore-with-jeirei-installed

That being said, I've implemented a way for the recipe book to still work in the next release. In the meantime you can use the workaround linked on that page.
