### ISSUE TITLE
[QUESTION]

### ISSUE THREAD

**Issue by Willem07** [embeddedt/ModernFix#39]
Please tell me what this means and how to fix it?
![screenshot](https://user-images.githubusercontent.com/51959206/224569793-cea77d53-7553-400e-a9b6-9eb2416a63c7.png)

> I can't upload logs
![screenshot](https://user-images.githubusercontent.com/51959206/224569985-d356eaa3-da7b-4f3a-9c11-2a9565106abd.png)

mod version: [modernfix-mc1.18.2-2.1.0](https://www.curseforge.com/minecraft/mc-mods/modernfix/files/4432430)
forge: 1.18.2-40.2.0

**Comment by embeddedt** [comment]
No fix is required; this is just ModernFix notifying you that one of your mods uses outdated structures which slows down the launch. This warning is harmless (hence why it is a warning, and not an error).
