### ISSUE TITLE
spawn-chunks related crash with carpet mod

### ISSUE THREAD

**Issue by Oguzhan5585** [embeddedt/ModernFix#390]
### Bug Description

the game crashes if you have the `remove_spawn_chunks` option enabled and then enter a singleplayer world where the carpet option `spawnChunkSize` is modified

### Reproduction Steps

- have carpet mod installed
- enter a singleplayer world and do `/carpet setDefault spawnChunkSize 0`
- leave the world
- now add modernfix and set `mixin.perf.remove_spawn_chunks` to `on`
- trying to enter that world now will make the game crash

### Log File

[crash-2024-04-06_00.44.54-server.txt](https://github.com/embeddedt/ModernFix/files/14891391/crash-2024-04-06_00.44.54-server.txt)

**Comment by embeddedt** [comment]
I will probably just solve this by making `remove_spawn_chunks` impossible to enable with Carpet installed, since it appears that can do the same thing.

**Comment by Oguzhan5585** [comment]
but the option in modernfix seems preferable over carpet's if it is just set to 0 to disable the spawn chunks because for me it seems like i can join a singleplayer world with modernfix's option faster than with the carpet option being set to 0. so while carpet's option allows you to change the size of the spawn chunks to a custom size, when it comes to simply disabling them then modernfix seems to be better at that.

**Comment by embeddedt** [comment]
This issue is now fixed in 5.16.0, there will no longer be a crash with both options enabled.
