### ISSUE TITLE
Fusion Incompat

### ISSUE THREAD

**Issue by WenXin20** [embeddedt/ModernFix#392]
### Bug Description

With Modernfix installed, connected textures do not properly apply with the Fusion mod. This can be tested with my Warp Pipes mod, which uses Fusion for connected textures. This was tested on 1.20.1 of Forge
To fix this, I had to disable `mixin.perf.resourcepacks=false` 

### Reproduction Steps

1. Install [Warp Pipes](https://www.curseforge.com/minecraft/mc-mods/wenxins-warp-pipes) & [Fusion](https://www.curseforge.com/minecraft/mc-mods/fusion-connected-textures)
2. Observe connected textures
3. Install ModernFix
4. Observe connected textures do not apply

### Log File

I didn't find any errors in the log. But if you think it will still help, I can send a new one.

**Comment by embeddedt** [comment]
Should be fixed in 5.16.1
