### ISSUE TITLE
Not sure whats with that but, after updating ModernFix into 5.16.0 and made a spark test, modernfix seem to create TPS problems?

### ISSUE THREAD

**Issue by Fyoncle** [embeddedt/ModernFix#393]
### Bug Description

![Spark](https://github.com/embeddedt/ModernFix/assets/63975256/6f1e3766-3095-4458-93ff-e4419a8674cd)

I use Elysium Days modpack by the way.

### Reproduction Steps

1. Update ModernFix to 5.16.0
2. Run around the map for like 5 minutes
3. Type /spark profiler stop and check the Mods list

### Log File

No need

**Comment by embeddedt** [comment]
Please provide a link to the Spark profile.

**Comment by Fyoncle** [comment]
> Please provide a link to the Spark profile.

Theres nothing special inside it, it doesn't provide any info.
![Spark2](https://github.com/embeddedt/ModernFix/assets/63975256/e8c88a89-d6de-42b0-a260-a1131c52f507)

**Comment by embeddedt** [comment]
`LockSupport.parkNanos` is called when the server is waiting between ticks; it doesn't indicate lag. This appears to be a false positive from Spark.

**Comment by Fyoncle** [comment]
> `LockSupport.parkNanos` is called when the server is waiting between ticks; it doesn't indicate lag. This appears to be a false positive from Spark.

Oh, so its not any TPS issue at all but false? becuase i have been having tps issues on my modpack for a long while and cannot figure it out why, and when i saw ur mod all the way above after update it just looked weird.

**Comment by embeddedt** [comment]
Yes, it is because I patch the code which calls `LockSupport.parkNanos` as of 5.16.0 (to fix a vanilla bug), which I guess causes Spark to falsely blame ModernFix for the time spent waiting. I think your other TPS issues are unrelated.
