### ISSUE TITLE
Texture Stitching was not fixed. RTX 3070 (v5.16.0)

### ISSUE THREAD

**Issue by YeetboiPro** [embeddedt/ModernFix#394]
### Bug Description

Texture Stitching issue was not fixed. I have an RTX 3070 and I still can't load big mods in big modpacks with the new update.

### Reproduction Steps

Add all the LandK mods and like 200-300 other mods at once.

### Log File

Load screen does not freeze but gets stuck on the tail end of the final loading step without crashing.

**Comment by embeddedt** [comment]
> Add all the LandK mods and like 200-300 other mods at once.

It is extremely time-consuming (and therefore infeasible) to debug with 300 mods in 99% of scenarios. Please provide reproduction steps that do not require such a large number of mods at once.

**Comment by YeetboiPro** [comment]
It was something on my end. I removed my custom mod and it started working.
I apologize for any inconvenience I may have caused.

**Comment by embeddedt** [comment]
Glad it's fixed!
