### ISSUE TITLE
CPU usage. on 5.16.1+mc1.20.4 installed from curseforge. 

### ISSUE THREAD

**Issue by T-Gx** [embeddedt/ModernFix#396]
### Bug Description

I updated the version i noticed that the cpu usage was increasing, it reached the 100% usage (and it is a mid gaming cpu), the game was unplayable. I went to the menu and the cpu usage didn't decrease, so i closed the game and it stopped. When i opend the game again the cpu usage didn't appear again. I supose that it's from this mod because it was the only change i made

### Reproduction Steps

I was playing with a 3d item rp(nongko's fantasy weapons), but that would only affect to gpu

### Log File

i don't any file, my pc was lagging so hard that the screenshoot stuff didn't work, and it didn't crash. anyways, i let you some crashes i had weeks ago, i don't think they help tho
[crash-2024-04-01_13.27.51-client.txt](https://github.com/embeddedt/ModernFix/files/15015573/crash-2024-04-01_13.27.51-client.txt)
[crash-2024-04-01_13.45.28-client.txt](https://github.com/embeddedt/ModernFix/files/15015575/crash-2024-04-01_13.45.28-client.txt)
[crash-2024-04-04_18.08.56-client.txt](https://github.com/embeddedt/ModernFix/files/15015576/crash-2024-04-04_18.08.56-client.txt)

**Comment by embeddedt** [comment]
If this cannot be reproduced with just ModernFix installed in a fresh instance, it's likely unrelated.

**Comment by Zontyk** [comment]
i have a same problem
