### ISSUE TITLE
`modernfix.debugReloader` should affect datapack reload as well

### ISSUE THREAD

**Issue by SettingDust** [embeddedt/ModernFix#397]
### Bug Description

For now the `modernfix.debugReloader` only applied in https://github.com/embeddedt/ModernFix/blob/1.16/common/src/main/java/org/embeddedt/modernfix/common/mixin/feature/measure_time/SimpleReloadableResourceManagerMixin.java

But not `DataPackContents`(`ReloadableServerResources` in mojmap)
`SimpleResourceReload.start(manager, dataPackContents.getContents(), prepareExecutor, applyExecutor, COMPLETED_UNIT, LOGGER.isDebugEnabled())`

Modify the boolean in `SimpleReloadInstance#create` maybe better?

### Reproduction Steps

Enable `modernfix.debugReloader` with JVM flag and join world

### Log File

no-op

**Comment by embeddedt** [comment]
Implemented the suggested change in 5.19.0.
