### ISSUE TITLE
[Bug] Log spam with Immersive Engineering(and Petroleum).

### ISSUE THREAD

**Issue by wasdspace** [embeddedt/ModernFix#4]
forge: 36.2.39
modernfix: 1.3.0

Immersive Engineering: 5.1.0-148 (_Lasest on Curseforge_)
Immersive Petroleum: 3.4.0-13 (_Lasest on Curseforge_)

with modernfix:
[debug.log](https://github.com/embeddedt/ModernFix/files/10359747/debug.log) - 1030KB
[latest.log](https://github.com/embeddedt/ModernFix/files/10359748/latest.log) - 945KB
takes 25s to start

without:
[debug.log](https://github.com/embeddedt/ModernFix/files/10359750/debug.log) - 86KB
[latest.log](https://github.com/embeddedt/ModernFix/files/10359751/latest.log) - 12KB
takes 10s to start

**Comment by embeddedt** [comment]
Thanks! It should be fixed in 1.3.1. Here is the new version to test since CurseForge will probably take a bit to approve:

[newversion.zip](https://github.com/embeddedt/ModernFix/files/10361429/newversion.zip)

**Comment by wasdspace** [comment]
Works perfectly for me! Thank you so much!
