### ISSUE TITLE
Crash 1.16.5

### ISSUE THREAD

**Issue by Redls07** [embeddedt/ModernFix#40]
Mod version 1.10.1

[crash-2023-03-14_20.58.12-client.txt](https://github.com/embeddedt/ModernFix/files/10969540/crash-2023-03-14_20.58.12-client.txt)

**Comment by embeddedt** [comment]
I think it's an incompatibility with Better Loading Screen, the only way to fix this would be to automatically disable the optimizations on my side if its installed (which would slow down the launch). I'd suggest just not using Better Loading Screen.

**Comment by Redls07** [comment]
Yeah, tried to run the game without it, and there is no crash. Thank you for the quick response and for your work. Game loading decreased from 2 min 50 sec to 1 min 10 sec

**Comment by embeddedt** [comment]
At some point I'm thinking I will add my own idea of a loading screen directly in ModernFix.

**Comment by Redls07** [comment]
If it can be disabled in the config, if someone doesn't like it, then why not

**Comment by Redls07** [comment]
Another crash, this time when trying to create a world
[crash-2023-03-17_09.46.55-client.txt](https://github.com/embeddedt/ModernFix/files/10997489/crash-2023-03-17_09.46.55-client.txt)

**Comment by embeddedt** [comment]
Known issue with Dynamic Trees - they have buggy code in their blocks which just so happens to work fine with vanilla. Unfortunately I can't easily fix it from my side.

https://github.com/DynamicTreesTeam/DynamicTrees/issues/758

**Comment by embeddedt** [comment]
I might tweak ModernFix's caching logic to behave more like vanilla, in order to avoid outright crashes if there is a buggy mod.

**Comment by Redls07** [comment]
It would be great

**Comment by Redls07** [comment]
Crash
[crash-2023-03-21_16.00.04-client.txt](https://github.com/embeddedt/ModernFix/files/11026496/crash-2023-03-21_16.00.04-client.txt)

**Comment by embeddedt** [comment]
This is an incompatibility with Lightspeed that is on my list of things to fix. For now you should just run without Lightspeed; there shouldn't be much performance loss as at the moment, ModernFix implements mostly the same optimizations.

**Comment by embeddedt** [comment]
I just pushed 1.11.1 with a fix; it may take a little bit to get approved on CurseForge.

**Comment by Redls07** [comment]
Everything works, thanks a lot! 62 seconds with Lightspeed :)
