### ISSUE TITLE
Modern Fix Loaded Too Early

### ISSUE THREAD

**Issue by Fyoncle** [embeddedt/ModernFix#401]
### Bug Description

When i join the game fabric crashes saying weird things and in the log it says Modern Fix loaded too early, it also says some things like advanced resource pack kind of things.

### Reproduction Steps

Idk, it happened after installing custom splash screen

### Log File

https://mclo.gs/iJjuRna

**Comment by embeddedt** [comment]
This is not ModernFix's fault, one of your other mods loads Minecraft code too early.

**Comment by Fyoncle** [comment]
> This is not ModernFix's fault, one of your other mods loads Minecraft code too early.

Thank you for fast answer but, which?

**Comment by embeddedt** [comment]
Unfortunately the error doesn't say, you'll have to remove mods you added recently until the crash stops happening.

**Comment by Fyoncle** [comment]
> Unfortunately the error doesn't say, you'll have to remove mods you added recently until the crash stops happening.

It can be because i added some mod's config instantly before i start the game for it to create its own configs first?

**Comment by embeddedt** [comment]
No, that shouldn't cause the issue.

**Comment by Fyoncle** [comment]
> No, that shouldn't cause the issue.

But it only happened in first launch, and other launches are fine?

**Comment by embeddedt** [comment]
:man_shrugging: If one of your mods has code that only runs on the first launch, then maybe. I cannot really guess just from looking at the log; hence my general suggestions of removing mods until the issue stops. All I can say is that the error is not a ModernFix bug.

**Comment by Fyoncle** [comment]
> 🤷‍♂️ If one of your mods has code that only runs on the first launch, then maybe. I cannot really guess just from looking at the log; hence my general suggestions of removing mods until the issue stops. All I can say is that the error is not a ModernFix bug.

Oh, wait ill try something and come back to you real quick.

**Comment by Fyoncle** [comment]
> 🤷‍♂️ If one of your mods has code that only runs on the first launch, then maybe. I cannot really guess just from looking at the log; hence my general suggestions of removing mods until the issue stops. All I can say is that the error is not a ModernFix bug.

Ah its impossible to find the mod, since it only appears in the first launch, but yea one possible mod is "Custom Splash Screen" i guess.

**Comment by embeddedt** [comment]
The AoF devs tracked down that the latest version of https://legacy.curseforge.com/minecraft/mc-mods/lets-do-meadow is causing this. I'd recommend downgrading one version until they release a fix.
