### ISSUE TITLE
[Question] Fast Async World Save / Smooth Chunk Save compatibility.

### ISSUE THREAD

**Issue by VOLKOUL** [embeddedt/ModernFix#403]
### Info

Hi! Sorry for making a report, but I was wondering whether the fixes of ModernFix include the optimizations (or part of the optimizations) provided by the Fast Async World Save / Smooth Chunk Save mods, as them interfering in some way could potentially cause a number of problems. Thanks!

**Comment by embeddedt** [comment]
Nope, no adjustments are currently made to how chunks save.
