### ISSUE TITLE
MUSICA DO WITHER STORM NAO TOCA

### ISSUE THREAD

**Issue by PAULINHO2834** [embeddedt/ModernFix#407]
### Bug Description

BOA TARDE MEU MOD DO WITHER STORM DESDE A NOVA UPDATE AS MUSICAS NAO QUEREM TOCAR SEMPRE TOCAVA BONITINHO JA FUI LA NAS OPCOES PRA VER A MUSICA E DIZ QUE TA FALSE A MUSICA NAO SEI OQ PODE ESTAR ACONTECENDO.
SE POSSIVEL PODEM RESOLVER

### Reproduction Steps

NAO SEI

### Log File

NAO SEI

**Comment by embeddedt** [comment]
Please use English on the bug tracker. Additionally, please provide steps to recreate the problem and verify that the issue occurs with just ModernFix & Wither Storm Mod installed; there are many reasons why this could happen.

**Comment by PAULINHO2834** [comment]
OK

Em sex., 17 de mai. de 2024, 17:54, embeddedt ***@***.***>
escreveu:
