### ISSUE TITLE
MY MUSIC OF WITHER STORM ITS NOT WORKING

### ISSUE THREAD

**Issue by PAULINHO2834** [embeddedt/ModernFix#408]
### Bug Description

GOOD AFTERNOON MY WITHER STORM MUSIC HASN´T BEEN PLAYNG SICE YOUR NEW UPDATE, I´VE ALREADY TESTED EVERYTHING AND IT´S ONLY IN THE MOD THAT IT DOESN´T WORK

### Reproduction Steps

I DON´T KNOW

### Log File

I DON´T KNOW

**Comment by embeddedt** [comment]
Cannot reproduce. With ModernFix 5.18.0 and CWSM installed on 1.20.1, the sound track plays fine. Note that you need to enable `playWitherStormTheme` in the wither storm mod config for this to work, as stated in their [documentation](https://github.com/nonamecrackers2/crackers-wither-storm-mod/wiki/Preferences-and-Performance).
