### ISSUE TITLE
Lunar Client Compatibility

### ISSUE THREAD

**Issue by kispintyi** [embeddedt/ModernFix#409]
### Bug Description

ModernFix is not compatible with Lunar Client - Will it ever be supported?

### Reproduction Steps

Install Lunar Client
Go to any version that ModernFix supports
Go to the mods section
 Click the folder icon
Add ModernFix
Play
Observe the game Crashing

### Log File

(log file from a **1.20.6 game** with the **ModernFix 5.17.3+mc1.20.6** mod version):
[crash-2024-05-29_20.32.48-client.txt](https://github.com/embeddedt/ModernFix/files/15489313/crash-2024-05-29_20.32.48-client.txt)

**Comment by embeddedt** [comment]
Custom clients won't be supported especially if obfuscated heavily like Lunar. However, anyone is welcome to submit a PR making ModernFix compatible with Lunar Client.
