### ISSUE TITLE
Iron's spells 'n spellbooks mod config not working as intended with ModernFix

### ISSUE THREAD

**Issue by Razor235T** [embeddedt/ModernFix#410]
### Bug Description

Adding weapons, for example a bow or shield, to the imbueWhitelist in Iron's spells 'n spellbooks mod config doesn't work as intended. After adding imbueWhitelist = ["minecraft:bow"], the bow should be able to be imbued on Arcane Anvil, but it flashes for a moment and then still can't be imbued.
Disabling all the ModernFix options doesn't do anything, issue still persists. Only uninstalling ModernFix fixes it. Also, on an integrated server issue sometimes fixes itself, but on a dedicated server it never does.

Also, I firstly described the problem on Iron's spells 'n Spellbooks github issue tracker, but I was told that ModernFix breaks forge config and they do no special config handling.

### Reproduction Steps

1. Install Iron's Spells 'n Spellbooks and dependencies on a server and a client
2. Install ModernFix on the server and the client
3. Try modifying imbueWhitelist in serverconfig, adding to it some item like a bow
4. Start and join dedicated server
5. Try imbuing the item in the game

### Log File

[latest.log](https://github.com/user-attachments/files/15539235/latest.log)

**Comment by embeddedt** [comment]
I've responded in your original issue on Iron's end. This is not a ModernFix bug. https://github.com/iron431/irons-spells-n-spellbooks/issues/454#issuecomment-2205948478
