### ISSUE TITLE
"Integrated server watchdog" casue single player use 100% of a single core.

### ISSUE THREAD

**Issue by lsadls** [embeddedt/ModernFix#417]
### Bug Description

When I am playing single player there is a cpu core always running at 100%. After some test I found out this is caused by "Integrated server watchdog" option, disable it make single player runs normally.
I have disabled watchdog in linux kernel parameter because it mess with my laptop's suspend, it may be the reason why this option goes wrong.
This option is default on, I suggest add a detection so when there is no watchdog in the system this option is default off. 

### Reproduction Steps

n/a

### Log File

n/a

**Comment by Jszp03** [comment]
yep

**Comment by embeddedt** [comment]
Unable to reproduce this issue in the latest version of ModernFix (for 1.20.1/1.21); tested in a void world to minimize CPU usage from any other parts of the game. CPU usage is roughly 30% with or without ModernFix installed.

**Comment by lsadls** [comment]
I have not touched minecraft since I opened this issue. Today I updated my mod and this problem is gone. If the mod didn't change the code related to watchdog then it could be some system setting that I changed somehow fixed it. This issue is no longer needed and I will close it.
