### ISSUE TITLE
Prevents Jigsaw Structures from generating in 1.21

### ISSUE THREAD

**Issue by BigPhobos** [embeddedt/ModernFix#420]
### Bug Description

Jigsaw Structures completely fail to generate when using this mod on Minecraft 1.21

### Reproduction Steps

Minecraft 1.21
Fabric Loader 0.15.11
ModernFix 5.18.1+mc1.21

Generate a new world and attempt to locate a Trial Chamber or other Jigsaw Structure

### Log File

[latest.log](https://github.com/user-attachments/files/15830334/latest.log)

**Comment by embeddedt** [comment]
Thanks for flagging this so quickly. 5.18.2 will be released in a few minutes with the fix.
