### ISSUE TITLE
Display problem after loading.

### ISSUE THREAD

**Issue by xbxct** [embeddedt/ModernFix#421]
### Bug Description

In version 5.18.1, a temporary font display artifact was noticed. This was noticed earlier, but as a result, this defect was eliminated on its own. The rrs mod disables the loading screen, which contributes to the appearance of artifact, but he are back in the new version of ModernFix. According to the assumption, we are talking about dynamic resources that either speed up or slow down something, which is why the game does not have time to load.
![Screenshot_2024-06-14-09-21-16-790_net kdt pojavlaunch firefly](https://github.com/embeddedt/ModernFix/assets/168722918/a2311548-7249-41c5-914b-9b8000f1f9d3)

### Reproduction Steps

start

### Log File

-

**Comment by embeddedt** [comment]
Does this happen with just ModernFix installed, without RRLS?

**Comment by xbxct** [comment]
No, the loading screen closes it all

**Comment by embeddedt** [comment]
I suspect, like you, it's an issue of RRLS no longer waiting for essential resources to load, and then ModernFix speeding up the launch enough to reveal the unloaded fonts. I would recommend not using RRLS in this case, the entire point of the loading screen is to allow resources to load. I'm doubtful this can be fixed on my end.
