### ISSUE TITLE
Item Frame and Glow Item Frame models do not render

### ISSUE THREAD

**Issue by Kaytra** [embeddedt/ModernFix#422]
### Bug Description

The Item Frame and Glow Item Frame models do not render when ModernFix version 5.18.2 for 1.21 is installed on Quilt 0.26.0-1.21

![2024-06-14_10 39 35](https://github.com/embeddedt/ModernFix/assets/86370363/6e1afd70-5d19-4a96-9195-590b3a22b081)
Item Frame is on the left, Glow Item Frame is above

I suspect that it may be an issue with how the mod is interacting with the template_item_frame model due to the fact that this issue is occurring to both the Item Frame and Glow Item Frame

### Reproduction Steps

1. fresh Install of the latest Quilt mod loader for 1.21 (quilt-loader-0.26.0-1.21)
2. add only ModernFix to the mods folder
3. join any minecraft world
4. place Item Frame or Glow Item Frame
5. Witness the broken model

### Log File

[latest.log](https://github.com/user-attachments/files/15841685/latest.log)

**Comment by embeddedt** [comment]
This will be fixed in 5.18.3 which should be released in a few minutes.
