### ISSUE TITLE
[Bug]: Missing items in search

### ISSUE THREAD

**Issue by Unleashed75** [embeddedt/ModernFix#425]
### Bug Description

Using Fabric loader 1.21 - 0.15.11

Mods installed;
fabric-api-0.100.1+1.21
jei-1.21-fabric-19.0.0.1
modernfix-fabric-5.18.2+mc1.21

In a new world where you are in creative, open inventory.
In the tab for searching items, search for Lightning Rod.
I expected to see Lightning Rods in the search results but it does not.
(Unknown if other items are missing from searches)

With both JEI and ModernFix installed, searching for Lightning Rod in the creative tab does not show up.
With either or both JEI or ModernFix is not installed things work normally.
Unsure which mod has the issue, so I am reporting to both.

FYI, Lightning Rod does show in the JEI search, but not in the Vanilla Creative Tab Search

### Reproduction Steps

Using Fabric loader 1.21 - 0.15.11

Mods installed;
fabric-api-0.100.1+1.21
jei-1.21-fabric-19.0.0.1
modernfix-fabric-5.18.2+mc1.21

In a new world where you are in creative, open inventory.
In the tab for searching items, search for Lightning Rod.
I expected to see Lightning Rods in the search results but it does not.
(Unknown if other items are missing from searches)

With both JEI and ModernFix installed, searching for Lightning Rod in the creative tab does not show up.
With either or both JEI or ModernFix is not installed things work normally.
Unsure which mod has the issue, so I am reporting to both.

FYI, Lightning Rod does show in the JEI search, but not in the Vanilla Creative Tab Search

### Log File

[latest.log](https://github.com/user-attachments/files/15874044/latest.log)

**Comment by Gbergz** [comment]
Same on NeoForge 1.21

**Comment by rainbows007** [comment]
I am also seeing this issue. Turning off mixin.perf.blast_search_trees was able to get those items to show up again.

**Comment by embeddedt** [comment]
Will be fixed in 5.18.4 by removing the `blast_search_trees` option (only for 1.21+); it is currently not worth it to reimplement properly. The creative search structures are generated by vanilla a lot more lazily in 1.21, which minimizes the benefit.

**Comment by genesy** [comment]
This still happens for me for version Forge minecraft-1.20.1  modernfix-5.18.10 
Tried setting blast search to false but still happening every other launch

**Comment by mateus3c** [comment]
might be a good idea to leave a note explaining that enabling blast_search_trees / blast_search_trees.force can cause this issue, it took me hours to found out what was causing it
