### ISSUE TITLE
Crash with Kiwi

### ISSUE THREAD

**Issue by SafeOfArsenal** [embeddedt/ModernFix#427]
### Bug Description

game crashes

### Reproduction Steps

not sure it only happens sometimes

### Log File

[latest.log](https://github.com/user-attachments/files/16022366/latest.log)
[crash-2024-06-27_18.34.00-client.txt](https://github.com/user-attachments/files/16022367/crash-2024-06-27_18.34.00-client.txt)

**Comment by embeddedt** [comment]
There is no crash in the attached log file, and the provided crash report is missing important context. Can you look for a `launcher_log.txt` file in `C:/Users/(your username)/curseforge/minecraft/Install`?
