### ISSUE TITLE
[Bug] Crash on Initialization Due to 'modernfix' in Conjunction with 'Just Enough Items (JEI)

### ISSUE THREAD

**Issue by Stanelbrow** [embeddedt/ModernFix#428]
### Bug Description

**Minecraft Version: 1.21 fabric**

**Mod Versions:**
- Just Enough Items (JEI): [jei-1.21-fabric-19.0.0.16]
- Modernfix: [modernfix-fabric-5.18.4+mc1.21]

Minecraft crashes during the initialization phase when using the mods 'Just Enough Items (JEI)' and 'modernfix' together. The error seems related to a missing class provided by 'modernfix' that is required by 'JEI'.

### Reproduction Steps

1. Install the mods 'Just Enough Items (JEI)' and 'modernfix'.
2. Launch Minecraft with these mods enabled.

### Log File

[crash-2024-07-03_09.21.13-client.txt](https://github.com/user-attachments/files/16086340/crash-2024-07-03_09.21.13-client.txt)

**Comment by Billetiado10** [comment]
I have same error

**Comment by yellowstudiosGa** [comment]
Also experiencing this issue

**Comment by embeddedt** [comment]
Will be fixed in 5.18.5, sorry about that.
