### ISSUE TITLE
(1.20.1 forge) elevator blocks don't show camouflage when dynamic resources is set to on

### ISSUE THREAD

**Issue by vinnyg0621** [embeddedt/ModernFix#429]
### Bug Description

I installed the open blocks elevator mod.
with this mod, you can camouflage elevator blocks to look like different blocks.
when I turned the dynamic resources option on, the camouflage is gone
![2024-07-04_16 25 20](https://github.com/embeddedt/ModernFix/assets/57818441/67739e2b-6be4-45e1-a801-51d505f35411)

### Reproduction Steps

1. turn dynamic resources to (on)
2. restart Minecraft
3. you will see an elevator block that's actually camouflaged but it's gone

### Log File

[latest.log](https://github.com/user-attachments/files/16103357/latest.log)

**Comment by embeddedt** [comment]
Thanks, fixed in 5.18.6.
