### ISSUE TITLE
[1.16.5] Lightspeed incompatibility

### ISSUE THREAD

**Issue by ghost** [embeddedt/ModernFix#43]
### Mod Loader

Forge 36.2.39

### Minecraft Version

1.16.5

### Mod Version

1.10.1

### Notes

Note: Conflict with Lightspeed. I am reporting this problem to the developers of both mods.

1. Run Minecraft.
2. Mod loader loading screen freezes.
3. Game crashes.

### Crash Report

[crash-2023-03-18_20.18.58-client.txt](https://github.com/embeddedt/ModernFix/files/11009899/crash-2023-03-18_20.18.58-client.txt)

**Comment by embeddedt** [comment]
Fixed in 1.11.1.
