### ISSUE TITLE
[1.20.1] REI crash

### ISSUE THREAD

**Issue by aolko** [embeddedt/ModernFix#430]
### Bug Description

Same as #395 but with 1.20.1 x https://modrinth.com/mod/rei/version/12.1.725+forge
modernfix: https://modrinth.com/mod/modernfix/version/JCb26GJk

### Reproduction Steps

1. Install modernfix
2. Install REI
3. Launch the game
4. Create/load a world

### Log File

log: https://mclo.gs/fF5N4Vn

**Comment by embeddedt** [comment]
Your log shows that you are using ModernFix 5.15.0, which is not the latest version.

**Comment by aolko** [comment]
> Your log shows that you are using ModernFix 5.15.0, which is not the latest version.

it is ***for neoforge***, according to modrinth

**Comment by embeddedt** [comment]
I fixed the marking on Modrinth, but it's generally fine to use Forge 1.20.1 mods on NeoForge 1.20.1, and vice versa. The restriction only applies to newer versions of Minecraft.
