### ISSUE TITLE
Neoforge 1.21 latest beta- Infinite loading

### ISSUE THREAD

**Issue by Handrail9** [embeddedt/ModernFix#431]
### Bug Description

Hello, I have run into an issue with ModernFix where it will cause the launcher to "bootloop" on the "Loading Mods" section of NeoForge when there are a large amount of mods present (in my case 121). Removing ModernFix gets rid of this bootloop so I assume this is because of ModernFix. The bootloop seemed to happen randomly as I added or removed mods, but the issue completely resided after removing ModernFix. 

### Reproduction Steps

1. Have a large amount of mods in the mods folder with ModernFix
2. Launch Minecraft

### Log File

[2024-07-06-6.log](https://github.com/user-attachments/files/16117622/2024-07-06-6.log)

**Comment by embeddedt** [comment]
This sounds more likely to be a race condition in one of your other mods, which ModernFix exacerbates by speeding up the game launch. 

Please add `mixin.feature.spam_thread_dump=true` at the bottom of `config/modernfix-mixins.properties`, relaunch the game, wait one minute, and send an updated game log.

**Comment by Handrail9** [comment]
[latest.log](https://github.com/user-attachments/files/16117652/latest.log)
Thanks for replying so fast. Looking through the debug myself I don't see what's wrong but I've also never been the greatest at reading logs. I appreciate your help! :)

**Comment by embeddedt** [comment]
I think I know what the issue is on my end, to confirm can you see if removing CreativeCore fixes the problem?

**Comment by Handrail9** [comment]
Disabling CreativeCore fixes the issue and ModernFix can be enabled :)

**Comment by embeddedt** [comment]
5.18.6 should fix this then.
