### ISSUE TITLE
[FORGE] [1.20.1] Crash with -Dmixin.debug.countInjections=true

### ISSUE THREAD

**Issue by Lolothepro** [embeddedt/ModernFix#432]
### Bug Description

launch Minecraft with -Dmixin.debug.countInjections=true crashes the game

### Reproduction Steps

launch Minecraft with -Dmixin.debug.countInjections=true

### Log File

https://mclo.gs/C0XdTEo

**Comment by embeddedt** [comment]
This is expected; some of the debug flags cause Mixin to reject mixins it normally accepts. I recommend not using the mod with this flag active.
