### ISSUE TITLE
Server crashed with ModernFix suspected

### ISSUE THREAD

**Issue by fred913** [embeddedt/ModernFix#437]
### Bug Description

Server crashed, forcibly stopped for ticking a world for too long. ModernFix is suspected in the crash report.

### Reproduction Steps

Run the server on Windows 22H2 (19045.4651) for hours (less than a day), then it crashed. 

*Note: it shouldn't be due to the player or world, since the server restarted and it didn't crash immediately :-(*

### Log File

[crash-2024-07-15_16.21.51-server.txt](https://github.com/user-attachments/files/16232265/crash-2024-07-15_16.21.51-server.txt)
[2024-07-15-1.edited.log](https://github.com/user-attachments/files/16232288/2024-07-15-1.edited.log)

**Comment by embeddedt** [comment]
The crash is likely not ModernFix's fault; this is just Forge's crash report analyzer falsely blaming a performance mod. I recommend installing Fullstack Watchdog to get a proper watchdog crash report as the default vanilla one cuts off too early to know what the cause was.

**Comment by fred913** [comment]
Thanks for clarification. I'll definitely try the mod you referenced. Have a good day bro :-)
