### ISSUE TITLE
Creative Menu completely breaks when JEI and ModernFix installed (Forge 1.20.1)

### ISSUE THREAD

**Issue by goldrat1** [embeddedt/ModernFix#438]
### Bug Description

Latest versions of ModernFix and JEI causes a bug that prevents the search function of the Creative menu completely. Items still appear in the creative menu search bar when nothing is typed, but typing anything into the bar causes all items to disappear.
![image](https://github.com/user-attachments/assets/dc7afbe7-b515-44a2-bf21-e4b7f65184f2)

Neither ModernFix nor JEI causes this issue but when they're both present together, the creative menu breaks.

### Reproduction Steps

1. Install latest versions of ModernFix and JEI on a fresh install of Forge 1.20.1 (v47.3.5)
2. Load into a world and attempt to search anything in the Creative Menu search bar.
3. Observe nothing.

### Log File

[latest.log](https://github.com/user-attachments/files/16247689/latest.log)

**Comment by embeddedt** [comment]
Thanks, will be fixed in 5.18.9; release should appear on CF/MR in a few minutes.

**Comment by mezz** [comment]
@embeddedt could you make ModernFix fall back on the vanilla search when the jei-compat breaks?
