### ISSUE TITLE
ModernFix and JEI crashes in the Creative Inventory

### ISSUE THREAD

**Issue by DracoHero** [embeddedt/ModernFix#439]
### Bug Description

**ModernFix** and **JEI** it crashes when I type the "@" symbol in the search bar of the creative inventory

### Reproduction Steps

1. Open Minecraft
2. Open World in Creative Mode
3. Open Creative Inventory
4. Write "@" in the search bar

### Log File

[crash-2024-07-17_13.55.13-client.txt](https://github.com/user-attachments/files/16272916/crash-2024-07-17_13.55.13-client.txt)

**Comment by embeddedt** [comment]
Should be fixed with 5.18.10.
