### ISSUE TITLE
Extremely high usage of jdk.internal.misc.Unsafe.park.

### ISSUE THREAD

**Issue by Renderthegreat** [embeddedt/ModernFix#440]
### Bug Description

While playing on my server out of nowhere the tick rate dropped to 0 tps. By pausing the server and using spark it shows that the jdk.internal.misc.Unsafe.park function was being over used.

### Reproduction Steps

I have no idea

### Log File

[2024-07-18-7.log](https://github.com/user-attachments/files/16301545/2024-07-18-7.log)

**Comment by embeddedt** [comment]
`Unsafe.park` indicates that the server thread is either waiting for the next tick, or waiting for a background thread to complete a task. When the async profiler is not used (as indicated by Spark in this log), it will falsely attribute time the server spends waiting as CPU time. You should look at other parts of the profile to identify what is actually causing the lag.
