### ISSUE TITLE
jei creative menu bug

### ISSUE THREAD

**Issue by DJXSTEVE** [embeddedt/ModernFix#442]
### Bug Description

When installed with JEI versions above 15.8.0.9, items do not appear in the creative search bar.

### Reproduction Steps

Install modernfix and any JEI versions above 15.8.0.9, go into creative and try search for something

### Log File

no log file

**Comment by embeddedt** [comment]
Please ensure you are using the latest version of ModernFix (5.18.10).

**Comment by DJXSTEVE** [comment]
Damn bruh ur quick at responding. Sorry for wasting your time, the bug no longer persists when the latest versions are downloaded.
