### ISSUE TITLE
The game crashed whilst rendering entity in world

### ISSUE THREAD

**Issue by Vinexo** [embeddedt/ModernFix#447]
### Bug Description

Playing with several mods
loading into the active singleplayer world with essentials mod : game crash
loading into another singeplayer world also with essentials mod game is not crashing
pls help

### Reproduction Steps

ew

### Log File

[message.txt](https://github.com/user-attachments/files/16418330/message.txt)

**Comment by embeddedt** [comment]
The crash is caused by the Medieval mod, not ModernFix. Specifically, it appears to be looking for code from some other "autoleveling" mod.
