### ISSUE TITLE
[Mod incompatibility or crash with latest modernfix build] 1.20.1

### ISSUE THREAD

**Issue by TheShadyyOneYT** [embeddedt/ModernFix#457]
### Bug Description

Game crashes prior to loading a new world with the latest version of modernfix for 1.20.1 fabric

### Reproduction Steps

1. Download Modernfix (newest version)
2. Download most recent modloader and api
3. launch the game
4. make a new world
5. game crashes during loading with error: `The game crashed whilst unexpected error
Error: java.lang.NullPointerException: Cannot read field "field_44912" because "this.field_4015.field_1724" is null`

Mod list (incase needed to re-produce):
![Screenshot 2024-08-24 213033](https://github.com/user-attachments/assets/fc3d8297-6a96-4065-b618-f8b32a1ffa87)
![Screenshot 2024-08-24 213044](https://github.com/user-attachments/assets/6f2a1133-3095-45fd-acdb-cd53ecaa637c)
![Screenshot 2024-08-24 213051](https://github.com/user-attachments/assets/cccd509d-bb44-4665-a4c5-d767a4a4817c)

### Log File

https://mclo.gs/R2zvguE

**Comment by TheShadyyOneYT** [comment]
I removed a couple of mods and the crash changed. It's something incompatible within sodium it seems, something it said like `GetVisibleChunkCount`: https://mclo.gs/oaQZo5z

this is what it looks like without sodium installed:
![2024-08-24_21 48 06](https://github.com/user-attachments/assets/93a466ff-5f0b-442c-9c72-c1aa2d20b636)

**Comment by embeddedt** [comment]
Please provide the full log file not just the crash report.

**Comment by TheShadyyOneYT** [comment]
https://mclo.gs/A6dnXSI `latest.log` if this isn't an issue for modernfix, I would love to know. I was certain at first, now I'm unsure.

**Comment by embeddedt** [comment]
This should be fixed by 5.19.4; there was a mixin conflict with Fluidlogged.

**Comment by TheShadyyOneYT** [comment]
> This should be fixed by 5.19.4; there was a mixin conflict with Fluidlogged.

Thanks for the clarification
