### ISSUE TITLE
Crash

### ISSUE THREAD

**Issue by Kasualix** [embeddedt/ModernFix#46]
> game version 1.16.5, mod version v1.11.1
> The first time entering a world, after exiting the world and re-entering the same world, the game will always get stuck at 100% world loading and then crash when trying to close the game.
> [minecraft-exported-crash-info-2023-03-24T15-36-42.zip](https://github.com/embeddedt/ModernFix/files/11059962/minecraft-exported-crash-info-2023-03-24T15-36-42.zip)

Report by others, I'm just a helper to submit issue.

**Comment by Kasualix** [comment]
latest.log: https://filebin.net/zqggik43u585o18d (SPAM WARN)
main part: https://pastebin.ubuntu.com/p/qXt56kzwQ5/
After installing shutupexperimentalsettings, he entered the game. And JEI loading seems to get stuck.
Then he opened the creative inventory screen & game crashed.

**Comment by Kasualix** [comment]
He found the actual conflict.
Between [TaC](https://www.curseforge.com/minecraft/mc-mods/timeless-and-classic-guns) and ModernFix
Mods env: modernfix，tac，curios api and obfuscate
crash report: [minecraft-exported-crash-info-2023-03-26T19-33-45.zip](https://github.com/embeddedt/ModernFix/files/11071483/minecraft-exported-crash-info-2023-03-26T19-33-45.zip)

**Comment by Kasualix** [comment]
solved & closed?

**Comment by embeddedt** [comment]
I think so.
