### ISSUE TITLE
MemoryLeak 1.20.1 Forge 47.3.0

### ISSUE THREAD

**Issue by Krimatoria** [embeddedt/ModernFix#460]
### Bug Description

1. modernfix-forge-5.19.4+mc1.20.1.jar
2. ferritecore-6.0.1-forge.jar

![image](https://github.com/user-attachments/assets/43e3afe0-730c-4b59-8644-bfe733bcf03a)
![2024-09-03_15 24 04](https://github.com/user-attachments/assets/b3c784d5-7e6a-4935-a963-506b09d86991)

I found that the memory is much larger than the allocated game. I have 16 GB of RAM. I allocated 7 GB for a large build, and recently discovered that Minecraft uses much more of the declared memory. Over time, this value overflows and grows...I tried to include a fix about memory leaks in your mod or dynamic resources, but nothing helps. The memory is growing anyway, I just installed your mod and Ferrite Core. That's what was in the log. Although nothing is installed except these mods, even the assembly is clean, nothing was installed on it except these mods

Although F3 in minecraft shows that as much memory is used as specified and the value of cleaning the "garbage collector", for example, is allocated 7, memory usage reaches 50% and is cleared.

I specifically launched a clean build with two mods (Ferrite Core + ModernFix) and set the memory limit to 1500. But it still exceeds it and grows further. Although a3 shows that everything is fine) Is there any way to fix this?

At the same time, there are no departures or roofs, no lags. Well, yes, there are in a large assembly, but they are more related to downloading chunks and TPS servers. At the same time, there are no departures or roofs, no lags. Well, yes, there are in a large assembly, but they are more related to downloading chunks and TPS servers. Although if there is actually a leak and the memory is clogged, perhaps this gives a lag.

### Reproduction Steps

Well, I wrote everything above)

**Comment by embeddedt** [comment]
This is normal behavior from Java; it will generally use at least a gigabyte more than you actually specify (more with larger heap sizes, in my experience). The amount you allocate is just for the Java heap; there are other parts of Java/Minecraft that use additional memory.

The best way to combat this is to just lower the heap size to compensate, or, if you have enough spare memory or it's not causing problems, ignore the extra memory usage and let the OS deal with it.

**Comment by Krimatoria** [comment]
> This is normal behavior from Java; it will generally use at least a gigabyte more than you actually specify (more with larger heap sizes, in my experience). The amount you allocate is just for the Java heap; there are other parts of Java/Minecraft that use additional memory.
> 
> The best way to combat this is to just lower the heap size to compensate, or, if you have enough spare memory or it's not causing problems, ignore the extra memory usage and let the OS deal with it.

Thank you))))) And I've been thinking for several hours that this is some kind of problem, but it turns out everything is fine)
