### ISSUE TITLE
[1.20.1] weird client crash when clicked on "Create New World"

### ISSUE THREAD

**Issue by vinnyg0621** [embeddedt/ModernFix#462]
### Bug Description

game crashes after clicking on the create new world button.

in the crash report it says "blue_skies:charoite does not exist". but why doesn't it exist?

[crash report here](https://mclo.gs/3leQH6t)

### Reproduction Steps

1. launch Minecraft
2. click on singleplayer
3. click on Create new world

### Log File

[latest.log](https://github.com/user-attachments/files/17091684/latest.log)

**Comment by embeddedt** [comment]
My guess is you have a Blue Skies add-on installed that adds recipes using its items, despite not having Blue Skies installed. I looked at your mod list and I see `create_blue_skies_compat` but not `blue_skies`.

**Comment by vinnyg0621** [comment]
oh i just saw i didn't have blue skies installed. thanks.
