### ISSUE TITLE
Dynamic Resources breaks GTCEu Modern's connected textures

### ISSUE THREAD

**Issue by ghost** [embeddedt/ModernFix#467]
### Bug Description

Dynamic Resources breaks connected textures in GTCEu Modern/LowDragLib

Dynamic Resources disabled:

![2024-10-03_17 28 01](https://github.com/user-attachments/assets/480cd41c-ddd4-4868-a187-88b51a45c5e7)

Dynamic Resources enabled:

![2024-10-03_17 28 49](https://github.com/user-attachments/assets/8445fb1b-5fdd-46da-aa6d-0229f80c22a4)

### Reproduction Steps

1. Enable dynamic resources
2. Place a few GTCEu Modern blocks next to each other (eg. coils of any kind)

### Log File

https://mclo.gs/adcCNIg

**Comment by Luviam** [comment]
I Can't unsee it now :(
Also can confirm this happens for me as well.

**Comment by embeddedt** [comment]
This is not easily fixable on my end. They rely on [looping over internal `ModelBakery` data structures](https://github.com/Low-Drag-MC/LDLib-Architectury/blob/c6302743ec8c86ae2add2ecd2ebe481f4517dada/forge/src/main/java/com/lowdragmc/lowdraglib/client/forge/ClientProxyImpl.java#L78-L134) to add the CTM functionality to models. The original ConnectedTexturesMod also does this, and I patch it, but I don't want to maintain an increasing number of bespoke patches for many mods doing the same thing. 

There are other ways for them to accomplish this that will work out of the box with dynamic resources, such as registering a custom model loader for their connected texture blocks, or using an existing CTM library that works with ModernFix like Athena, Fusion, etc.
