### ISSUE TITLE
The absence of the remove spawn chunks option

### ISSUE THREAD

**Issue by xbxct** [embeddedt/ModernFix#470]
### Bug Description

For some reason, the problem arose in a branch of another mod
https://github.com/RelativityMC/C2ME-fabric/issues/368

### Reproduction Steps

-

### Log File

-

**Comment by arbeloya** [comment]
I'm currently having the same problem using ModernFix in Simply Optimized.

**Comment by embeddedt** [comment]
This option was removed from ModernFix in 1.21 as you can accomplish the same thing by changing the vanilla `spawnChunkRadius` gamerule to 0.
