### ISSUE TITLE
Affinity's Holographic Stereopticon causes a EXCEPTION_ACCESS_VIOLATION

### ISSUE THREAD

**Issue by jitterdev** [embeddedt/ModernFix#472]
### Bug Description

placing the holographic stereopticon from affinity down will cause a EXCEPTION_ACCESS_VIOLATION.

### Reproduction Steps

i was using 0.1.1+1.20 of affinity and 5.19.4+mc.1.20.1 of modernfix on fabric 0.16.7. i placed down the holographic stereopticon with a world section imprinted, and my game crashed shortly after. disabling modernfix fixed this crash.

### Log File

[hs_err_pid30676.log](https://github.com/user-attachments/files/17482311/hs_err_pid30676.log)
https://mclo.gs/XFS1Sa1

**Comment by embeddedt** [comment]
This is probably a compatibility issue with another mod that frees memory without recording it (which causes ModernFix to try to free it again later); you can add `mixin.bugfix.buffer_builder_leak=false` at the bottom of `config/modernfix-mixins.properties` to work around it. I wasn't able to figure out what code in Affinity is responsible for this though.
