### ISSUE TITLE
Dynamic Resources causing  client crash upon joining on server with Origins mod 

### ISSUE THREAD

**Issue by Thspooks** [embeddedt/ModernFix#474]
### Bug Description

Whenever me and friend joins a server with mod installed after choosing an origin, we cannot join back after restarting the game, as if the mod is forcing the game to skip some things related to origin. Tho im not sure if thats what exactly happens, but just my assumption, i aint coder. I am leaving also Curseforge profile included. Tried every version but it seems happening on every single one. Ill try to provide as much as i can with hope this issue can be solved, the difference with and without the mod is big and removing it hurts
https://drive.google.com/file/d/1aUjiHrOah8M3aZwa-NoMtZgKlWTcX0ab/view?usp=sharing 

### Reproduction Steps

Install the curseforge profile
Create server
Join it, pick origin and close the game
Start the game back up
The game crashes 

### Log File

[latest (2).log](https://github.com/user-attachments/files/17607639/latest.2.log)

**Comment by embeddedt** [comment]
To me, this looks like a bug in Origins; the other errors from ModernFix are because the game is already in the process of crashing.

```
[14:43:44] [Render thread/ERROR]: Unreported exception thrown!
java.lang.IllegalArgumentException: Could not get layer from id 'origins:origin', as it doesn't exist!
	at io.github.apace100.origins.origin.OriginLayers.getLayer(OriginLayers.java:78) ~[Origins-1.20.1-1.10.0.jar:?]
	at io.github.apace100.origins.power.OriginsEntityConditions.lambda$register$1(OriginsEntityConditions.java:30) ~[Origins-1.20.1-1.10.0.jar:?]
	at io.github.apace100.apoli.power.factory.condition.ConditionFactory$Instance.isFulfilled(ConditionFactory.java:44) ~[apoli-2.9.0-2cf13cc7518c67a0.jar:?]
	at io.github.apace100.apoli.power.factory.condition.ConditionFactory$Instance.test(ConditionFactory.java:35) ~[apoli-2.9.0-2cf13cc7518c67a0.jar:?]
	at io.github.apace100.apoli.power.factory.condition.EntityConditions.lambda$register$1(EntityConditions.java:69) ~[apoli-2.9.0-2cf13cc7518c67a0.jar:?]
```

**Comment by Thspooks** [comment]
I thought so, but for some reason disabling dynamic resources fixed the crash. Mostly at least. RARELY (its been some time and happened only once as for now) that happens with it disabled, but with it enabled i cannot join at all. Since ive felt difference with modernfix's dynamic resources disabled i thought it fair to post the issue here (Also that origins for 1.20.1 has only one version and is completely "put aside" by devs). I do not say its not origins fault, but i do love dynamic resources and i wish to keep it on, but i am not sure how to go about i.

**Comment by embeddedt** [comment]
If the crash still occasionally happens with it disabled, it's more likely to be a timing-related bug in Origins than something on ModernFix's end.

There's a ton of mods installed here, so it's not really feasible for me to debug myself, is it possible to reproduce the issue with *just* ModernFix and Origins?

**Comment by Thspooks** [comment]
I will see, it is not my server that im joining so i cannot test is as a player. But i do have old laptop with a server on 1.20.1 set up for just me and friend, so i might as well test it on there with just these 2

**Comment by embeddedt** [comment]
Any updates here?

**Comment by BlueAmulet** [comment]
Happened again where a person was unable to join my server, getting this same error about 'origins:origin', and disabling ModernFix allowed them to join again, using DarkRPG pack.

Origins 1.10.0
ModernFix 5.25.2+mc1.20.1
