### ISSUE TITLE
[Mohist Server.jar] ModernFix mod Error

### ISSUE THREAD

**Issue by conetopia** [embeddedt/ModernFix#477]
### Bug Description

  Forge: net.minecraftforge:47.3.11[19:31:56 ERROR]: Failed to start the minecraft server
net.minecraftforge.fml.LoadingFailedException: Loading errors encountered: [
        ModernFix (modernfix) has failed to load correctly
§7java.lang.NoClassDefFoundError: net/minecraft/server/players/PlayerList

### Reproduction Steps

https://mohistmc.com/downloadSoftware?project=mohist&projectVersion=1.20.1
Download Server.jar  & Create a start.bat

Insert ModernFix into mods folder.

### Log File

[latest.log](https://github.com/user-attachments/files/17741645/latest.log)
Already contacted Mohist, and was recommended to make a issue/ticket to each mod. 

I understand a few other mods were listed, I have removed them, and created separate issue to them as well.

**Comment by embeddedt** [comment]
Hybrid servers tend to cause unexpected issues especially with performance mods so I don't officially support them. That said, you might be able to get ModernFix to work by turning off any conflicting options in the config file manually.
