### ISSUE TITLE
Add Support for MC-133685 (Depth Strider + Riptide in Water Bug)

### ISSUE THREAD

**Issue by NakyoykaN** [embeddedt/ModernFix#480]
[MC-136249](https://bugs.mojang.com/browse/MC-136249) Depth strider decreases Riptide's launching effect when underwater

    Fix: Ignore depth strider's increased drag while using riptide
    
Please add this one.  It was fixed via TieFix but that mod hasn't been updated since 2023.  Port over the fix?

**Comment by embeddedt** [comment]
Going to say no to this one, while I'm not *terribly* strict about keeping every single behavior element of vanilla accurate, I try not to change things that will have a noticeable impact on gameplay, especially not by default. I'd be willing to accept a PR if someone contributed it as an optional feature, though.

**Comment by NakyoykaN** [comment]
I am not a coder, however, I did find the source code for TieFix that does address this issue.  It's still not updated to Minecraft 1.21 but I thought the code might help as an alternative to a full on PR.

In this particular one it has a warning that it can trigger anticheat in multiplayer and is set to disabled by default.  I presume this should be retained - and players have to opt into it specifically via the settings.

https://github.com/j-tai/TieFix/blob/main/src/main/java/ca/jtai/tiefix/mixin/mc136249/LivingEntityMixin.java
