### ISSUE TITLE
IRIS Compatibility

### ISSUE THREAD

**Issue by xbxct** [embeddedt/ModernFix#481]
### Bug Description

When shaders are enabled, a crash occurs. 

### Reproduction Steps

Run shaders with the latest version of iris

### Log File

https://github.com/IrisShaders/Iris/issues/2533

**Comment by embeddedt** [comment]
That is an Iris bug; the only reason ModernFix is in the stacktrace is because you have an option enabled that applies all mixins at once to clear the memory afterwards.
