### ISSUE TITLE
mss structures having NBT problems due to this mod

### ISSUE THREAD

**Issue by VaporeonScripts** [embeddedt/ModernFix#483]
### Bug Description

https://mclo.gs/F1qTill

### Reproduction Steps

install this mod along MSS

### Log File

https://mclo.gs/F1qTill

**Comment by VaporeonScripts** [comment]
https://mclo.gs/nwlw7xZ

**Comment by embeddedt** [comment]
The same NBT errors appear when using this mod in a standalone instance without ModernFix.

**Comment by VaporeonScripts** [comment]
The error explicitally mentions a specific modern fix  mixin ,disabling it in the config fixes it:/
