### ISSUE TITLE
1.21.1 false 40k tps crash out

### ISSUE THREAD

**Issue by Joshernoob** [embeddedt/ModernFix#486]
### Bug Description

for some reason i can not seem to narrow down in my modpack im currently making, 1.21.1 neoforge when this mod is enabled and you load to many new chunks or sit for more then about 15 minutes, the game gives an error of 
A single server tick has taken 40001, more than 40000 milliseconds
Then thred dumps even though the game itself is still fine. do to this the game does not crash but will no longer load chunks or chest loot but I seem to be able to open chest i place myself.

Side note: if you keep the game going past the false crash it seems that the error will repeat itself but double the number each time. along with this I've also tested with no extrea "help mods" installed how i narrowed it to this one for sure

### Reproduction Steps

play personal pack with mod
wait for a bit or load enough chunks
false crash happens.

### Log File

[2024-12-08-7.log](https://github.com/user-attachments/files/18054897/2024-12-08-7.log)

**Comment by embeddedt** [comment]
The game is not fine if chunks/chest loot no longer load. ModernFix is not the cause of that problem, it just prints more diagnostic information to help with troubleshooting it.

The actual issue in this case appears to be Superior Smithing trying to load a chunk when a zombie is spawned as part of world generation.
