### ISSUE TITLE
1.20.1 Neoforge - JEI Incompatibility - Creative mode search

### ISSUE THREAD

**Issue by Hunter-495** [embeddedt/ModernFix#491]
### Bug Description

When using Vanilla minecraft's creative search, typing anything while JEI is installed will make the list go entirely blank.

### Reproduction Steps

1. Install both Modernfix and JEI (Note, JEI 1.20.1 is still on Forge, not Neoforge)
2. Enter or create a world with cheats/creative enabled
3. Go into Creative mode
4. Type anything into the Creative mode search bar (Compass tab)
5. The list of items should have gone blank

### Log File

N/A (Bug is in-game and doesn't result in a crash)

**Comment by embeddedt** [comment]
Please make sure you are using the latest version of JEI ([15.20.0.105](https://legacy.curseforge.com/minecraft/mc-mods/jei/files/5846810)) and ModernFix (5.19.6) and it should work. You may have to switch to Forge to be able to use the modern JEI. NeoForge 1.20.1 isn't maintained and some bugfixes/small features got added in newer Forge versions, so some mods require it.
