### ISSUE TITLE
Error with My Nethers Delight

### ISSUE THREAD

**Issue by Pineappleguy03** [embeddedt/ModernFix#492]
### Bug Description

Error when My Nether Delight  {re:mixin,re:classloading,pl:mixin:APP:modernfix-forge.mixins.json:perf.reduce_blockstate_cache_rebuilds.GameDataMixin,pl:mixin:A}

### Reproduction Steps

1: Download ModernFix and My Nethers Delight together
2: Boot up the server to cause the crash (Must use dedicated Server)

### Log File

![image](https://github.com/user-attachments/assets/416653eb-9e29-46cd-94d3-6332313d4159)

**Comment by Pineappleguy03** [comment]
Again this might not be ModernFix

I just posted in both

**Comment by embeddedt** [comment]
This is not a ModernFix bug, the crash report analyzer incorrectly blames it for that type of crash.
