### ISSUE TITLE
mixin.perf.worldgen_allocation causes AlexsCaves ConversionCrucibleBlockEntity crash

### ISSUE THREAD

**Issue by MoePus** [embeddedt/ModernFix#494]
### Bug Description

When mixin.perf.worldgen_allocation is enabled, using AlexsCaves ConversionCrucibleBlock could cause a crash
Only crash when game is running on a dedicated server, do not crash on client or local game.

The worldgen_allocation option made 
```public net.minecraft.world.level.levelgen.SurfaceRules$Context m_189576_(IIIIII)V # updateY``` in accesstransformers.cfg not work

### Reproduction Steps

Start a dedicated server with alex caves installed, and mixin.perf.worldgen_allocation enabled
Place a Conversion Crucible Block
Right click on the Conversion Crucible Block with a Biome Treat
Crash

### Log File

https://mclo.gs/2kCqhiI

**Comment by embeddedt** [comment]
Good catch, thanks; I'll push another 1.20.1 release shortly if there are no other reported issues in the next day or so.

**Comment by embeddedt** [comment]
Fixed in 5.20.0.
