### ISSUE TITLE
Menu Error

### ISSUE THREAD

**Issue by discrb** [embeddedt/ModernFix#496]
### Bug Description

When I open the game with the mod the game font just turn into a bunch  of [][][][][][] and when i try to open a world it crash the game.

### Reproduction Steps

I play minecraft 1.20.1 with forge in the official minecraft java from microsoft and the mod is in the correct version but I play with another mods that are:
AmbientSounds_FORGE_v6.1.4_mc1.20.1
appleskin-forge-mc1.20.1-2.5.1
BetterF3-7.0.2-Forge-1.20.1
carryon-forge-1.20.1-2.1.2.7
cherishedworlds-forge-6.1.7+1.20.1
cloth-config-11.1.136-forge
| CreativeCore_FORGE_v2.12.26_mc1.20.1
CustomPlayerModels-1.20-0.6.19a
eatinganimation-1.20.1-5.1.0
Fallingleaves-1.20-2.1.0-beta.1
gml-4.0.9-all
inventorysorter-1.20.1-23.0.8
Jade-1.20.1-Forge-11.12.2
jei-1.20.1-forge-15.20.0.105
OptiFine_1.20.1_HD_U_16
PickUpNotifier-v8.0.0-1.20.1-Forge
PuzzlesLib-v8.1.25-1.20.1-Forge
sit-1.20.1-1.3.5

### Log File

[latest.log](https://github.com/user-attachments/files/18159160/latest.log)

**Comment by embeddedt** [comment]
OptiFine is not supported; use Embeddium instead.
