### ISSUE TITLE
game crushed

### ISSUE THREAD

**Issue by Rhaaaaaast1** [embeddedt/ModernFix#497]
### Bug Description

when i get to create a new world,the game crushed(im not a english man)

### Reproduction Steps

just click single game and create a new world

### Log File

[crash-2024-12-18_13.05.56-client.txt](https://github.com/user-attachments/files/18175346/crash-2024-12-18_13.05.56-client.txt)

**Comment by embeddedt** [comment]
This appears to be a crash from Thermal Core, not ModernFix.
