### ISSUE TITLE
All tick-based updates stop happening on new chunk load

### ISSUE THREAD

**Issue by ModderOfGames** [embeddedt/ModernFix#498]
### Bug Description

I can't figure out what happens or why, but all I know is that after a while of playing when I load new chunks for the first time, the game will almost completely lock up. I can still move, but I can't enter/exit boats/other mounts, all mob AI completely stops functioning, breaking blocks works but they don't drop anything, and I can't load any new chunks. All I've really managed to figure out is that disabling the mod fixes this issue. 

This has happened on more than one world, too. I started a new one thinking maybe I'd accidentally corrupted my old one somehow, but now that the same thing has happened again and I've discovered that disabling ModernFix makes this issue go away I'm fairly confident it's some issue with this mod. I'm running Forge 1.19.2

### Reproduction Steps

1. Wander around a fair bit of your world, I'm not sure how much exactly but I'd say enough to the point that spawn is a fair ways out of render distance.
2. After walking into some-- not *all* apparently, but *some* new chunks, the game will lock up

that's really all I know about the bug, sorry if it's not particularly helpful.

### Log File

[latest.log](https://github.com/user-attachments/files/18191290/latest.log)

**Comment by ModderOfGames** [comment]
I want to point out that I've just learned setting "mixin.bugfix.chunk_dealock" too off fixes this as well. I'm not sure why considering this setting sounds like it should be preventing this issue, but I feel like this is important to note.

**Comment by embeddedt** [comment]
This is a bug in `dungeons_libraries`, their `EntityJoinLevelEvent` handler is buggy and tries to load more chunks when a chunk is already loading. You should report this to them.
