### ISSUE TITLE
Dynamic Resources incompatibility with Refined Storage

### ISSUE THREAD

**Issue by danny-janse** [embeddedt/ModernFix#499]
Refined storage works with patterns, when you've added a recipe to the pattern it shows the pattern icon by default. When you hold down shift, the icon should switch from the pattern icon to the icon of the item crafted by the recipe. Unfortunetly when enabling dynamic_resources, this feature seems to break.

I've ran into this issue in (AllTheMods) ATM 9 - v0.3.5 available on curseforge and debugged this based on the changes of the modpack, since it didnt have this issue previously.

After submitting this issue, i've also managed to reproduce this in a standalone installation as followed;
it is important to enable dynamic_resources before starting the game.
![image](https://github.com/user-attachments/assets/586d79fc-50b4-44cb-9c07-115114f2a674)

**Comment by halvalla01** [comment]
Definitely a ModernFix issue. Disabling MF did the trick on my end

**Comment by embeddedt** [comment]
Fixed in 5.20.0.
