### ISSUE TITLE
[QUESTION]

### ISSUE THREAD

**Issue by Willem07** [embeddedt/ModernFix#50]
Does this affect server latency? If so, is it possible to fix it?

`[Worker-Main-14/ERROR] [ModernFix/]: Can't read structure
java.io.FileNotFoundException: ctov:structures/village/mountain_alpine/deco/copper_golem.nbt`

[latest.log](https://github.com/embeddedt/ModernFix/files/11117166/latest.log)

> modernfix-mc1.19.2-3.2.1

**Comment by embeddedt** [comment]
I have fixed it already but haven't made a new release yet - will do so soon.
