### ISSUE TITLE
Crash Modpack with Modernfix

### ISSUE THREAD

**Issue by Meidde** [embeddedt/ModernFix#500]
### Bug Description

When modernfix is ​​in the modpack, it doesn't open and crashes

Version 1.20.1
Forge 47.3.12

Modernfix 5.19.7

### Reproduction Steps

Open the modpack and crash

### Log File

[crash-2024-12-26_12.35.25-client.txt](https://github.com/user-attachments/files/18255504/crash-2024-12-26_12.35.25-client.txt)

**Comment by embeddedt** [comment]
You have another mod that is changing the list of resource packs while the game is loading. ModernFix should not cause this issue, but launch optimizations often reveal timing-related bugs like this in other mods. Unfortunately, the error doesn't indicate what mod is at fault.
