### ISSUE TITLE
[1.20.1-Forge]Chunk Freeze

### ISSUE THREAD

**Issue by Git-Reternos** [embeddedt/ModernFix#502]
### Bug Description

chunk Freeze
This issues crash my game sometime
Dont know which mod conflict with modernfix

### Reproduction Steps

Walking around and step into a new chunk

### Log File

[2024-12-31-6.log](https://github.com/user-attachments/files/18282216/2024-12-31-6.log)

**Comment by embeddedt** [comment]
Try to remove `betterchunkloading`, but this doesn't look like a ModernFix issue.
