### ISSUE TITLE
Certain type of blocks won't render properly (I Like Wood, 1.18.2)

### ISSUE THREAD

**Issue by unzzerdawli** [embeddedt/ModernFix#51]
Using ModernFix (any version for 1.18.2) alongside with the I Like Wood mod (latest 1.18.2 version) causes the barrels from this mod to render as a missing texture block:
![2023-03-31_21 38 58](https://user-images.githubusercontent.com/54668342/229227657-b740818e-129a-4ecc-8d56-51903e27831d.png)
So any ILW barrel placed on the ground turns into an emo block. I haven't noticed any other blocks behaving this way.
  Disabling `mixin.perf.modern_resourcepacks` in the `modernfix-mixins.properties` file fixes the issue but makes the game launch slower.

  Open barrels, however, always render as intended:
![2023-03-31_21 40 02](https://user-images.githubusercontent.com/54668342/229227659-5464a895-7e38-4698-9a80-97784ab8da60.png)

  I tried to reproduce this bug in 1.19.2 but everything works fine (I can't update my modpack to this version tho). 
_I guess I really... Need the barrels..._

**Comment by embeddedt** [comment]
Thanks! This was reported and fixed on 1.16 a while ago and somehow the fix did not end up getting applied to 1.18. It's now fixed in 2.2.2.
