### ISSUE TITLE
Crash with Better Loading Screen on 1.18.2

### ISSUE THREAD

**Issue by xFirefalconx** [embeddedt/ModernFix#52]
Hi, I'm developing a modpack (update, actually). 
When adding your mod, it crashed on startup. 

I singled out that this mod alone with Better Loading Screen is causing the crash. if I deactivate either, it works again, testing on also just having both installed together crashes on a fresh modpack. Here's the report on the other side. 

https://github.com/shedaniel/BetterLoadingScreen/issues/46

I have no idea what can cause this but if you need any additional info or test runs, let me know, I am also interested in fixing this issue asap. 
If there are any additional mods you recommend in deactivating, please let me know as well. I might change the setup again, depending on what can be done about this issue. In doubt I will choose BLS over ModernFix. 

[crash-2023-04-03_19.22.08-client.txt](https://github.com/embeddedt/ModernFix/files/11142037/crash-2023-04-03_19.22.08-client.txt)
[latest.log](https://github.com/embeddedt/ModernFix/files/11142042/latest.log)

**Comment by embeddedt** [comment]
Hard for me to fix this on my end. Better Loading Screen injects into a bunch of vanilla code to show detailed loading information for models, etc., while ModernFix modifies the same code to improve launch speed.

BLS hasn't been updated in quite a while and as far as I know also crashes on some GPUs and setups.

> I might change the setup again, depending on what can be done about this issue. In doubt I will choose BLS over ModernFix.

Personally I think choosing a nice-looking loading screen over performance optimizations doesn't make a ton of sense, but it's not my modpack. :laughing: You can also try disabling `mixin.perf.faster_baking` in the config, since that appears to be the conflicting patch on my end, however I wouldn't recommend that.

**Comment by xFirefalconx** [comment]
Okay, do you know any other mods that do about the same, that probably work better than this combo? I might try them out. I just need something that comes close in visuals, tbf.

**Comment by embeddedt** [comment]
Unfortunately I am not aware of any other loading screen mods, unless all you care about is changing the background image or something like that.

**Comment by Kasualix** [comment]
Can you explain why you must use it?
I don't see any benefit to it.

**Comment by xFirefalconx** [comment]
The situation has changed as the dev told me there will be a rewrite. I'll check if the future version is hopefully going to be compatible. I don't use BLS in the meantime.

**Comment by electrified0** [comment]
There is a mod called [Drippy Loading Screen](https://www.curseforge.com/minecraft/mc-mods/drippy-loading-screenl) that does the same thing and seems to be compatible with ModernFix.

**Comment by Kasualix** [comment]
It allows you to customize the loading screen, but I don't think it can make the kind of display that BLS has, can it?

**Comment by Kasualix** [comment]
Note: shedaniel currently studies heavily for his university entrance examination on June 7th ～ 10th in China, which means he may not rework BLS before the day.

**Comment by embeddedt** [comment]
Closing for now as this cannot easily be solved on ModernFix's end.
