### ISSUE TITLE
1.16.5 Crash with Essential mod when pressing esc to open menu

### ISSUE THREAD

**Issue by SpecialtyK** [embeddedt/ModernFix#54]
When I press esc to open the menu the game crashes, so perhaps something involving the UI? If it is just ModernFix and Essential it works but I believe a combination of mods involving ModernFix is causing the issue from when I was trying to disable mods. I am having trouble narrowing down the exact combination though. Is there a mixin I could disable that might fix the issue? I am using the 1.16 required arguments for Java 17 if that helps. Crash log https://paste.ee/p/cKncu Full Log https://paste.ee/p/jienX

**Comment by Kasualix** [comment]
Maybe the error throwed by Essential is not real error, but this:
![image](https://user-images.githubusercontent.com/110756250/230764359-4cf10274-bcea-4e52-8420-4372357bf5ca.png)
Try delete Smooth Chunk Save?

**Comment by SpecialtyK** [comment]
That might be related to another issue I was having and will play without that mod but here is latest log without Smooth Chunk Save. It crashes the moment I open up my menu, but runs fine otherwise. https://paste.ee/p/C03U5

**Comment by Kasualix** [comment]
Oh, you have so many issues.
I would recommend you to do [this](https://github.com/embeddedt/ModernFix/issues/5#issuecomment-1374356722)

> Unfortunately, there are far too many mods to realistically narrow down the issue. It would be great if you could determine the minimum set of mods necessary to reproduce this (as it seems to be a specific incompatibility with one of your mods).

**Comment by SpecialtyK** [comment]
Ok I think I finally found the issue. A combination of Essential, ModernFix, and Time Core. Created a new instance with just those three mods installed and crashed at the main menu. https://paste.ee/p/Kdybz

**Comment by embeddedt** [comment]
I suspect it's an Essential issue; I didn't get a crash but I see the mod is making use of a thread pool which you cannot safely use on Forge, as it will cause classloading issues. That mod is known for causing problems in other packs as well.

**Comment by SpecialtyK** [comment]
Removing Time Core stops it from crashing in my setup so that is my solution for now. Looking at a previous crash report with Time Core it had issues with Java greater than 8 but was patched at least for Java 14. I am using Java 17 so that might be a related issue. I will see what Time Core and Essential devs say on the matter. Thank you for your time.

**Comment by SpecialtyK** [comment]
Talking with someone at Essential said the issue is not being able to convert the time to a friendlier format to display on the sale banner.  Nobody else was able to reproduce the crash because when tested the sale ended most likely.

**Comment by embeddedt** [comment]
Closing as I don't think there is much I can do from my end at the moment.
