### ISSUE TITLE
[1.18.2] Multiblocked missing textures

### ISSUE THREAD

**Issue by DerCommander323** [embeddedt/ModernFix#57]
When using ModernFix together with Multiblocked, custom Parts and Controllers will have a lot of missing textures. It seems not 100% of textures and only custom textures are affected (the custom textures are located in a seperate folder in the instance, which may be part of why this happens?)

latest.log: https://mclo.gs/mOaIDav

Modlist:
ModernFix v2.3.1
LazyDFU v0.1.3
Multiblocked v1.18.2-1.0.5a
LowDragLib v1.18.2-1.0.7a

Forge version 40.2.1, Minecraft 1.18.2

If you want to try this yourself, I just copied the `multiblocked` folder out of a Multiblock Madness 2 instance for testing

Screenshots:
![image](https://user-images.githubusercontent.com/80590706/232258894-8488f385-323e-453e-bf6a-9a4c10da28bf.png)

**Comment by embeddedt** [comment]
Did you explicitly enable `mixin.perf.dynamic_resources`?

**Comment by embeddedt** [comment]
Fixed in 2.3.2.
