### ISSUE TITLE
Mod Loading Error 1.18.2 Latest

### ISSUE THREAD

**Issue by Atlantispy** [embeddedt/ModernFix#58]
Latest Build

[crash-2023-04-16_17.45.38-fml.txt](https://github.com/embeddedt/ModernFix/files/11242887/crash-2023-04-16_17.45.38-fml.txt)

**Comment by embeddedt** [comment]
Full `latest.log` file, please. :)

**Comment by Atlantispy** [comment]
[latest.log](https://github.com/embeddedt/ModernFix/files/11242894/latest.log)

**Comment by embeddedt** [comment]
Thanks, will be fixed in the next release. Apparently you are the first person to use ModernFix and Modern UI together on 1.18.

**Comment by HockeyZman2000** [comment]
That's so strange. I played with ModernFix and Modern UI together on a 1.18 server, but when I moved to 1.19 that's when I got this null error

**Comment by embeddedt** [comment]
There is at least one release by now with the fix.
