### ISSUE TITLE
[Bug] Crash

### ISSUE THREAD

**Issue by wasdspace** [embeddedt/ModernFix#6]
modernfix: 1.4.0
[crash-2023-01-08_10.48.27-fml.txt](https://github.com/embeddedt/ModernFix/files/10367598/crash-2023-01-08_10.48.27-fml.txt)
[debug.log](https://github.com/embeddedt/ModernFix/files/10367599/debug.log)
[latest.log](https://github.com/embeddedt/ModernFix/files/10367601/latest.log)

**Comment by embeddedt** [comment]
I've released 1.4.1 as a hotfix. In the meantime you can use `mixin.perf.preload_block_classes=false` to disable the optimization in 1.4.0.
