### ISSUE TITLE
[Feature] A slightly gui optimization

### ISSUE THREAD

**Issue by Safixoo** [embeddedt/ModernFix#60]
I don't want to be annoying but i found a mod a small mod that optimizes the hud via caching a function (the mod in question https://modrinth.com/mod/seaborgium) and i thought i would be a nice addition and that makes sense with the theme of the mod because as far as im aware isn't the big thing but boosts fps and helps a lot to people who has a poor gpu, also the author in the description gives permission to people for decompiling the mod.

sorry if i'm being annoying, i didn't find a better way of asking this, and sorry for rusty english as well

**Comment by Roadhog360** [comment]
While they provide permission to decompile the mod permission to actually use the decompiled code is never provided.

**Comment by Safixoo** [comment]
i checked and 2 hours ago the mod changed license to ISC and the source went public, so yea i think now is interesting, i hope it helps in something :)

**Comment by embeddedt** [comment]
Looks like Seaborgium has Forge builds now.
