### ISSUE TITLE
1.18.2 Index 2 out of Bounds for length 2 (crash on startup)

### ISSUE THREAD

**Issue by border999** [embeddedt/ModernFix#61]
https://gist.github.com/border999/f5f9554c452294a533915780aa8fbfad
This probably is caused by an interaction between JAOPCA, JSON Things, and ModernFix

**Comment by border999** [comment]
https://github.com/TheLMiffy1111/JAOPCA/issues/276

**Comment by embeddedt** [comment]
It's an issue with JSON Things adding an extra resource pack type (vanilla only has one for client/server). I'll fix it from my end. Not an issue with JAOPCA.

**Comment by embeddedt** [comment]
Should be fixed in this beta: https://nightly.link/embeddedt/ModernFix/workflows/gradle/1.18/Package.zip

**Comment by border999** [comment]
can confirm, game loaded with this.
