### ISSUE TITLE
Dynamic resources and Connectedness not compatible

### ISSUE THREAD

**Issue by hyl5942850** [embeddedt/ModernFix#62]
1.19.2forge 43.2.6
when modernfix installed with connectedness in the same time,connect texture  support by connectedness can't work,such as it still have  gaps between glass block

**Comment by embeddedt** [comment]
Can't reproduce with only ModernFix and Connectedness installed. I added the Stay True resource pack and the connected textures from it seem to work as expected.

**Comment by embeddedt** [comment]
As far as I know this is not an issue in the latest ModernFix releases, at least with the default config.
