### ISSUE TITLE
Startup crash with ModernFix

### ISSUE THREAD

**Issue by LegendaryCrystalFox** [embeddedt/ModernFix#63]
Crashing on startup when adding the lastest version of 1.16.5 modernfix (1.13.0)

https://gist.github.com/LegendaryCrystalFox/add0afb171496e8bf5ae119bb1b31838

**Comment by embeddedt** [comment]
Try without OptiFine installed. If that works, add `mixin.bugfix.preserve_early_window_pos=false` to `config/modernfix-mixins.properties` and see if that fixes it.

**Comment by LegendaryCrystalFox** [comment]
I tired without OptiFine and it works but adding it back in and doing the config thing it doesnt work

**Comment by LegendaryCrystalFox** [comment]
Never mind I seem to have not done the config thing correctly I believe it is working now

**Comment by LegendaryCrystalFox** [comment]
Alright, thanks for your help!
