### ISSUE TITLE
Crash

### ISSUE THREAD

**Issue by wasdspace** [embeddedt/ModernFix#64]
1.16.5
https://github.com/embeddedt/ModernFix/actions/runs/4831359185

[crash-2023-04-28_22.40.03-client.txt](https://github.com/embeddedt/ModernFix/files/11354590/crash-2023-04-28_22.40.03-client.txt)
[latest.log](https://github.com/embeddedt/ModernFix/files/11354591/latest.log)

If no useful information is provided, I will find out the culprit later.

**Comment by embeddedt** [comment]
I know why it is happening, should be fixed in the next commit. I appreciate those brave enough to test the `main` branch. :wink:
