### ISSUE TITLE
Dynamic Resources bugs.

### ISSUE THREAD

**Issue by wasdspace** [embeddedt/ModernFix#65]
version: https://github.com/embeddedt/ModernFix/actions/runs/4833874810
config: `mixin.perf.dynamic_resources=true`

(1) mod: [refinedstorage-1.9.18](https://legacy.curseforge.com/minecraft/mc-mods/refined-storage/files/3807951)

Cover and Hollow Cover:
![2023-04-29_21 05 47](https://user-images.githubusercontent.com/85009668/235304445-b81ed937-1363-4da5-b447-3cee87308eaa.png)

(2) resourcepack: [VanillaTweaks_r738430.zip](https://github.com/embeddedt/ModernFix/files/11359251/VanillaTweaks_r738430.zip)
(https://vanillatweaks.net/picker/resource-packs/ -> 1.16 -> Age 25 Kelp -> Download)

![2023-04-29_21 08 13](https://user-images.githubusercontent.com/85009668/235304757-2bcbb40f-a4d9-45e1-96d4-c9301bd659d1.png)

Other than that I haven't encountered any other problems. And this feature is real a magic, reducing my modpack 20s' launch time and 1gb memory usage.

I never use the RELEASE version. hahahaha

**Comment by embeddedt** [comment]
Both should now be fixed. Appreciate the reports. :)
