### ISSUE TITLE
Game stuck after entering the world.

### ISSUE THREAD

**Issue by wasdspace** [embeddedt/ModernFix#66]
ModernFix: https://github.com/embeddedt/ModernFix/actions/runs/4839493281
[debug.log](https://github.com/embeddedt/ModernFix/files/11359651/debug.log)
[latest.log](https://github.com/embeddedt/ModernFix/files/11359648/latest.log)

Starting from line 6925. Search keywords: `java.lang.StackOverflowError`

`mixin.perf.fast_registry_validation=false` would resolve.

If no useful information provided, I will find out culprit later.

**Comment by embeddedt** [comment]
This confirms what I feared: the registry implementation is too complex to be worth rewriting for the average modpack. (I was playing with registering a million items and these changes had helped somewhat, but that's not exactly a normal use case.)

I've moved most of the new changes out into a separate option and disabled them; please confirm that the crash is gone with `fast_registry_validation` turned back on.

**Comment by wasdspace** [comment]
YOU ARE THE MODDING KING
