### ISSUE TITLE
Unknown blockstate property: 'inventory'.

### ISSUE THREAD

**Issue by wasdspace** [embeddedt/ModernFix#67]
ModernFix: https://github.com/embeddedt/ModernFix/actions/runs/4839493281
[debug.log](https://github.com/embeddedt/ModernFix/files/11359653/debug.log)
[latest.log](https://github.com/embeddedt/ModernFix/files/11359654/latest.log)
`mixin.perf.dynamic_resources=true`

**Comment by wasdspace** [comment]
If no useful information is provided, I will find out the culprit later.

**Comment by embeddedt** [comment]
Fixed, thanks.
