### ISSUE TITLE
[FR] Optimizations for Create Sifter

### ISSUE THREAD

**Issue by HitaloM** [embeddedt/ModernFix#68]
# Explanation

This issue is just a request, I'm currently playing the FTB Skies modpack where Create Sifter is very essential for resource generation, however they cause a very considerable FPS drop when looking at them, even with the modernfix and chunk rendering mixing of Rubidium enabled.

## Notes:

* I play on a dedicated server.
* FTB Skies v1.0.7
* Additional mods that are not included in the modpack: Rubidium Extras, EntityCulling, EntityCollisonFix. MemoryLeakFix, Starlight and Canary.

The list of mods for the modpack is listed here: https://www.feed-the-beast.com/modpacks/103-ftb-skies

## LOGs

Here's my spark profile (maybe it could be useful, I don't understand much of Spark): https://spark.lucko.me/3P6oOu2UHh

**Comment by embeddedt** [comment]
Thanks for the report. I recently spent some time looking into Create rendering, however it is honestly over my head and I am not sure of any quick optimizations that can be done. It might be worth reporting this to the Create Sifter developer(s). Another workaround would be to put the sifters inside a compact machine to avoid them impacting FPS for regular gameplay.
