### ISSUE TITLE
Rarely, text is displayed incorrectly with Modern UI installed

### ISSUE THREAD

**Issue by A0000Xz** [embeddedt/ModernFix#7]
At present, there are two situations. The first is that the number of items disappears after entering the archive. The second is that a single item is not affected, and the items with numbers all become "S".
Of course, these are all display problems, in fact, the number of items has not changed. And the probability of encountering it is relatively small, but it is quite annoying because I have to restart the game.

**Comment by embeddedt** [comment]
I assume you are using a translator, but unfortunately I am not sure what you mean by "archive". Also I will need to know the set of mods (ideally as small as possible) needed to reproduce the issue.

**Comment by A0000Xz** [comment]
Sorry, my English is not good, so I use translation software.
I mean "file".
Mod is the default setting and I haven't changed anything.
At present, I'm playing with several optimized mods such as "saturn", "ferrite core", "Starlight", "Road Runner","lazyDFU","ModernUI" ,and "Chlorine".The version is 1.16.5.
I will attach a picture later.

**Comment by A0000Xz** [comment]
![2023-01-14_08 58 35](https://user-images.githubusercontent.com/122650088/212442925-6369cb51-d9f3-40aa-99f6-db02cd452223.png)
![2023-01-14_08 58 26](https://user-images.githubusercontent.com/122650088/212442954-9b6027eb-ba4c-4f6a-bf82-c24d5fbfe767.png)
It seems that this is a strange question.

**Comment by embeddedt** [comment]
I see. Are these the only mods installed?

**Comment by A0000Xz** [comment]
There is a high probability that this will not happen when entering the file for the first time, but it will happen for the second time, but it is only for numbers, whether it is the displayed mob health or the number of items.
Of course, there are actually 75 mods, and I just picked out the ones that I think have great influence.
I'll list all mods for you later.

**Comment by embeddedt** [comment]
Unfortunately debugging with 75 mods installed is very difficult. :sweat_smile: Ideally that should be narrowed to a small set (ideally just ModernFix and a few others) that are necessary to reproduce the issue.

**Comment by A0000Xz** [comment]
Well, that's what I said above.
I guess this is in conflict with the font of "modern UI". In addition, that's all that can affect the display in all my mods.

**Comment by A0000Xz** [comment]
There is another bug, and I will build another issue.

**Comment by embeddedt** [comment]
I tested with just Modern UI and the performance mods you mentioned installed, but the issue did not appear. I will leave this issue open for now, but unfortunately I cannot really do anything to fix this unless there is a way of reproducing it reliably and with a small number of mods.

-------

As a side note, you might want to look into using Rubidium instead of Chlorine, as Chlorine is abandoned nowadays.

**Comment by A0000Xz** [comment]
Oh, I have to mention something about modernUI. Because of the configuration of my computer, I was lucky enough to find a beta version that can support my hardware.The version of modernUI is 1.16.5-2.5.1.86. Maybe the BUG I mentioned has been fixed by the latest official version. But at present, the generation of this stronghold is a bit strange.

**Comment by embeddedt** [comment]
Going to close this as I haven't gotten any more issue reports after changing the default `async_jei` state.
