### ISSUE TITLE
[1.16.5] Cause LDLib JEIPlugin log error

### ISSUE THREAD

**Issue by Kasualix** [embeddedt/ModernFix#70]
Error: https://pastebin.ubuntu.com/p/c5VHfRNnZ8/
env: LDLib & ModernFix & JEI, Java 17 & [JVM arguments](https://github.com/embeddedt/ModernFix/wiki/1.16---required-arguments-for-Java-17), Forge 36.2.39
[LDLib](https://legacy.curseforge.com/minecraft/mc-mods/ldlib) is a dependence of [Multiblocked](https://www.curseforge.com/minecraft/mc-mods/multiblocked)

**Comment by embeddedt** [comment]
Ideally they should fix this on their end, their code appears to assume the JEI plugin has finished loading when `RecipesUpdatedEvent` fires; if they just moved that code inside their plugin's `onRuntimeAvailable` method I think it would fix the issue.

**Comment by Kasualix** [comment]
[Done](https://github.com/MCTeamPotato/Opotato/commit/d582df48dfed6e4c393189d859425c7e7dd6ea5f) in [my mod](https://www.curseforge.com/minecraft/mc-mods/opotato). KilaBash has abandoned 1.16.5 for a long time and hopefully won't fix this in the future.
