### ISSUE TITLE
Scan and add all needed structures to DFU cache

### ISSUE THREAD

**Issue by Treeway7** [embeddedt/ModernFix#71]
It would be great to be able to cache every outdated structure in a modlist with a single command, rather than having to do it while loading chunks.

Even if that command takes a solid amount of time to process for an entire modpack, it's better than having to generate structure cache on the fly while players are exploring.

(My understanding of the DFU isn't that solid yet, but I've noticed it was causing very major lag spikes in my modpack - up to a minute of frozen chunk loading at a time.)

**Comment by embeddedt** [comment]
I just happened to be discussing this on Discord a few hours ago, a command to do this been added to the development builds.

**Comment by embeddedt** [comment]
`/modernfix upgradeStructures` is available in the latest versions.
