### ISSUE TITLE
[1.18.2 Fabric Dev build]random crash, rendering error

### ISSUE THREAD

**Issue by ZZZank** [embeddedt/ModernFix#72]
[crash-2023-05-04_16.29.01-client.txt](https://github.com/embeddedt/ModernFix/files/11395488/crash-2023-05-04_16.29.01-client.txt)
using the latest Dev build of ModernFix on modpack Create Astral 2.0.4b. 
Happened when signing into a world. 

Edit: the problem disappeared when I restart the game, but there's another problem: 
![2023-05-04_17 02 55](https://user-images.githubusercontent.com/47418975/236159456-c1ab7c04-9a23-43ee-9b9b-01ecc936d389.png)
These error blocks in the screenshots are glass blocks from Chipped. 
In 
[latest.log](https://github.com/embeddedt/ModernFix/files/11395679/latest.log)
I find thousands of lines of: 
`[17:00:17] [Render thread/WARN]: Unable to bake model: 'chipped:glass_pane_89#east=true,north=true,south=false,waterlogged=true,west=true': java.lang.NullPointerException: Cannot invoke "java.util.Set.iterator()" because "textureDependencies" is null`

**Comment by embeddedt** [comment]
Please try without DashLoader installed. Also, do you have dynamic resources enabled or disabled?

**Comment by ZZZank** [comment]
still look exactly the same with DashLoader removed, dynamicResources is always off.

**Comment by ZZZank** [comment]
I just tried again on a new MC instance with less mod installed, and it looks very, normal
![2023-05-04_22 53 38](https://user-images.githubusercontent.com/47418975/236247062-83a24239-5440-4b1a-a9a1-d96dfe395a5f.png)

And in the correspnding
[latest.log](https://github.com/embeddedt/ModernFix/files/11398794/latest.log)
I also find many lines of `Unable to bake model`, so there might be other mods causing the problem.

**Comment by ZZZank** [comment]
oh i get it. The problem appeared only when a certain resource pack provided by continuity is loaded: 
![2023-05-04_23 45 27](https://user-images.githubusercontent.com/47418975/236259832-a2a5d151-80af-47d9-835c-0ac6290c5f2d.png)
![2023-05-04_23 46 02](https://user-images.githubusercontent.com/47418975/236259891-85045722-41d6-49b1-90da-88392189c1cb.png)
when remove this resource pack: 
<img width="568" alt="image" src="https://user-images.githubusercontent.com/47418975/236260373-47e568af-011e-4b2a-9455-db6f9ea0bb41.png">
<img width="714" alt="image" src="https://user-images.githubusercontent.com/47418975/236260558-aec9f6f9-52b0-4f3e-9702-8206ccfcd6ab.png">

**Comment by embeddedt** [comment]
I still can't reproduce this, even with the resource pack. The only mods I have installed are Chipped, CTM for Fabric, Continuity, Create, Fabric API, ModernFix, and Mod Menu.

Like you, I also suspect there is another mod that is causing this incompatibility.

**Comment by ZZZank** [comment]
I removed more mods, and the problem still exists even when only

- chipped-fabric-1.18.2-2.0.1
- continuity-2.0.1+1.18.2
- ctm-fabric-1.0.0+1.18
- fabric-api-0.76.0+1.18.2
- modernfix-mc1.18.2-fabric-2.4.1-61-g7400782 (It's [the latest](https://github.com/embeddedt/ModernFix/actions/runs/4888415662))

are loaded. 
This means that this might not be other mods' problem.

**Comment by embeddedt** [comment]
Could you send the log from when it happens with just these mods?

**Comment by ZZZank** [comment]
[2023-05-05-7.log.gz](https://github.com/embeddedt/ModernFix/files/11402587/2023-05-05-7.log.gz)
I get this log when tried again on Java20(was Java17). The problem is the same, so I think this can be a valid log.

**Comment by embeddedt** [comment]
Finally fixed, thanks for your patience. :)

**Comment by ZZZank** [comment]
: )
