### ISSUE TITLE
Incompatibility With DashLoader & Suggestions

### ISSUE THREAD

**Issue by Talbe1** [embeddedt/ModernFix#75]
Hello, I noticed that ModernFix does not play nicely with DashLoader after the mod gets cached.
Upon attempting to launch the game for the **second** time after installing the mod, the 
loading bar gets stuck and doesn't move.

I would suggest you to clarify on the CurseForge and Modrinth pages of ModernFix
that there's an incompatibility with DashLoader, because I only found out about it
when I launched the game, and through the fabric.mod.json file.

I really do like ModernFix, should open an issue on DashLoader regarding the issue in order to solve it?

![image](https://user-images.githubusercontent.com/104154497/236548854-52101942-05a3-4243-a167-df222e993bc4.png)

Additionally, I have another suggestion, consider adding "tooltips" with explanations for the different 
modifications that the can be toggled on and off in the game?

**Comment by embeddedt** [comment]
How are you managing to launch the game? The intent of `breaks` is that it immediately triggers Fabric Loader to display an error dialog on launch.

![image](https://user-images.githubusercontent.com/42941056/236550027-531156c0-218a-40fb-9688-f46169420885.png)

**Comment by Talbe1** [comment]
I'm aware what the intent "breaks" does, although I was curious as for what would happen if I were to override it (**by deleting it**), since the incompatibility isn't actually mentioned on the download page of the mod.
To clarify, I have some experience "breaking" mods of developers (purely out of curiosity) and see what happens.

Here's a video that demonstrates how I managed to do it,
and it shows when the game gets stuck on launch.
I recommend watching the **entire** video.
https://user-images.githubusercontent.com/104154497/236609416-c34d2ff1-8777-4c5d-b1c5-b07b9fa7dc2a.mp4

**Comment by embeddedt** [comment]
This incompatibility is known and is why I don't support DashLoader. The mods change much of the same code and from my testing it's not worth the effort to make it work.
