### ISSUE TITLE
[Feature] Optimise Hashset

### ISSUE THREAD

**Issue by coco875** [embeddedt/ModernFix#76]
Try to find a way to better use Hashset to reduce memory and CPU
Here a exemple:
https://spark.lucko.me/7FShGimrLf
![image](https://user-images.githubusercontent.com/59367621/236573516-e4f83f34-51aa-41cd-bc9d-db25529d6b71.png)
is nearly 17% here and I think we can optise it

**Comment by embeddedt** [comment]
This appears to be code injected by Valkyrien Skies, please report this to them.

https://github.com/ValkyrienSkies/Valkyrien-Skies-2/blob/c3076eba2428b4bef3a4732aea55051d928f41ae/common/src/main/java/org/valkyrienskies/mod/mixin/server/world/MixinServerLevel.java#L117

**Comment by coco875** [comment]
oh ok
