### ISSUE TITLE
ETF Incompatibility?

### ISSUE THREAD

**Issue by An-thracene** [embeddedt/ModernFix#77]
<img width="716" alt="image" src="https://user-images.githubusercontent.com/96624949/236603493-fcb0a5a0-7792-4e8d-a31b-299346a0cbf2.png">

I'm using Glowing (https://modrinth.com/resourcepack/glowing) and it doesn't work.
But it seems that Continuity works well.

**Comment by embeddedt** [comment]
I need more information. Which Minecraft version/ModernFix version?

**Comment by An-thracene** [comment]
oh sorry for that
it's Fabric 1.19.2 and Modern Fix 3.5.0

**Comment by embeddedt** [comment]
Seems to work fine for me, did you install CTM Refabricated?

![2023-05-06_11 56 38](https://user-images.githubusercontent.com/42941056/236634405-cf7c778c-222f-4329-81db-34047d04ae69.png)

**Comment by An-thracene** [comment]
Strange. I've installed CTM Refabricated, but it still doesn't work for me.
<img width="835" alt="image" src="https://user-images.githubusercontent.com/96624949/236664127-1ead9b2a-eba9-4501-89cf-5e2eb3fd6128.png">

**Comment by embeddedt** [comment]
Do you have any other mods installed or did you change any mod options?

**Comment by An-thracene** [comment]
No. Only ETF, CTM Refabricated, Continuity, Modern Fix and Fabric API. All the mods are latest.

**Comment by embeddedt** [comment]
Any other resource packs installed? Could you also provide the `latest.log` file?

**Comment by embeddedt** [comment]
I figured out the difference from the log - you were using the OptiFine version of the emissive resource pack and I was using the CTM version. :sweat_smile: 

This issue will be resolved in the next release, or you can use the beta build once it finishes building in about 15 minutes.

**Comment by An-thracene** [comment]
thanks very much!

**Comment by embeddedt** [comment]
New release is now out.
