### ISSUE TITLE
mixin.perf.faster_texture_loading is incompatible with QSL

### ISSUE THREAD

**Issue by SplendidAlakey** [embeddedt/ModernFix#78]
**MC** 1.19.2
**[QSL](https://modrinth.com/mod/qsl)** 4.0.0-beta.30
**ModernFix** 3.5.0

The game simply crashes on startup, unless I set the config value `mixin.perf.faster_texture_loading=false`. Everything else seems to work perfectly fine. Let me know, if this needs to be reported to QSL, instead, especially since you didn't explicitly tag Quilt as supported.

Edit: I also can't find this feature on [the list](https://github.com/embeddedt/ModernFix/wiki/Summary-of-Patches).

Edit 2: This may actually be because QSL might be doing the same thing as this mixin.

Logs: https://gist.github.com/SplendidAlakey/83fb666055e33fe26cee4046500d49c8

**Comment by embeddedt** [comment]
Will be fixed in next release/when dev build finishes compiling.
