### ISSUE TITLE
[1.16.5] Client Crash on update to 1.14.0

### ISSUE THREAD

**Issue by MundM2007** [embeddedt/ModernFix#79]
**Describe the bug**
version 1.14.0 for minecraft forge is giving me a wierd client crashes with the main screen text looking like how in the following screenschot (ignore the background):
![image](https://user-images.githubusercontent.com/85188362/236628961-45ba8e4a-2ca4-4c4a-bc30-775c9c7c12e4.png)
For Logs see below:
[latest.log](https://github.com/embeddedt/ModernFix/files/11412510/latest.log)
[crash-2023-05-06_15.59.51-client.txt](https://github.com/embeddedt/ModernFix/files/11412512/crash-2023-05-06_15.59.51-client.txt)

**Expected behavior**
That the text shows like normal.

**Versions:**
- Modernfix: 1.14.0
- forge: 36.2.39 (newest, 1.16.5)

**Comment by embeddedt** [comment]
Will be fixed in the next release, see the README to download a beta if you want it sooner.
