### ISSUE TITLE
Conflict with hybrid server (Magma, etc.)

### ISSUE THREAD

**Issue by coco875** [embeddedt/ModernFix#80]
Crash with magma server
[latest.log](https://github.com/embeddedt/ModernFix/files/11412640/latest.log)

**Comment by embeddedt** [comment]
Hybrid servers aren't going to be supported officially, but by disabling some options you can likely make it work (here the crash appears to be caused by `mixin.perf.cache_strongholds`). You can also safely use ModernFix on clients even if it's not on a server.
