### ISSUE TITLE
Crash with Small Ships 1.18.2

### ISSUE THREAD

**Issue by 5stigma** [embeddedt/ModernFix#81]
modernFix mod V2.5.0 forge crash with Small Ship 1.18.2-2.0.0-Alpha-0.4.jar

[CrashReport](https://gist.github.com/5stigma/fd6956aea755feb42542deef3c9f4372)

1.- Only renders items for Small Ships ingame (any Cog item)
2.- Crash!!

**Comment by embeddedt** [comment]
Thanks for the report! This issue has been fixed and the fix will be available in the upcoming release. You can use a [development build](https://github.com/embeddedt/ModernFix/tree/main#development-builds-generally-stable-but-may-occasionally-have-bugs) if you want the fix sooner.
