### ISSUE TITLE
Can't disable mixin.perf.thread_priorities

### ISSUE THREAD

**Issue by HyperSoop** [embeddedt/ModernFix#82]
Upon trying to set `mixin.perf.thread_priorities=false`, the line gets reset. This log message might be relevant: `[09:32:56] [main/WARN]: Can't disable missing option mixin.perf.boost_worker_count`, though it appears on every startup.

**Comment by embeddedt** [comment]
If you have Smooth Boot installed it's already disabled automatically, that
might be why.

**Comment by HyperSoop** [comment]
That does check out. Though it probably shouldn't behave like that either way.

**Comment by embeddedt** [comment]
I agree that the current behavior is not ideal, but fixing it requires an overhaul of the config system, and the wiki that documents config options now notes that most options are on by default. As such I think I will leave things as they are for the time being. Thanks for noting this though.
