### ISSUE TITLE
crash with modernfix on 1.18.2

### ISSUE THREAD

**Issue by Xplodin** [embeddedt/ModernFix#83]
unsure what happened but it worked previously before updating to 2.5.0 but I also updated a bunch of other mods
[crash-2023-05-07_21.02.20-client.txt](https://github.com/embeddedt/ModernFix/files/11416947/crash-2023-05-07_21.02.20-client.txt)

here is my crash report I got when booting the game let me know if you need any more details.

**Comment by embeddedt** [comment]
Try with the dev build (see README).

**Comment by Xplodin** [comment]
Can I upload a patch to my modpack with the dev build included to CurseForge? Id be grateful as I got to push an update soon :)

**Comment by embeddedt** [comment]
Pushed 2.5.1 to CurseForge.
