### ISSUE TITLE
1.19.2 Render Thread Failure with mods when using `1.19.2-3.5.1`

### ISSUE THREAD

**Issue by P3rf3ctXZer0** [embeddedt/ModernFix#84]
Multiple mods broken - Mystical Agriculture, Botania, Patchuilli and probably more.

**Comment by ZZZank** [comment]
Can you provide crash report, or latest.log?

I'm not the Dev of this mod, but I know providing logs is always helpful

**Comment by P3rf3ctXZer0** [comment]
No because the crash log is all over the place. All I know for certain is that after I reverted back exactly one version is harmony was restored by process of elimination - that means that something changed in Modern fix which cascaded other issues.

**Comment by embeddedt** [comment]
The pack you linked above loaded without problems but I have an idea of how this could occur; please try the following beta build.

[test.zip](https://github.com/embeddedt/ModernFix/files/11421633/test.zip)

**Comment by P3rf3ctXZer0** [comment]
Alright also I have the following 
* Crash Log Client https://gist.github.com/P3rf3ctXZer0/0ea7a4ecb4af1a1cae20e7864b859520 
* Latest Log Client https://gist.github.com/P3rf3ctXZer0/5e7957bdca719b9a00b0d8224ec705f8
* Debug Log Client https://gist.github.com/P3rf3ctXZer0/5f85b8297878eed9374b3255a90628f6

**Comment by P3rf3ctXZer0** [comment]
@embeddedt is your beta build so supposed to take years to start? I started it at 8:45am and its 9:00am

**Comment by embeddedt** [comment]
Ok this build should fix everything unless I missed something.

[testt3.zip](https://github.com/embeddedt/ModernFix/files/11421925/testt3.zip)

**Comment by P3rf3ctXZer0** [comment]
![7eYsbRU 1](https://user-images.githubusercontent.com/10351221/236851232-400f46bd-6318-462c-87d6-c8c16b3baee9.jpeg)

It at least booted now 🗡️

**Comment by P3rf3ctXZer0** [comment]
You should push test 3 to public - the issue is resolved thanks @embeddedt
