### ISSUE TITLE
[1.18.2]  Creative Search Menu Broken when used with JEI

### ISSUE THREAD

**Issue by Reshy** [embeddedt/ModernFix#86]
Version:  modernfix-mc1.18.2-forge-2.5.1.jar

![2023-05-08_02 11 06](https://user-images.githubusercontent.com/2096384/236785806-f26c3a92-43bc-4cf6-bbc1-6d7886de5587.png)

The required mods for the bug to occur:
![mod incompatibility](https://user-images.githubusercontent.com/2096384/236827906-aacaa770-b3df-45a6-abac-7da01ae092ec.PNG)

**Comment by embeddedt** [comment]
Thanks for the report! This issue has been fixed and the fix will be available in the upcoming release. You can use a [development build](https://github.com/embeddedt/ModernFix/tree/main#development-builds-generally-stable-but-may-occasionally-have-bugs) if you want the fix sooner.
