### ISSUE TITLE
mixin.perf.faster_texture_loading breaks DirTNT

### ISSUE THREAD

**Issue by SplendidAlakey** [embeddedt/ModernFix#88]
**MC** 1.19.2
**ModernFix** 3.5.1
**[DirTNT](https://legacy.curseforge.com/minecraft/mc-mods/dirtnt/files/3823783)** 1.2-1.19

By default the 2 mods together will result in missing DirTNT textures and models:
![2023-05-08_18 51 37](https://user-images.githubusercontent.com/86702831/236886838-1a2b6fbb-a8b6-43b1-b50f-625ae5f553fa.png)

Setting `mixin.perf.faster_texture_loading=false` fixes that:
![2023-05-08_18 55 38](https://user-images.githubusercontent.com/86702831/236886775-0cc00fc4-8167-4682-b6a6-f48b32bb685b.png)

Let me know if this needs to be reported to DirTNT, instead.

Logs: https://gist.github.com/SplendidAlakey/c5dce876c047c7cfd8af3465e4e585a9

**Comment by LegendaryCrystalFox** [comment]
I was having the same issue with almost all the mods i had installed everything was just missing textures. Doing the mixin thing seemed to have fixed the issue.

**Comment by SplendidAlakey** [comment]
In my case DirTNT is the only mod, that has missing textures with ModernFix.

**Comment by embeddedt** [comment]
Thanks, I've applied that workaround on my end as well as compatibility with Stitch (the library DirTNT uses for textures) does not appear to be easy. The fix will be included in the next release or you can use the dev build.
