### ISSUE TITLE
mixin.bugfix.paper_chunk_patches slightly corrupts the chunkloading animation

### ISSUE THREAD

**Issue by SplendidAlakey** [embeddedt/ModernFix#89]
**MC** 1.19.2
**ModernFix** 3.5.1

Default settings, different distances from the spawn chunks are all black:
![2023-05-08_19 13 51](https://user-images.githubusercontent.com/86702831/236888745-270f5926-4163-4f47-a8c4-fa0967b0abbb.png)

`mixin.bugfix.paper_chunk_patches=false`, different distances from the spawn chunks are correctly colour coded:
![2023-05-08_19 16 12](https://user-images.githubusercontent.com/86702831/236888758-4727aaff-f952-4832-b94c-d222eeafedbe.png)

The issue is so minor, I don't even care if it's fixed, but figured I'd let you know anyway. Or it might not be an issue at all and the patch simply skips waiting for the further away chunks to generate?

Logs: https://gist.github.com/SplendidAlakey/ee3cd40bf83047df33990d84db5fa642

**Comment by embeddedt** [comment]
Working as intended; the `paper_chunk_patches` option does tweak how chunkloading works slightly. But thanks for your close attention. :)
