### ISSUE TITLE
Incompatible with SWEM + JEI

### ISSUE THREAD

**Issue by LegendaryCrystalFox** [embeddedt/ModernFix#9]
With just modernfix and jei installed the jei menu shows but when installing swem it doesnt show at all.

Mods installed:
jei-1.16.5-7.7.1.153
modernfix-mc1.16.5-1.4.2
geckolib-forge-1.16.5-3.0.103
player-animation-lib-forge-0.3.5+1.16.5
swem-1.16.5-0.5.3.4

LOG: https://pastebin.com/Jw88yTkm

**Comment by embeddedt** [comment]
Thanks! I believe it's fixed in 1.4.3.
