### ISSUE TITLE
(1.19.2) Mixin crash

### ISSUE THREAD

**Issue by ModernGamingWorld** [embeddedt/ModernFix#90]
A streamer trying to play my custom 1.19.2 pack crashed with this error and it looks to mention this mod in the crash log

[crash-2023-05-08_12.54.03-client.txt](https://github.com/embeddedt/ModernFix/files/11425554/crash-2023-05-08_12.54.03-client.txt)

**Comment by embeddedt** [comment]
They will probably need to use the beta until I release 3.5.2.
