### ISSUE TITLE
World not loading after 3.5.0 on 1.19.2

### ISSUE THREAD

**Issue by bootzin** [embeddedt/ModernFix#92]
Getting stuck at 0% when I try to load my existing world. I've been using 3.4.1 and after updating it stopped working. Reverting it back makes it load properly again.
Log says "[spark-java-sampler-0-3/WARN]: Timed out waiting for world statistics".
I'm using a lot of mods, so might be a bit hard to find the source of the issue, but do you know any changes that could have caused this? Or maybe any mods that could be conflicting?

**Comment by embeddedt** [comment]
Please try 3.5.2.

**Comment by bootzin** [comment]
I did just before posting. Using forge 43.2.8

**Comment by embeddedt** [comment]
Ok, can you send the `latest.log` file in case there is something useful?

**Comment by bootzin** [comment]
[2023-05-09-4.log.gz](https://github.com/embeddedt/ModernFix/files/11436424/2023-05-09-4.log.gz)

**Comment by embeddedt** [comment]
Hmm, unfortunately nothing useful there. Is this a modpack I can download from somewhere?

**Comment by bootzin** [comment]
No, it's custom. But I can share it with you, gimme me a moment

**Comment by bootzin** [comment]
https://drive.google.com/file/d/1zVIwDupLZvbqjDIFv1_FL7yz0dZoLTiM/view?usp=sharing
See if this works

**Comment by embeddedt** [comment]
The Fastload dev suggested this is likely an issue with the Forge port of their mod. After removing it I was able to generate and join a world with no issues, although it did take quite a while.

**Comment by bootzin** [comment]
Thank you very much for the help, but sadly it didn't work for me :/
Got the same error, even after disabling Fastload

**Comment by embeddedt** [comment]
Ok, can you try the following debug build? Install it, and attempt to load the world. After it freezes wait 1 minute and then send `latest.log`. It's been programmed to print extra debug information.

[testbuild.zip](https://github.com/embeddedt/ModernFix/files/11446423/testbuild.zip)

**Comment by embeddedt** [comment]
Two other suggestions after you send that log, in case I'm not available to look at it for a while:

* Check how much RAM you allocated to the game. I checked your log but unfortunately it didn't show it. With the current settings, I need 5GB to be able to join a world and based on the numbers I'm seeing I'd recommend 6. It may have been on the very edge with 3.4.1. Most people allocate enough but I figured it was worth mentioning.
* Try without Lightspeed - there is an issue I discovered in it that could cause freezes in some situations.

**Comment by bootzin** [comment]
I'll test it as soon as I can, but I think I might only be able to do so this weekend. I'll let you know when I do (:
But regarding RAM, I'm using 12~16Gb, using Aikar's flags. If anything, it might be too much

**Comment by embeddedt** [comment]
@bootzin Were you able to make any progress with this? I'd also be curious to hear if 3.6.0 resolves the issue.

**Comment by bootzin** [comment]
Hey, so, sadly, I was not able to check on it with the test build, but I just ran the instance with the 3.6.0 version and had no problems at all. Do you still want me to try the test build?

**Comment by embeddedt** [comment]
No, if it works in 3.6.0 let's assume it's fixed and we'll revisit if you run into problems again. Thanks for testing. :)
