### ISSUE TITLE
Abnormal texture of gtceu block（Forge1.19.2）

### ISSUE THREAD

**Issue by 08118651** [embeddedt/ModernFix#93]
When modernfix and gtceu were installed, some block textures in gtceu could not be displayed properly：
![2023-05-10_22 32 23](https://github.com/embeddedt/ModernFix/assets/89691619/c47e1f1d-a88e-4dd3-b2cf-b3b78c018419)
![2023-05-10_22 32 38](https://github.com/embeddedt/ModernFix/assets/89691619/20f55038-133b-44e9-aa06-77d06ccb7957)
When remove modernfix, the block textures load normally：
![2023-05-10_22 47 05](https://github.com/embeddedt/ModernFix/assets/89691619/61d27f33-94f2-43df-a445-51b5d8bd47b1)
![2023-05-10_22 47 13](https://github.com/embeddedt/ModernFix/assets/89691619/78237d20-8c30-4712-8d1e-19694b0831d4)

**Comment by 08118651** [comment]
mod verson：
gtceu-forge-1.19.2-1.0.2.jar
modernfix-mc1.19.2-forge-3.5.2.jar

**Comment by embeddedt** [comment]
Thanks for the report! This issue has been fixed and the fix will be available in the upcoming release. You can use a [development build](https://github.com/embeddedt/ModernFix/tree/main#development-builds-generally-stable-but-may-occasionally-have-bugs) if you want the fix sooner.

**Comment by embeddedt** [comment]
Fixed in latest release.
