### ISSUE TITLE
Dynamic Resources Textures Breaking [1.19.4]

### ISSUE THREAD

**Issue by R00tB33rMan** [embeddedt/ModernFix#94]
Dynamic Resources OFF: ![2023-05-11_21 44 47](https://github.com/embeddedt/ModernFix/assets/36140389/921dcb27-bb0b-45ec-bdd7-191bb4b8a92f)

Dynamic Resources ON: ![2023-05-11_21 47 45](https://github.com/embeddedt/ModernFix/assets/36140389/0ff6965e-c5f7-44fb-9d2b-2a7bcb8c6cb5)

Issue persists on: https://github.com/embeddedt/ModernFix/actions/runs/4949658091
And on: https://modrinth.com/mod/modernfix/version/4.0.0

Presumption: Only seems to occur in environments with highly modified resource packs/resource packs in genral.

Following mods are in use and that could initialize this conflict:
- ImmediatelyFast
- Sodium
- MoreCulling

**Comment by embeddedt** [comment]
Is this the default spawn point on Origin Realms?

**Comment by R00tB33rMan** [comment]
It is, yes. However, this persists in any region on OriginRealms

**Comment by embeddedt** [comment]
Fixed in next dev build.

**Comment by R00tB33rMan** [comment]
Perfect. Really appreciate your extremely hard work!

**Comment by embeddedt** [comment]
Fixed in current release. :)
