### ISSUE TITLE
Compressed Blockstate Causes Immediate Crash [1.19.4]

### ISSUE THREAD

**Issue by R00tB33rMan** [embeddedt/ModernFix#95]
Crash Log: https://pastebin.com/44MHRah1

When the compressed blockstate mixin/module is activated, the game will immediately crash. It appears it is explicitly mentioned as well, when the game crashes. All details regarding mods used, Quilt version/build, & etc. are mentioned in the crash report.

Issue persists on latest ModernFix release and latest development builds.

**Comment by embeddedt** [comment]
I recommend you do not use this option for now; it caused some weird
startup issues for me when I tested in a larger modpack.

**Comment by embeddedt** [comment]
Compressed blockstate was removed in the latest version.
