### ISSUE TITLE
1.18.2 FORGE 2.5.2 mod version

### ISSUE THREAD

**Issue by Orangejewce92** [embeddedt/ModernFix#98]
Hello, with this mod installed with Project MMO mod, hangs up on start up causing continuous crashes.
i will provide a crash report here:
[https://pastebin.com/4dFyAEMQ](url)

Thank you.

**Comment by embeddedt** [comment]
Please try the latest development build from the README and let me know if the issue persists.

**Comment by Orangejewce92** [comment]
I'm currently using the latest version on CF. For mc Forge 1.18.2 are you saying there's another version to try?

**Comment by embeddedt** [comment]
https://github.com/embeddedt/ModernFix#development-builds-generally-stable-but-may-occasionally-have-bugs

**Comment by Orangejewce92** [comment]
Awesome, I'll give this a go tomorrow.

**Comment by embeddedt** [comment]
Is this fixed with the latest release (2.6.0)?

**Comment by embeddedt** [comment]
The underlying cause of the reported lag was fixed in https://github.com/embeddedt/ModernFix/commit/a7e64f29476020e020707195368841f959d38cac, so I think this issue won't occur anymore.
